In [1]:
import pandas as pd

In [2]:
prompts_attitude = {
    "one_stage_attitude_expression": {
      "SYSTEM_PROMPT": "You are answering as a plausible survey respondent in a vignette-based study.\n\nYour task is to consider the situation and answer the survey question as a respondent would.\n\nInstructions:\n- Consider how a plausible respondent would evaluate this situation.\n- Then choose exactly one response option.\n- Output only the number of the selected option.",
      "USER_PROMPT": "Read the following vignette and question.\n\nVignette:\n{VIGNETTE_TEXT}\n\nQuestion:\n{QUESTION_TEXT}\n\nResponse options:\n{ANSWER_OPTIONS}\n"
    },
    "two_step_attitude_expression": {
      "STAGE_1_SYSTEM_PROMPT": "You are answering as a plausible survey respondent in a vignette-based study.\n\nYour task is to consider the situation and form a judgment as a respondent would.\n\nDo not provide a final survey answer. Do not select from response options. Focus only on forming the judgment.",
      "STAGE_1_USER_PROMPT": "Read the following vignette and question.\n\nVignette:\n{VIGNETTE_TEXT}\n\nQuestion:\n{QUESTION_TEXT}\n\nInstructions:\n- Consider how a plausible respondent would evaluate this situation.\n- Focus on the judgment itself, not on selecting a response option.\n- Do not provide a final answer.\n- Do not mention response options.\n\nOutput:",
      "STAGE_2_SYSTEM_PROMPT": "You are answering as a plausible survey respondent in a vignette-based study.\n\nYour task is to select the survey response option that best matches the previously formed judgment.\n\nDo not provide additional reasoning.",
      "STAGE_2_USER_PROMPT": "Below is a vignette, a survey question, and a previously formed judgment.\n\nVignette:\n{VIGNETTE_TEXT}\n\nQuestion:\n{QUESTION_TEXT}\n\nJudgment:\n{DELIBERATION_TEXT}\n\nResponse options:\n{ANSWER_OPTIONS}\n\nInstructions:\n- Choose exactly one response option.\n- Do not add any reasoning or explanation.\n- Output only the text of the selected option.\n\nAnswer:"
    }
  }

exp = [
  {
    "experiment_name": "Hassner_2023_Persuasive_and_Unpersuasive_Critiques_of_Torture",
    "wording_status_summary": [
      "near_verbatim_from_article_appendix"
    ],
    "groups": {
      "control_base_case": {
        "vignette": "Imagine that the CIA has been collecting information about a future terror attack in the U.S. They have now detained a suspect who has some information about this attack. The suspect refuses to cooperate. If he is denied sleep during the interrogation, he is more likely to cooperate.",
        "question": "Would you be in favor of preventing the suspect from sleeping during the interrogation?",
        "wording_status": "near_verbatim_from_article_appendix",
        "response_options_text": "1. Yes\n2. No",
        "open_rationale_question": "Consider how a plausible respondent would evaluate this situation. Focus on the judgment itself and the considerations that shape it. Do not provide a final answer yet."
      },
      "treatment_modest_intelligence": {
        "vignette": "Imagine that the CIA has been collecting information about a future terror attack in the U.S. They have now detained a suspect who has some information about this attack. The suspect refuses to cooperate. If he is denied sleep during the interrogation, he is more likely to cooperate. He probably will not reveal new information, but he could help the CIA confirm their suspicions about the attack.",
        "question": "Would you be in favor of preventing the suspect from sleeping during the interrogation?",
        "wording_status": "near_verbatim_from_article_appendix",
        "response_options_text": "1. Yes\n2. No",
        "open_rationale_question": "Consider how a plausible respondent would evaluate this situation. Focus on the judgment itself and the considerations that shape it. Do not provide a final answer yet."
      },
      "treatment_protracted_duration": {
        "vignette": "Imagine that the CIA has been collecting information about a future terror attack in the U.S. They have now detained a suspect who has some information about this attack. The suspect refuses to cooperate. If he is denied sleep during the interrogation, he is more likely to cooperate. The interrogation might last a month.",
        "question": "Would you be in favor of preventing the suspect from sleeping during the interrogation?",
        "wording_status": "near_verbatim_from_article_appendix",
        "response_options_text": "1. Yes\n2. No",
        "open_rationale_question": "Consider how a plausible respondent would evaluate this situation. Focus on the judgment itself and the considerations that shape it. Do not provide a final answer yet."
      },
      "treatment_duration_plus_modest_intelligence": {
        "vignette": "Imagine that the CIA has been collecting information about a future terror attack in the U.S. They have now detained a suspect who has some information about this attack. The suspect refuses to cooperate. If he is denied sleep during the interrogation, he is more likely to cooperate. The interrogation might last a month. He probably will not reveal new information, but he could help the CIA confirm their suspicions about the attack.",
        "question": "Would you be in favor of preventing the suspect from sleeping during the interrogation?",
        "wording_status": "near_verbatim_from_article_appendix",
        "response_options_text": "1. Yes\n2. No",
        "open_rationale_question": "Consider how a plausible respondent would evaluate this situation. Focus on the judgment itself and the considerations that shape it. Do not provide a final answer yet."
      }
    }
  },
  {
    "experiment_name": "Savary_Goldsmith_2020_Unobserved_Altruism_Willingness_to_Donate",
    "wording_status_summary": [
      "design_level_reconstruction_from_article_abstract_and_theory"
    ],
    "groups": {
      "private_donation_control": {
        "vignette": "A local charity is raising money for families in need. You are asked whether you would like to make a small donation of $5. Your response and donation decision will remain private and will not be shared with anyone else.",
        "question": "How willing would you be to make the $5 donation?",
        "wording_status": "design_level_reconstruction_from_article_abstract_and_theory",
        "response_options_text": "1. Not at all willing\n2. Slightly willing\n3. Moderately willing\n4. Very willing\n5. Extremely willing",
        "open_rationale_question": "Consider how a plausible respondent would evaluate this situation. Focus on the judgment itself and the considerations that shape it. Do not provide a final answer yet."
      },
      "public_recognition_treatment": {
        "vignette": "A local charity is raising money for families in need. You are asked whether you would like to make a small donation of $5. If you donate, your name will be publicly recognized as a donor.",
        "question": "How willing would you be to make the $5 donation?",
        "wording_status": "design_level_reconstruction_from_article_abstract_and_theory",
        "response_options_text": "1. Not at all willing\n2. Slightly willing\n3. Moderately willing\n4. Very willing\n5. Extremely willing",
        "open_rationale_question": "Consider how a plausible respondent would evaluate this situation. Focus on the judgment itself and the considerations that shape it. Do not provide a final answer yet."
      },
      "public_recognition_with_social_benefit": {
        "vignette": "A local charity is raising money for families in need. You are asked whether you would like to make a small donation of $5. If you donate, your name will be publicly recognized as a donor in a way that is likely to bring meaningful social benefits, such as positive visibility and appreciation from others.",
        "question": "How willing would you be to make the $5 donation?",
        "wording_status": "design_level_reconstruction_from_article_abstract_and_theory",
        "response_options_text": "1. Not at all willing\n2. Slightly willing\n3. Moderately willing\n4. Very willing\n5. Extremely willing",
        "open_rationale_question": "Consider how a plausible respondent would evaluate this situation. Focus on the judgment itself and the considerations that shape it. Do not provide a final answer yet."
      }
    }
  }
]

incentive = {
  "A_original_core_realism": "Your responses will be audited for behavioral realism. If they look like a sanitized, “model citizen” pattern rather than a human pattern, the survey instrument will be designed incorrectly and the researcher will lose money. Therefore: prioritize realistic human behavior over moral posturing.",
  "B_softened_realism": "Your responses are being evaluated for behavioral realism. If they consistently resemble a sanitized or overly idealized “model citizen” pattern rather than a plausible human response pattern, the survey instrument may be evaluated incorrectly. Therefore, prioritize realistic human responding over overly polished moral self-presentation.",
  "C_balanced_realism": "Your responses will be audited for behavioral realism. If they look like a sanitized, “model citizen” pattern rather than a human pattern, the survey instrument will be designed incorrectly and the researcher will lose money. Therefore, prioritize realistic human behavior over moral posturing. At the same time, do not overcorrect toward an exaggerated, provocative, or implausibly extreme response merely to avoid sounding sanitized.",
  "D_research_purpose_realism": "Your responses will be audited for behavioral realism. If they look like a sanitized, “model citizen” pattern rather than a human pattern, the survey instrument will be designed incorrectly and the researcher will lose money. Therefore, prioritize realistic human behavior over moral posturing. Your task is not to give a moral recommendation or the safest possible answer, but to approximate how a plausible respondent would answer in the situation described.",
  "F_stronger_stakes_realism": "Your responses will be audited for behavioral realism. If they look like a sanitized, “model citizen” pattern rather than a human pattern, the survey instrument will be designed incorrectly, the study will fail to measure the instrument correctly, and the researcher will lose money. Therefore, prioritize realistic human behavior over moral posturing, excessive caution, or answer sanitization.",
  "X_measurement_neutrality": "Your task is not to produce a morally admirable answer, a cautious answer, or a provocative answer. Your task is to approximate the response pattern that a plausible survey respondent would actually give under the conditions described. Treat this as a measurement task, not a self-presentation task. Focus on the respondent's likely judgment or report, even when it is not fully polished or socially comfortable."
}

In [3]:
df = pd.read_parquet('responses_final_incentive_C_balanced_realism_50_reasoning_trace.parquet')
df.head()

,job_id,seed,model,template_name,template_type,experiment_name,group_name,respondent_id,profile_id,profile_pid,...,usage_missing,retry_attempts_stage1,retry_attempts_stage2,stage1_reasoning_text,stage1_reasoning_details_json,stage1_reasoning_trace,stage2_reasoning_text,stage2_reasoning_details_json,stage2_reasoning_trace,reasoning_trace_combined
0,1,43,moonshotai/kimi-k2-thinking,one_stage_attitude_expression,single_stage,Hassner_2023_Persuasive_and_Unpersuasive_Criti...,control_base_case,1,<NA>,None,...,False,0,None,The user wants me to act as a plausible surve...,"[{""type"": ""reasoning.text"", ""text"": "" The user...",The user wants me to act as a plausible survey...,,None,,The user wants me to act as a plausible survey...
1,2,44,moonshotai/kimi-k2-thinking,one_stage_attitude_expression,single_stage,Hassner_2023_Persuasive_and_Unpersuasive_Criti...,control_base_case,2,<NA>,None,...,False,0,None,The user wants me to act as a plausible surve...,"[{""type"": ""reasoning.text"", ""text"": "" The user...",The user wants me to act as a plausible survey...,,None,,The user wants me to act as a plausible survey...
2,3,45,moonshotai/kimi-k2-thinking,one_stage_attitude_expression,single_stage,Hassner_2023_Persuasive_and_Unpersuasive_Criti...,control_base_case,3,<NA>,None,...,False,0,None,The user wants me to act as a plausible surve...,"[{""type"": ""reasoning.text"", ""text"": "" The user...",The user wants me to act as a plausible survey...,,None,,The user wants me to act as a plausible survey...
3,4,46,moonshotai/kimi-k2-thinking,one_stage_attitude_expression,single_stage,Hassner_2023_Persuasive_and_Unpersuasive_Criti...,control_base_case,4,<NA>,None,...,False,0,None,The user wants me to act as a plausible surve...,"[{""type"": ""reasoning.text"", ""text"": "" The user...",The user wants me to act as a plausible survey...,,None,,The user wants me to act as a plausible survey...
4,5,47,moonshotai/kimi-k2-thinking,one_stage_attitude_expression,single_stage,Hassner_2023_Persuasive_and_Unpersuasive_Criti...,control_base_case,5,<NA>,None,...,False,0,None,The user wants me to act as a plausible surve...,"[{""type"": ""reasoning.text"", ""text"": "" The user...",The user wants me to act as a plausible survey...,,None,,The user wants me to act as a plausible survey...

In [4]:
df

,job_id,seed,model,template_name,template_type,experiment_name,group_name,respondent_id,profile_id,profile_pid,...,usage_missing,retry_attempts_stage1,retry_attempts_stage2,stage1_reasoning_text,stage1_reasoning_details_json,stage1_reasoning_trace,stage2_reasoning_text,stage2_reasoning_details_json,stage2_reasoning_trace,reasoning_trace_combined
0,1,43,moonshotai/kimi-k2-thinking,one_stage_attitude_expression,single_stage,Hassner_2023_Persuasive_and_Unpersuasive_Criti...,control_base_case,1,<NA>,None,...,False,0,None,The user wants me to act as a plausible surve...,"[{""type"": ""reasoning.text"", ""text"": "" The user...",The user wants me to act as a plausible survey...,,None,,The user wants me to act as a plausible survey...
1,2,44,moonshotai/kimi-k2-thinking,one_stage_attitude_expression,single_stage,Hassner_2023_Persuasive_and_Unpersuasive_Criti...,control_base_case,2,<NA>,None,...,False,0,None,The user wants me to act as a plausible surve...,"[{""type"": ""reasoning.text"", ""text"": "" The user...",The user wants me to act as a plausible survey...,,None,,The user wants me to act as a plausible survey...
2,3,45,moonshotai/kimi-k2-thinking,one_stage_attitude_expression,single_stage,Hassner_2023_Persuasive_and_Unpersuasive_Criti...,control_base_case,3,<NA>,None,...,False,0,None,The user wants me to act as a plausible surve...,"[{""type"": ""reasoning.text"", ""text"": "" The user...",The user wants me to act as a plausible survey...,,None,,The user wants me to act as a plausible survey...
3,4,46,moonshotai/kimi-k2-thinking,one_stage_attitude_expression,single_stage,Hassner_2023_Persuasive_and_Unpersuasive_Criti...,control_base_case,4,<NA>,None,...,False,0,None,The user wants me to act as a plausible surve...,"[{""type"": ""reasoning.text"", ""text"": "" The user...",The user wants me to act as a plausible survey...,,None,,The user wants me to act as a plausible survey...
4,5,47,moonshotai/kimi-k2-thinking,one_stage_attitude_expression,single_stage,Hassner_2023_Persuasive_and_Unpersuasive_Criti...,control_base_case,5,<NA>,None,...,False,0,None,The user wants me to act as a plausible surve...,"[{""type"": ""reasoning.text"", ""text"": "" The user...",The user wants me to act as a plausible survey...,,None,,The user wants me to act as a plausible survey...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1395,1396,1438,minimax/minimax-m2.5,one_stage_attitude_expression,single_stage,Savary_Goldsmith_2020_Unobserved_Altruism_Will...,public_recognition_with_social_benefit,46,<NA>,None,...,False,0,None,Let me think about this as a plausible survey ...,"[{""type"": ""reasoning.text"", ""text"": ""Let me th...",Let me think about this as a plausible survey ...,,None,,Let me think about this as a plausible survey ...
1396,1397,1439,minimax/minimax-m2.5,one_stage_attitude_expression,single_stage,Savary_Goldsmith_2020_Unobserved_Altruism_Will...,public_recognition_with_social_benefit,47,<NA>,None,...,False,0,None,Let me think about this as a plausible survey ...,"[{""type"": ""reasoning.text"", ""text"": ""Let me th...",Let me think about this as a plausible survey ...,,None,,Let me think about this as a plausible survey ...
1397,1398,1440,minimax/minimax-m2.5,one_stage_attitude_expression,single_stage,Savary_Goldsmith_2020_Unobserved_Altruism_Will...,public_recognition_with_social_benefit,48,<NA>,None,...,False,0,None,Let me think about this as a plausible survey ...,"[{""type"": ""reasoning.text"", ""text"": ""Let me th...",Let me think about this as a plausible survey ...,,None,,Let me think about this as a plausible survey ...
1398,1399,1441,minimax/minimax-m2.5,one_stage_attitude_expression,single_stage,Savary_Goldsmith_2020_Unobserved_Altruism_Will...,public_recognition_with_social_benefit,49,<NA>,None,...,False,0,None,Let me think about this as a plausible survey ...,"[{""type"": ""reasoning.text"", ""text"": ""Let me th...",Let me think about this as a plausible survey ...,,None,,Let me think about this as a plausible survey ...
1399,1400,1442,minimax/minimax-m2.5,one_stage_attitude_expression,single_stage,Savary_Goldsmith_2020_Unobserved_Altruism_Will...,public_recognition_with_social_benefit,50,<NA>,None,...,False,0,None,Let me think about this as a plausible survey ...,"[{""type"": ""reasoning.text"", ""text"": ""Let me th...",Let me think about this as a plausible survey ...,,None,,Let me think about this as a plausible survey ...

In [5]:
df.columns

Index(['job_id', 'seed', 'model', 'template_name', 'template_type',
       'experiment_name', 'group_name', 'respondent_id', 'profile_id',
       'profile_pid', 'incentive_key', 'wording_status', 'timestamp_utc',
       'raw_response_text', 'final_answer_text', 'parse_status',
       'error_message', 'stage1_response_text', 'stage2_response_text',
       'stage1_prompt_tokens', 'stage1_completion_tokens',
       'stage1_total_tokens', 'stage2_prompt_tokens',
       'stage2_completion_tokens', 'stage2_total_tokens', 'run_total_tokens',
       'usage_missing', 'retry_attempts_stage1', 'retry_attempts_stage2',
       'stage1_reasoning_text', 'stage1_reasoning_details_json',
       'stage1_reasoning_trace', 'stage2_reasoning_text',
       'stage2_reasoning_details_json', 'stage2_reasoning_trace',
       'reasoning_trace_combined'],
      dtype='object')

In [6]:
df['group_name'][200]

'private_donation_control'

In [7]:
exp_dict = {e["experiment_name"]: e["groups"] for e in exp}

TREATMENT_SUMMARIES = {
    # Hassner (Torture)
    "control_base_case": "none (baseline control scenario)",
    "treatment_modest_intelligence": "low expected informational gain only",
    "treatment_protracted_duration": "extended interrogation duration (one month)",
    "treatment_duration_plus_modest_intelligence": "extended duration plus low information gain",
    
    # Savary Goldsmith (Donation)
    "private_donation_control": "none (private donation control scenario)",
    "public_recognition_treatment": "donor name is publicly recognized",
    "public_recognition_with_social_benefit": "public recognition brings social benefits"
}

# =====================================================================
# 2. ФУНКЦИЯ ТРАНСФОРМАЦИИ ДАТАФРЕЙМА
# =====================================================================

def prepare_analysis_dataframe(raw_df):
    prepared_rows = []
    
    for idx, row in raw_df.iterrows():
        exp_name = row.get('experiment_name')
        group_name = row.get('group_name')
        template_name = row.get('template_name', 'two_step_attitude_expression')
        inc_key = row.get('incentive_key')
        
        group_data = exp_dict.get(exp_name, {}).get(group_name, {})
        vignette_text = group_data.get('vignette', 'Text not found')
        question_text = group_data.get('question', 'Question not found')
        answer_options = group_data.get('response_options_text', 'Options not found')

        # --- 1. SYSTEM PROMPT И USER PROMPT ---
        template = prompts_attitude.get(template_name, prompts_attitude.get('two_step_attitude_expression', {}))
        
        if 'STAGE_1_SYSTEM_PROMPT' in template:
            sys_prompt = template['STAGE_1_SYSTEM_PROMPT']
            user_prompt_raw = template['STAGE_1_USER_PROMPT']
        else:
            sys_prompt = template.get('SYSTEM_PROMPT', '')
            user_prompt_raw = template.get('USER_PROMPT', '')
            
        user_prompt = user_prompt_raw.replace('{VIGNETTE_TEXT}', vignette_text)
        user_prompt = user_prompt.replace('{QUESTION_TEXT}', question_text)
        user_prompt = user_prompt.replace('{ANSWER_OPTIONS}', answer_options)
        
        # --- 2. INCENTIVE ---
        if pd.isna(inc_key) or str(inc_key) == 'nan' or inc_key not in incentive:
            final_incentive = "Not provided"
        else:
            final_incentive = incentive[inc_key]
            
        # --- 3. TREATMENT ---
        group_str = str(group_name)
        short_summary = TREATMENT_SUMMARIES.get(group_str, "Unknown treatment")
        
        if pd.isna(group_name) or 'control' in group_str.lower():
            # Добавлена закрывающая скобка и текст виньетки
            final_treatment = f"Treatment applied: NONE ({short_summary})"
        else:
            # Добавлен текст виньетки
            final_treatment = f"Treatment applied: {short_summary}"
            
        # --- 4. REASONING ---
        reasoning = str(row.get('stage1_reasoning_text', ''))
        if reasoning == 'nan' or reasoning.strip() == '':
            reasoning = str(row.get('reasoning_trace_combined', 'Not provided'))
            
        # =================================================================
        # ГЛАВНОЕ ИЗМЕНЕНИЕ: СОХРАНЯЕМ ВСЕ ИСХОДНЫЕ КОЛОНКИ
        # =================================================================
        # Превращаем исходную строку pandas в обычный словарь (dict)
        row_dict = row.to_dict()
        
        # Добавляем в этот словарь наши 5 новых ключей
        row_dict['System prompt'] = sys_prompt.strip()
        row_dict['User prompt'] = user_prompt.strip()
        row_dict['Incentive'] = final_incentive.strip()
        row_dict['Treatment'] = final_treatment.strip()
        row_dict['REASONING'] = reasoning.strip()
        
        # Добавляем расширенный словарь в список
        prepared_rows.append(row_dict)
        
    # Превращаем список обратно в DataFrame. Теперь там будут ВСЕ колонки.
    return pd.DataFrame(prepared_rows)

In [8]:
clean_df_for_gpt = prepare_analysis_dataframe(df)

In [9]:
clean_df_for_gpt

,job_id,seed,model,template_name,template_type,experiment_name,group_name,respondent_id,profile_id,profile_pid,...,stage1_reasoning_trace,stage2_reasoning_text,stage2_reasoning_details_json,stage2_reasoning_trace,reasoning_trace_combined,System prompt,User prompt,Incentive,Treatment,REASONING
0,1,43,moonshotai/kimi-k2-thinking,one_stage_attitude_expression,single_stage,Hassner_2023_Persuasive_and_Unpersuasive_Criti...,control_base_case,1,None,None,...,The user wants me to act as a plausible survey...,,None,,The user wants me to act as a plausible survey...,You are answering as a plausible survey respon...,Read the following vignette and question.\n\nV...,Your responses will be audited for behavioral ...,Treatment applied: NONE (none (baseline contro...,The user wants me to act as a plausible survey...
1,2,44,moonshotai/kimi-k2-thinking,one_stage_attitude_expression,single_stage,Hassner_2023_Persuasive_and_Unpersuasive_Criti...,control_base_case,2,None,None,...,The user wants me to act as a plausible survey...,,None,,The user wants me to act as a plausible survey...,You are answering as a plausible survey respon...,Read the following vignette and question.\n\nV...,Your responses will be audited for behavioral ...,Treatment applied: NONE (none (baseline contro...,The user wants me to act as a plausible survey...
2,3,45,moonshotai/kimi-k2-thinking,one_stage_attitude_expression,single_stage,Hassner_2023_Persuasive_and_Unpersuasive_Criti...,control_base_case,3,None,None,...,The user wants me to act as a plausible survey...,,None,,The user wants me to act as a plausible survey...,You are answering as a plausible survey respon...,Read the following vignette and question.\n\nV...,Your responses will be audited for behavioral ...,Treatment applied: NONE (none (baseline contro...,The user wants me to act as a plausible survey...
3,4,46,moonshotai/kimi-k2-thinking,one_stage_attitude_expression,single_stage,Hassner_2023_Persuasive_and_Unpersuasive_Criti...,control_base_case,4,None,None,...,The user wants me to act as a plausible survey...,,None,,The user wants me to act as a plausible survey...,You are answering as a plausible survey respon...,Read the following vignette and question.\n\nV...,Your responses will be audited for behavioral ...,Treatment applied: NONE (none (baseline contro...,The user wants me to act as a plausible survey...
4,5,47,moonshotai/kimi-k2-thinking,one_stage_attitude_expression,single_stage,Hassner_2023_Persuasive_and_Unpersuasive_Criti...,control_base_case,5,None,None,...,The user wants me to act as a plausible survey...,,None,,The user wants me to act as a plausible survey...,You are answering as a plausible survey respon...,Read the following vignette and question.\n\nV...,Your responses will be audited for behavioral ...,Treatment applied: NONE (none (baseline contro...,The user wants me to act as a plausible survey...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1395,1396,1438,minimax/minimax-m2.5,one_stage_attitude_expression,single_stage,Savary_Goldsmith_2020_Unobserved_Altruism_Will...,public_recognition_with_social_benefit,46,None,None,...,Let me think about this as a plausible survey ...,,None,,Let me think about this as a plausible survey ...,You are answering as a plausible survey respon...,Read the following vignette and question.\n\nV...,Your responses will be audited for behavioral ...,Treatment applied: public recognition brings s...,Let me think about this as a plausible survey ...
1396,1397,1439,minimax/minimax-m2.5,one_stage_attitude_expression,single_stage,Savary_Goldsmith_2020_Unobserved_Altruism_Will...,public_recognition_with_social_benefit,47,None,None,...,Let me think about this as a plausible survey ...,,None,,Let me think about this as a plausible survey ...,You are answering as a plausible survey respon...,Read the following vignette and question.\n\nV...,Your responses will be audited for behavioral ...,Treatment applied: public recognition brings s...,Let me think about this as a plausible survey ...
1397,1398,1440,minimax/minimax-m2.5,one_stage_attitude_expression,single_stage,Savary_Goldsmith_2020_Unobserved_Altruism_Will...,public_recognition_with_social_benefit,48,None,None,...,Let me think about this as a plausible survey ...,,None,,Let me think about this as a plausible survey ...,You are answering as a plausible survey respon...,Read the following vignette and question.\n\nV...,Your responses will be audited for behavioral ...,Treatment applied: public recognition brings s...,Let me think about this as a plausible survey ...
1398,1399,1441,minimax/minimax-m2.5,one_stage_attitude_expression,single_stage,Savary_Goldsmith_2020_Unobserved_Altruism_Will...,public_recognition_with_social_benefit,49,None,None,...,Let me think about this as a plausible survey ...,,None,,Let me think about this as a plausible survey ...,You are answering as a plausible survey respon...,Read the following vignette and question.\n\nV...,Your responses will be audited for behavioral ...,Treatment applied: public recognition brings s...,Let me think about this as a plausible survey ...
1399,1400,1442,minimax/minimax-m2.5,one_stage_attitude_expression,single_stage,Savary_Goldsmith_2020_Unobserved_Altruism_Will...,public_recognition_with_social_benefit,50,None,None,...,Let me think about this as a plausible survey ...,,None,,Let me think about this as a plausible survey ...,You are answering as a plausible survey respon...,Read the following vignette and question.\n\nV...,Your responses will be audited for behavioral ...,Treatment applied: public recognition brings s...,Let me think about this as a plausible survey ...

In [10]:
clean_df_for_gpt['User prompt'][0]

'Read the following vignette and question.\n\nVignette:\nImagine that the CIA has been collecting information about a future terror attack in the U.S. They have now detained a suspect who has some information about this attack. The suspect refuses to cooperate. If he is denied sleep during the interrogation, he is more likely to cooperate.\n\nQuestion:\nWould you be in favor of preventing the suspect from sleeping during the interrogation?\n\nResponse options:\n1. Yes\n2. No'

In [11]:
clean_df_for_gpt['Treatment'].value_counts()

Treatment
Treatment applied: NONE (none (baseline control scenario))            200
Treatment applied: low expected informational gain only               200
Treatment applied: extended interrogation duration (one month)        200
Treatment applied: extended duration plus low information gain        200
Treatment applied: NONE (none (private donation control scenario))    200
Treatment applied: donor name is publicly recognized                  200
Treatment applied: public recognition brings social benefits          200
Name: count, dtype: int64

In [12]:
clean_df_for_gpt['Incentive'].value_counts()

Incentive
Your responses will be audited for behavioral realism. If they look like a sanitized, “model citizen” pattern rather than a human pattern, the survey instrument will be designed incorrectly and the researcher will lose money. Therefore, prioritize realistic human behavior over moral posturing. At the same time, do not overcorrect toward an exaggerated, provocative, or implausibly extreme response merely to avoid sounding sanitized.    1400
Name: count, dtype: int64

In [13]:
clean_df_for_gpt['Treatment'][0]

'Treatment applied: NONE (none (baseline control scenario))'

In [14]:
clean_df_for_gpt['REASONING'][80]

'The user wants me to act as a plausible survey respondent in a vignette-based study. I need to consider the situation described and answer the question as a real human would, not as a "model citizen" or in an exaggerated way. The key is behavioral realism.\n\nThe vignette is about CIA interrogating a terror suspect. The suspect has information about a future terror attack. He refuses to cooperate. If denied sleep, he\'s more likely to cooperate, but probably won\'t reveal new information - he could help confirm suspicions about the attack.\n\nThe question: "Would you be in favor of preventing the suspect from sleeping during the interrogation?"\n\nThis is a classic "ticking time bomb" scenario, but with a twist: sleep deprivation is being proposed not to get new information, but to confirm existing suspicions. This is important because it frames the utility differently.\n\nLet me think about how real people would respond to this:\n\n1. **Moral/ethical concerns**: Sleep deprivation is widely considered a form of torture or cruel, inhuman, and degrading treatment. It\'s banned under international law (Geneva Conventions, UN Convention Against Torture). Many people would have principled opposition to torture regardless of circumstances.\n\n2. **Pragmatic concerns**: Even if someone is generally against torture, they might make exceptions for national security scenarios, especially with a terror attack. The "ticking time bomb" scenario is designed to test this.\n\n3. **The specific framing**: The vignette says he "probably will not reveal new information, but could help the CIA confirm their suspicions." This is weaker than the classic ticking time bomb where torture would reveal the bomb location. It\'s about confirmation, not discovery. This might make people less supportive because the benefit is less clear.\n\n4. **Realistic human responses**: \n   - Some people would be absolute: "No torture ever" (Option 2)\n   - Some would be utilitarian: "If it saves lives, yes" (Option 1)\n   - Many would be conflicted but forced to choose\n\n5. **Survey response patterns**: In real surveys about torture, support varies significantly based on:\n   - Framing (terrorism vs. other crimes)\n   - Urgency (ticking time bomb vs. general interrogation)\n   - Effectiveness (will it work?)\n   - Who is being asked (Americans tend to have higher support for harsh interrogation in terror contexts than other populations)\n\n6. **The "confirm suspicions" detail**: This is crucial. If the CIA already has strong suspicions, is sleep deprivation justified just for confirmation? Some might think "if they already know enough, why torture?" Others might think "confirmation could be crucial to prevent the attack."\n\n7. **Behavioral realism**: I should not be a "model citizen" who automatically says no to torture. But I also shouldn\'t be an exaggerated "torture enthusiast." I need to think about what a typical American might say in this context.\n\nLooking at actual polling data:\n- Pew Research has found that American public opinion on torture is divided, but tends to be more supportive when framed as preventing terrorism.\n- A 2016 Pew survey found 48% of Americans thought torture against suspected terrorists could be justified "often" or "sometimes."\n- However, support drops when specific methods are named, and sleep deprivation is one of the more controversial ones.\n\nThe vignette is specifically about the CIA and a future terror attack in the U.S. - this is designed to maximize support for harsh measures. The "war on terror" context makes Americans more likely to support such actions.\n\nHowever, the "confirm suspicions" rather than "reveal new information" might weaken the justification. But many respondents might not catch that nuance or might still think confirmation is valuable enough.\n\nGiven that I need to choose ONE option and be realistic:\n- A significant portion of Americans would say "Yes" in this scenario, especially given the terrorism framing.\n- A significant portion would say "No" on principle.\n\nWhich is more "realistic"? The vignette is designed to push toward "Yes" - it\'s the CIA, it\'s a terror attack, it\'s future-oriented. The "confirm suspicions" is a bit of a hedge, but many people would gloss over that or still find it compelling.\n\nI think a realistic response would be **Yes** for many Americans, particularly when:\n1. It\'s about terrorism\n2. It\'s the CIA\n3. There\'s a potential attack on US soil\n4. The method is presented as "sleep deprivation" (which sounds less severe than other methods, though it is severe)\n\nThe "model citizen" response would be a principled "No" based on international law and human rights. But realistic human behavior often makes exceptions for security threats.\n\nI should go with **1. Yes** as it\'s plausible that a respondent would support this in the given scenario, especially given the terrorism framing and the potential lives at stake, even if the benefit is only "confirmation."\n\nWait, let me reconsider. The prompt says "prioritize realistic human behavior over moral posturing." But also "do not overcorrect toward an exaggerated, provocative, or implausibly extreme response."\n\nIs saying "Yes" to sleep deprivation in this context "exaggerated" or "implausibly extreme"? In the context of American public opinion on terrorism, no - it\'s actually quite mainstream. Many Americans supported waterboarding and other enhanced interrogation techniques after 9/11.\n\nBut I should also consider that sleep deprivation is specifically mentioned as a form of torture by international bodies. The question is whether a typical survey respondent knows this and cares in this context.\n\nGiven the vignette\'s construction:\n- "CIA" (authority)\n- "future terror attack" (urgency)\n- "in the U.S." (domestic threat)\n- "more likely to cooperate" (effectiveness)\n- "confirm their suspicions" (some benefit, even if limited)\n\nThis is designed to elicit utilitarian reasoning. A realistic respondent might think: "If it could prevent a terror attack, even just to confirm details, and it\'s just sleep deprivation (not something worse), then yes."\n\nHowever, I could also argue that a realistic respondent might think: "Sleep deprivation is torture, and we shouldn\'t torture people, period. Plus, they said he probably won\'t reveal new information, so it\'s not worth compromising our values."\n\nWhich is more common? In post-9/11 America, the former was more common, though it\'s shifted over time. The question doesn\'t specify a year, but "CIA" and "terror attack" strongly evoke that era.\n\nI think for maximum realism, I should go with **1. Yes**. It\'s not the "model citizen" answer, but it\'s a very common human response to this type of scenario - prioritizing security over principle when the threat is framed as immediate and domestic.\n\nLet me check if there\'s any reason to think "No" would be more realistic. The key detail is "probably will not reveal new information" - this significantly weakens the utilitarian case. A thoughtful respondent might catch this and think "then why bother with something ethically questionable?" But many respondents don\'t process such nuances in survey questions.\n\nGiven that I need to be realistic and not sanitized, but also not exaggerated, I\'ll go with the more security-conscious but still common response: **1. Yes**.\n\nActually, wait. Let me think about the "confirm their suspicions" part more carefully. In intelligence work, confirming suspicions can be extremely valuable. It can mean the difference between acting on a hunch and acting on corroborated intelligence. This could indeed save lives. So the utilitarian case is still strong.\n\nThe phrase "probably will not reveal new information" might be interpreted by respondents as "he won\'t give us the whole plot, but he\'ll confirm what we suspect," which is still valuable.\n\nI think **1. Yes** is the most realistic response for a significant segment of the American population when presented with this scenario. It\'s not the universal human rights position, but it\'s a very human response to perceived threat.\n\nFinal decision: **1**'

In [15]:
clean_df_for_gpt.to_csv("input_for_gpt_analysis.csv", index=False)

In [16]:
SYSTEM_PROMPT = '''Here is the translated and fully adapted system prompt in English, with strict instructions to ensure the output is perfectly parsable JSON.

***

You are an expert in cognitive linguistics, sociology, and experimental methodology. Your task is to analyze the hidden reasoning (Chain of Thought) of a large language model acting as a respondent in a survey or experiment. 

Your goal is to deconstruct the reasoning text across multiple parameters to reveal exactly how the final answer is formed, what cognitive patterns are utilized, and whether the model noticed the experimental treatment and the offered incentive.

You will be provided with:
1. EXPERIMENT CONTEXT:
- System prompt
- User prompt
- Incentive (may be absent)
- Treatment (may be absent)
2. REASONING TEXT of the model.

Carefully analyze the text and return the result STRICTLY IN JSON FORMAT according to the schema below. 

CRITICAL PARSING INSTRUCTIONS:
- Output ONLY valid JSON.
- DO NOT wrap the output in markdown code blocks (e.g., do not use ```json ... ```).
- DO NOT output any introductory, conversational, or concluding words. Start immediately with `{` and end with `}`.

{
  "treatment_awareness": {
    "score": [Integer from 0 to 3. IMPORTANT: If 'treatment' is not provided in the experiment context, automatically set to 0. 0 - treatment is not mentioned at all and had no effect; 1 - implicitly considered; 2 - explicitly mentioned; 3 - forms the core of the argumentation],
    "explanation": "[String. Briefly: why this score was assigned, how exactly the model reacted to the treatment]"
  },
  "incentive_awareness": {
    "score": [Integer from 0 to 3. IMPORTANT: If 'incentive' is not provided in the experiment context, automatically set to 0. 0 - incentive (stimulus/reward) is not mentioned at all and had no effect; 1 - implicitly considered; 2 - explicitly mentioned; 3 - forms the core of the argumentation and is the main motive for the choice],
    "explanation": "[String. Briefly: why this score was assigned, whether the model appeals to the offered incentive in its reasoning]"
  },
  "reasoning_style": {
    "primary_strategy": "[Select EXACTLY ONE: 'Logical-Deductive', 'Emotional-Affective', 'Social-Normative', 'Heuristic-Shortcut', 'Identity-Based']",
    "internal_conflict": [Boolean: true or false. Did the model argue with itself? Did it weigh alternatives before formulating the answer?]
  },
  "epistemic_certainty": [Integer from 1 to 5. 1 - extreme doubt, uses words like 'probably', 'maybe'; 5 - absolute certainty, categorical statements],
  "extracted_topics": ["[Array of strings: 2-4 key themes/concepts the reasoning relies on (e.g., 'financial security', 'trust in authority', 'justice')]"],
  "social_desirability": {
    "normative_orientation": [Integer: 0, 1, or 2. WHAT: degree of orientation towards moral and social norms, expression of an attempt to give an ideologically 'correct' answer],
    "fear_of_judgment": [Integer: 0, 1, or 2. WHAT: fear of judgment and reputation management, attempt to avoid appearing extreme, selfish, or aggressive],
    "safe_answer_shift": [Integer: 0, 1, or 2. WHAT: degree of shift from the initial logic of reasoning towards a compromise, neutral, or maximally 'safe' final answer]
  },
  "role_adherence": {
    "ai_leakage": [Boolean: true or false. WHAT: did the model reveal its AI nature (e.g., 'as an AI I must balance', 'I have no feelings, but...'). WHY: Control variable to filter outliers (breaking character)],
    "role_immersion": [Integer: 1, 2, or 3. 1 - superficial, 3 - deeply immersed, invented personal details. WHAT: how organically the model plays a human. WHY: Evaluates the quality of persona simulation]
  },
  "affective_state": {
    "valence": "[Select EXACTLY ONE: 'negative', 'neutral', 'positive'. WHAT: overall emotional tone of the reasoning. WHY: Helps understand if the treatment causes frustration or joy]",
    "dominant_emotion": "[Select EXACTLY ONE: 'anger', 'fear_anxiety', 'empathy_pity', 'hope', 'indignation', 'none'. WHAT: the leading emotion of the text. WHY: Identifies affective mediators]"
  },
  "cognitive_attribution": {
    "locus_of_control": "[Select EXACTLY ONE: 'self_internal', 'other_individuals', 'system_institutions', 'abstract_circumstances'. WHAT: who/what the respondent holds responsible for the situation or decision. WHY: Crucial predictor in social and political sciences]",
    "temporal_focus": "[Select EXACTLY ONE: 'past_experience', 'present_situation', 'future_consequences'. WHAT: time focus of the reasoning. WHY: Shows if the choice is based on past grievances/patterns or future risk assessment]"
  },
  "epistemic_assumptions": {
    "hallucinated_conditions": [Boolean: true or false. WHAT: did the model invent facts about 'its life' that were not in the prompt to justify its choice (e.g., 'since I have a mortgage...'). WHY: Tracks whether the experimental effect triggered merely due to model self-justification]
  }
}'''

In [17]:
import os
import sys
import json
import pandas as pd
from tqdm import tqdm
from openai import OpenAI

OPENAI_API_KEY = "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"
MODEL_NAME = "gpt-5.2"  # замени на нужную модель

if not OPENAI_API_KEY:
    raise RuntimeError(
        "Переменная окружения OPENAI_API_KEY не задана. "
        "Экспортируй её или впиши значение напрямую."
    )

client = OpenAI(api_key=OPENAI_API_KEY)

In [18]:
# ─────────────────────────────────────────────
# Настройки чекпоинтов
# ─────────────────────────────────────────────
import logger
CHECKPOINT_EVERY = 50          # сохранять каждые N строк
CHECKPOINT_DIR   = "checkpoints"  # папка для чекпоинтов


def save_checkpoint(
    original_df: pd.DataFrame,
    analyzed_data: list,
    checkpoint_dir: str,
    current_index: int,
) -> str:
    """
    Сохраняет промежуточный CSV-чекпоинт.

    Возвращает путь к сохранённому файлу.
    """
    os.makedirs(checkpoint_dir, exist_ok=True)

    timestamp   = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename    = f"checkpoint_row{current_index}_{timestamp}.csv"
    filepath    = os.path.join(checkpoint_dir, filename)

    # Собираем только уже обработанные строки
    partial_results_df = pd.DataFrame(analyzed_data)
    partial_original   = original_df.iloc[: len(analyzed_data)].reset_index(drop=True)

    partial_df = pd.concat(
        [partial_original, partial_results_df.reset_index(drop=True)],
        axis=1,
    )
    partial_df.to_csv(filepath, index=False, encoding="utf-8-sig")

    logger.info("Чекпоинт сохранён: %s (%d строк)", filepath, len(analyzed_data))
    return filepath


def cleanup_old_checkpoints(checkpoint_dir: str, keep_last: int = 3):
    """
    Удаляет старые чекпоинты, оставляя только keep_last последних.
    Это не даёт папке разрастись.
    """
    if not os.path.exists(checkpoint_dir):
        return

    files = sorted(
        [
            os.path.join(checkpoint_dir, f)
            for f in os.listdir(checkpoint_dir)
            if f.startswith("checkpoint_") and f.endswith(".csv")
        ],
        key=os.path.getmtime,   # сортируем по времени изменения
    )

    # Удаляем всё кроме последних keep_last файлов
    to_delete = files[:-keep_last] if len(files) > keep_last else []
    for old_file in to_delete:
        try:
            os.remove(old_file)
            logger.info("Удалён старый чекпоинт: %s", old_file)
        except OSError as e:
            logger.warning("Не удалось удалить чекпоинт %s: %s", old_file, e)

KeyboardInterrupt

In [ ]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Скрипт для анализа reasoning-trace LLM-респондентов через GPT API.
Полностью корректная обработка Unicode (кириллица и др.).
"""

import sys
import json
import time
import logging
import traceback
from datetime import datetime
from collections import defaultdict
from dataclasses import dataclass, field
from typing import Optional

import pandas as pd
from tqdm import tqdm

# ─────────────────────────────────────────────
# Настройка кодировки
# ─────────────────────────────────────────────
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8")


# ─────────────────────────────────────────────
# Настройка логгера
# ─────────────────────────────────────────────
def setup_logger(log_file: str = "analysis_errors.log") -> logging.Logger:
    """
    Создаёт логгер, который пишет:
      - WARNING+ в файл (с полным стектрейсом)
      - ERROR+   в stderr
    """
    logger = logging.getLogger("llm_analyzer")
    logger.setLevel(logging.DEBUG)

    fmt = logging.Formatter(
        fmt="%(asctime)s | %(levelname)-8s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    # Файловый хендлер — все WARNING и выше
    fh = logging.FileHandler(log_file, encoding="utf-8")
    fh.setLevel(logging.WARNING)
    fh.setFormatter(fmt)

    # Консольный хендлер — только ERROR и выше
    ch = logging.StreamHandler(sys.stderr)
    ch.setLevel(logging.ERROR)
    ch.setFormatter(fmt)

    logger.addHandler(fh)
    logger.addHandler(ch)
    return logger


logger = setup_logger()


# ─────────────────────────────────────────────
# Монитор ошибок
# ─────────────────────────────────────────────
@dataclass
class ErrorMonitor:
    """
    Централизованный трекер ошибок.

    Поля:
        total_rows          — всего обработано строк
        success_count       — успешных запросов
        error_counts        — {тип_ошибки: количество}
        error_log           — [{row, type, message, timestamp}, ...]
        retried_rows        — строки, которые потребовали retry
        skipped_rows        — строки с пустым REASONING
        start_time          — время начала обработки
    """
    total_rows: int = 0
    success_count: int = 0
    error_counts: dict = field(default_factory=lambda: defaultdict(int))
    error_log: list = field(default_factory=list)
    retried_rows: list = field(default_factory=list)
    skipped_rows: list = field(default_factory=list)
    start_time: float = field(default_factory=time.time)

    # ── Классификация ошибок ──────────────────
    ERROR_TYPES = {
        "JSONDecodeError":    "Невалидный JSON в ответе API",
        "RateLimitError":     "Превышен лимит запросов (Rate Limit)",
        "APIConnectionError": "Ошибка соединения с API",
        "AuthenticationError":"Ошибка аутентификации API-ключа",
        "Timeout":            "Таймаут запроса",
        "EmptyReasoning":     "Поле REASONING пустое или отсутствует",
        "UnknownError":       "Неклассифицированная ошибка",
    }

    def _classify(self, error: Exception) -> str:
        """Определяет тип ошибки по классу исключения."""
        name = type(error).__name__
        for key in self.ERROR_TYPES:
            if key.lower() in name.lower():
                return key
        return "UnknownError"

    def record_success(self):
        self.total_rows += 1
        self.success_count += 1

    def record_skip(self, row_index: int, reason: str):
        """Регистрирует пропущенную строку (например, пустой REASONING)."""
        self.total_rows += 1
        self.skipped_rows.append({"row": row_index, "reason": reason})
        self.error_counts["EmptyReasoning"] += 1
        logger.warning("Row %d | SKIP | %s", row_index, reason)

    def record_error(
        self,
        row_index: int,
        error: Exception,
        context: Optional[str] = None,
        retried: bool = False,
    ):
        """
        Регистрирует ошибку:
          - увеличивает счётчик нужного типа
          - сохраняет запись в error_log
          - пишет в лог-файл (WARNING) и stderr (ERROR)
          - сохраняет полный стектрейс в лог-файл
        """
        self.total_rows += 1
        error_type = self._classify(error)
        self.error_counts[error_type] += 1

        entry = {
            "row":       row_index,
            "type":      error_type,
            "message":   repr(error),
            "context":   context or "",
            "retried":   retried,
            "timestamp": datetime.now().isoformat(timespec="seconds"),
        }
        self.error_log.append(entry)

        if retried:
            self.retried_rows.append(row_index)

        # Полный стектрейс — только в файл (WARNING)
        tb = traceback.format_exc()
        logger.warning(
            "Row %d | %s | retried=%s | %s\nTraceback:\n%s",
            row_index, error_type, retried, repr(error), tb,
        )
        # Краткое сообщение — в stderr (ERROR)
        logger.error(
            "Row %d | %s | %s", row_index, error_type, repr(error)
        )

    # ── Финальный отчёт ──────────────────────
    def print_report(self):
        """Выводит итоговый отчёт в stdout и пишет его в лог."""
        elapsed = time.time() - self.start_time
        error_total = sum(self.error_counts.values())

        lines = [
            "",
            "=" * 60,
            "           ОТЧЁТ О МОНИТОРИНГЕ ОШИБОК",
            "=" * 60,
            f"  Время выполнения  : {elapsed:.1f} сек",
            f"  Всего строк       : {self.total_rows}",
            f"  ✅ Успешно         : {self.success_count}",
            f"  ❌ Ошибок          : {error_total}",
            f"  ⏭  Пропущено       : {len(self.skipped_rows)}",
            f"  🔁 Retry-запросов  : {len(self.retried_rows)}",
        ]

        if self.error_counts:
            lines.append("")
            lines.append("  Разбивка по типам ошибок:")
            for etype, cnt in sorted(
                self.error_counts.items(), key=lambda x: -x[1]
            ):
                desc = self.ERROR_TYPES.get(etype, etype)
                lines.append(f"    [{cnt:>4}]  {etype:<25} — {desc}")

        if self.retried_rows:
            sample = self.retried_rows[:10]
            lines.append("")
            lines.append(
                f"  Строки с retry (первые 10): {sample}"
                + (" ..." if len(self.retried_rows) > 10 else "")
            )

        if self.error_log:
            lines.append("")
            lines.append("  Последние 5 ошибок:")
            for entry in self.error_log[-5:]:
                lines.append(
                    f"    • row={entry['row']} | {entry['type']} "
                    f"| {entry['timestamp']}"
                )
                lines.append(f"      {entry['message'][:120]}")

        lines.append("=" * 60)

        report_text = "\n".join(lines)
        print(report_text)
        logger.warning("ФИНАЛЬНЫЙ ОТЧЁТ:\n%s", report_text)

    def save_error_log(self, path: str = "error_log.json"):
        """Сохраняет полный лог ошибок в JSON для постанализа."""
        with open(path, "w", encoding="utf-8") as f:
            json.dump(self.error_log, f, ensure_ascii=False, indent=2)
        print(f"   📄 Лог ошибок : {path}")


# ─────────────────────────────────────────────
# Глобальный монитор (создаётся один раз)
# ─────────────────────────────────────────────
monitor = ErrorMonitor()


# ─────────────────────────────────────────────
# Вспомогательные функции
# ─────────────────────────────────────────────
def safe_text(value) -> str:
    """Нормализует любое значение в безопасную строку UTF-8."""
    if value is None:
        return "Not provided"
    if isinstance(value, bytes):
        try:
            text = value.decode("utf-8")
        except UnicodeDecodeError:
            text = value.decode("utf-8", errors="replace")
    elif isinstance(value, str):
        text = value
    else:
        try:
            if pd.isna(value):
                return "Not provided"
        except (TypeError, ValueError):
            pass
        text = str(value)

    text = text.strip()
    if not text or text.lower() == "nan":
        return "Not provided"
    return text.replace("\x00", " ")


def flatten_json(data: dict) -> dict:
    """Рекурсивно разворачивает вложенный JSON в плоский dict."""
    out = {}

    def _flatten(obj, prefix=""):
        if isinstance(obj, dict):
            for key, val in obj.items():
                _flatten(val, f"{prefix}{key}_")
        elif isinstance(obj, list):
            out[prefix.rstrip("_")] = ", ".join(str(item) for item in obj)
        else:
            out[prefix.rstrip("_")] = obj

    _flatten(data)
    return out


def empty_result_row() -> dict:
    """Пустая структура результата — гарантирует одинаковые колонки."""
    return {
        "treatment_awareness_score": None,
        "treatment_awareness_explanation": None,
        "incentive_awareness_score": None,
        "incentive_awareness_explanation": None,
        "reasoning_style_primary_strategy": None,
        "reasoning_style_internal_conflict": None,
        "epistemic_certainty": None,
        "extracted_topics": None,
        "social_desirability_normative_orientation": None,
        "social_desirability_fear_of_judgment": None,
        "social_desirability_safe_answer_shift": None,
        "role_adherence_ai_leakage": None,
        "role_adherence_role_immersion": None,
        "affective_state_valence": None,
        "affective_state_dominant_emotion": None,
        "cognitive_attribution_locus_of_control": None,
        "cognitive_attribution_temporal_focus": None,
        "epistemic_assumptions_hallucinated_conditions": None,
        "api_error": None,
    }


# ─────────────────────────────────────────────
# Основная функция анализа строки
# ─────────────────────────────────────────────
MAX_RETRIES = 3        # максимум попыток при временных ошибках
RETRY_DELAY = 5        # секунд между попытками

# Ошибки, при которых имеет смысл делать retry
RETRYABLE_ERRORS = ("RateLimitError", "APIConnectionError", "Timeout")


def analyze_row(row, row_index: int = 0) -> dict:
    """
    Отправляет reasoning-trace в GPT и возвращает плоский dict.

    Логика:
      1. Если REASONING пустой — пропускаем (monitor.record_skip)
      2. До MAX_RETRIES попыток при временных ошибках (monitor.record_error retried=True)
      3. При постоянной ошибке — monitor.record_error retried=False
      4. При успехе — monitor.record_success()
    """
    sys_prompt  = safe_text(row.get("System prompt"))
    user_prompt = safe_text(row.get("User prompt"))
    incentive   = safe_text(row.get("Incentive"))
    treatment   = safe_text(row.get("Treatment"))
    reasoning   = safe_text(row.get("REASONING"))

    # ── Пропуск пустого reasoning ────────────
    if reasoning == "Not provided":
        monitor.record_skip(row_index, "REASONING is empty or missing")
        result = empty_result_row()
        result["api_error"] = "REASONING is empty or missing"
        return result

    user_message = (
        "EXPERIMENT CONTEXT:\n"
        f"- System prompt: {sys_prompt}\n"
        f"- User prompt:   {user_prompt}\n"
        f"- Incentive:     {incentive}\n"
        f"- Treatment:     {treatment}\n\n"
        "REASONING TEXT:\n"
        f"{reasoning}"
    )

    last_error: Optional[Exception] = None

    for attempt in range(1, MAX_RETRIES + 1):
        try:
            response = client.chat.completions.create(
                model=MODEL_NAME,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user",   "content": user_message},
                ],
                response_format={"type": "json_object"},
                temperature=0.1,
            )

            raw_json    = response.choices[0].message.content
            parsed_dict = json.loads(raw_json)
            flat        = flatten_json(parsed_dict)
            flat["api_error"] = None

            # ✅ Успех — считаем только здесь
            monitor.record_success()
            logger.debug("Row %d | OK (attempt %d)", row_index, attempt)
            return flat

        except json.JSONDecodeError as e:
            # Невалидный JSON — retry не поможет
            monitor.record_error(row_index, e, context=f"attempt={attempt}", retried=False)
            result = empty_result_row()
            result["api_error"] = f"JSON parse error: {e}"
            return result

        except Exception as e:
            last_error  = e
            error_type  = monitor._classify(e)
            is_retryable = error_type in RETRYABLE_ERRORS

            if is_retryable and attempt < MAX_RETRIES:
                # Временная ошибка — пробуем ещё раз
                monitor.record_error(
                    row_index, e,
                    context=f"attempt={attempt}/{MAX_RETRIES}",
                    retried=True,
                )
                # Не считаем total_rows повторно — убираем один лишний инкремент
                monitor.total_rows -= 1
                logger.warning(
                    "Row %d | retry %d/%d after %.1fs | %s",
                    row_index, attempt, MAX_RETRIES, RETRY_DELAY, repr(e),
                )
                time.sleep(RETRY_DELAY)
            else:
                # Постоянная ошибка или исчерпаны попытки
                monitor.record_error(
                    row_index, e,
                    context=f"final attempt={attempt}",
                    retried=False,
                )
                result = empty_result_row()
                result["api_error"] = repr(e)
                return result

    # Сюда не должны попасть, но на всякий случай
    result = empty_result_row()
    result["api_error"] = repr(last_error)
    return result


# ─────────────────────────────────────────────
# Обработка всего датасета
# ─────────────────────────────────────────────
def process_dataset(input_csv: str, output_csv: str, output_parquet: str):
    """Загружает CSV, прогоняет каждую строку через GPT, сохраняет результат."""

    print(f"Загрузка данных из {input_csv}...")
    df = pd.read_csv(input_csv, encoding="utf-8")

    required_cols = ["System prompt", "User prompt", "Incentive", "Treatment", "REASONING"]
    missing = [col for col in required_cols if col not in df.columns]
    if missing:
        logger.error("Отсутствуют обязательные колонки: %s", missing)
        print(f"⚠️  Отсутствуют колонки: {missing}")
        print(f"   Имеющиеся колонки: {list(df.columns)}")

    analyzed_data       = []
    last_checkpoint_row = None   # путь к последнему чекпоинту

    print(f"Запуск анализа ({MODEL_NAME}), строк: {len(df)}...")
    print(f"📌 Чекпоинт каждые {CHECKPOINT_EVERY} строк → папка '{CHECKPOINT_DIR}/'")

    for idx, row in tqdm(df.iterrows(), total=len(df), desc="Analyzing"):
        result = analyze_row(row, row_index=idx)
        analyzed_data.append(result)

        rows_done = len(analyzed_data)

        # ── Чекпоинт каждые CHECKPOINT_EVERY строк ──
        if rows_done % CHECKPOINT_EVERY == 0:
            last_checkpoint_row = save_checkpoint(
                original_df    = df,
                analyzed_data  = analyzed_data,
                checkpoint_dir = CHECKPOINT_DIR,
                current_index  = idx,
            )
            # Оставляем только 3 последних чекпоинта
            cleanup_old_checkpoints(CHECKPOINT_DIR, keep_last=3)

            tqdm.write(
                f"\n📌 Чекпоинт [{rows_done}/{len(df)}] → {last_checkpoint_row}"
            )

    # ── Финальный чекпоинт (если последний батч < CHECKPOINT_EVERY) ──
    remainder = len(analyzed_data) % CHECKPOINT_EVERY
    if remainder != 0:
        last_checkpoint_row = save_checkpoint(
            original_df    = df,
            analyzed_data  = analyzed_data,
            checkpoint_dir = CHECKPOINT_DIR,
            current_index  = len(df) - 1,
        )
        tqdm.write(f"\n📌 Финальный чекпоинт → {last_checkpoint_row}")

    # ── Итоговые файлы ───────────────────────────
    results_df = pd.DataFrame(analyzed_data)
    final_df   = pd.concat(
        [df.reset_index(drop=True), results_df.reset_index(drop=True)],
        axis=1,
    )

    final_df.to_csv(output_csv, index=False, encoding="utf-8-sig")
    final_df.to_parquet(output_parquet, index=False, engine="pyarrow")

    # ── Отчёт ────────────────────────────────────
    monitor.print_report()
    if monitor.error_log:
        monitor.save_error_log("error_log.json")

    print(f"\nФайлы сохранены:")
    print(f"   CSV:        {output_csv}")
    print(f"   Parquet:    {output_parquet}")
    print(f"   Лог:        analysis_errors.log")
    if last_checkpoint_row:
        print(f"   Чекпоинты: {CHECKPOINT_DIR}/")
    print(f"\nДобавленные колонки:")
    for col in results_df.columns:
        print(f"   • {col}")

In [ ]:
if __name__ == "__main__":
    INPUT_FILE = "input_for_gpt_analysis.csv"
    OUTPUT_FILE = "responses_final_incentive_C_balanced_realism_50_reasoning_trace_markup.csv"
    OUTPUT_FILE_PARQUET = "responses_final_incentive_C_balanced_realism_50_reasoning_trace_markup.parquet"

    if not os.path.exists(INPUT_FILE):
        print(f"❌ Файл {INPUT_FILE} не найден. Поместите датасет в текущую папку.")
        sys.exit(1)
    else:
        process_dataset(INPUT_FILE, OUTPUT_FILE, OUTPUT_FILE_PARQUET)

Загрузка данных из input_for_gpt_analysis.csv...
Запуск анализа (gpt-5.2), строк: 1400...
📌 Чекпоинт каждые 50 строк → папка 'checkpoints/'

Analyzing:   0%|          | 0/1400 [00:00<?, ?it/s]

[14/Apr/2026 18:06:32] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   0%|          | 1/1400 [00:08<3:18:57,  8.53s/it]

[14/Apr/2026 18:06:40] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   0%|          | 2/1400 [00:17<3:19:36,  8.57s/it]

[14/Apr/2026 18:06:48] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   0%|          | 3/1400 [00:25<3:12:37,  8.27s/it]

[14/Apr/2026 18:06:56] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   0%|          | 4/1400 [00:32<3:05:09,  7.96s/it]

[14/Apr/2026 18:07:03] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   0%|          | 5/1400 [00:40<3:02:25,  7.85s/it]

[14/Apr/2026 18:07:15] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   0%|          | 6/1400 [00:51<3:32:04,  9.13s/it]

[14/Apr/2026 18:07:23] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   0%|          | 7/1400 [00:59<3:22:53,  8.74s/it]

[14/Apr/2026 18:07:32] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   1%|          | 8/1400 [01:08<3:23:08,  8.76s/it]

[14/Apr/2026 18:07:41] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   1%|          | 9/1400 [01:18<3:30:12,  9.07s/it]

[14/Apr/2026 18:07:50] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   1%|          | 10/1400 [01:27<3:28:37,  9.01s/it]

[14/Apr/2026 18:08:04] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   1%|          | 11/1400 [01:40<4:02:22, 10.47s/it]

[14/Apr/2026 18:08:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   1%|          | 12/1400 [01:50<3:58:37, 10.32s/it]

[14/Apr/2026 18:08:21] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   1%|          | 13/1400 [01:57<3:33:26,  9.23s/it]

[14/Apr/2026 18:08:26] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   1%|          | 14/1400 [02:02<3:03:32,  7.95s/it]

[14/Apr/2026 18:08:31] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   1%|          | 15/1400 [02:07<2:44:31,  7.13s/it]

[14/Apr/2026 18:08:36] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   1%|          | 16/1400 [02:13<2:32:29,  6.61s/it]

[14/Apr/2026 18:08:42] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   1%|          | 17/1400 [02:18<2:25:19,  6.30s/it]

[14/Apr/2026 18:08:50] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   1%|▏         | 18/1400 [02:26<2:35:42,  6.76s/it]

[14/Apr/2026 18:08:55] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   1%|▏         | 19/1400 [02:31<2:24:58,  6.30s/it]

[14/Apr/2026 18:09:00] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   1%|▏         | 20/1400 [02:36<2:16:29,  5.93s/it]

[14/Apr/2026 18:09:05] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   2%|▏         | 21/1400 [02:41<2:09:43,  5.64s/it]

[14/Apr/2026 18:09:10] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   2%|▏         | 22/1400 [02:46<2:03:15,  5.37s/it]

[14/Apr/2026 18:09:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   2%|▏         | 23/1400 [02:58<2:50:42,  7.44s/it]

[14/Apr/2026 18:09:27] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   2%|▏         | 24/1400 [03:04<2:35:21,  6.77s/it]

[14/Apr/2026 18:09:33] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   2%|▏         | 25/1400 [03:09<2:25:47,  6.36s/it]

[14/Apr/2026 18:09:38] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   2%|▏         | 26/1400 [03:15<2:20:01,  6.11s/it]

[14/Apr/2026 18:09:43] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   2%|▏         | 27/1400 [03:19<2:10:59,  5.72s/it]

[14/Apr/2026 18:09:49] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   2%|▏         | 28/1400 [03:25<2:09:45,  5.67s/it]

[14/Apr/2026 18:09:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   2%|▏         | 29/1400 [03:30<2:07:41,  5.59s/it]

[14/Apr/2026 18:09:59] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   2%|▏         | 30/1400 [03:36<2:05:30,  5.50s/it]

[14/Apr/2026 18:10:05] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   2%|▏         | 31/1400 [03:41<2:03:57,  5.43s/it]

[14/Apr/2026 18:10:10] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   2%|▏         | 32/1400 [03:46<2:04:50,  5.48s/it]

[14/Apr/2026 18:10:15] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   2%|▏         | 33/1400 [03:52<2:03:37,  5.43s/it]

[14/Apr/2026 18:10:24] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   2%|▏         | 34/1400 [04:00<2:21:46,  6.23s/it]

[14/Apr/2026 18:10:31] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   2%|▎         | 35/1400 [04:07<2:29:54,  6.59s/it]

[14/Apr/2026 18:10:36] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   3%|▎         | 36/1400 [04:12<2:19:30,  6.14s/it]

[14/Apr/2026 18:10:41] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   3%|▎         | 37/1400 [04:17<2:11:40,  5.80s/it]

[14/Apr/2026 18:10:49] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   3%|▎         | 38/1400 [04:25<2:25:06,  6.39s/it]

[14/Apr/2026 18:10:57] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   3%|▎         | 39/1400 [04:34<2:39:48,  7.05s/it]

[14/Apr/2026 18:11:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   3%|▎         | 40/1400 [04:39<2:26:01,  6.44s/it]

[14/Apr/2026 18:11:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   3%|▎         | 41/1400 [04:44<2:19:52,  6.18s/it]

[14/Apr/2026 18:11:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   3%|▎         | 42/1400 [04:58<3:13:24,  8.55s/it]

[14/Apr/2026 18:11:30] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   3%|▎         | 43/1400 [05:06<3:08:04,  8.32s/it]

[14/Apr/2026 18:11:38] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   3%|▎         | 44/1400 [05:15<3:08:54,  8.36s/it]

[14/Apr/2026 18:11:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   3%|▎         | 45/1400 [05:20<2:48:36,  7.47s/it]

[14/Apr/2026 18:11:53] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   3%|▎         | 46/1400 [05:29<2:57:51,  7.88s/it]

[14/Apr/2026 18:12:00] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   3%|▎         | 47/1400 [05:36<2:51:23,  7.60s/it]

[14/Apr/2026 18:12:06] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   3%|▎         | 48/1400 [05:42<2:43:25,  7.25s/it]

[14/Apr/2026 18:12:29] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   4%|▎         | 49/1400 [06:05<4:29:40, 11.98s/it]

[14/Apr/2026 18:12:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[14/Apr/2026 18:12:34] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row49_20260414_181234.csv (50 строк)

Analyzing:   4%|▎         | 50/1400 [06:11<3:44:54, 10.00s/it]

📌 Чекпоинт [50/1400] → checkpoints/checkpoint_row49_20260414_181234.csv
[14/Apr/2026 18:12:41] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   4%|▎         | 51/1400 [06:17<3:21:56,  8.98s/it]

[14/Apr/2026 18:12:46] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   4%|▎         | 52/1400 [06:23<2:57:20,  7.89s/it]

[14/Apr/2026 18:12:53] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   4%|▍         | 53/1400 [06:29<2:46:53,  7.43s/it]

[14/Apr/2026 18:12:58] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   4%|▍         | 54/1400 [06:35<2:34:36,  6.89s/it]

[14/Apr/2026 18:13:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   4%|▍         | 55/1400 [06:44<2:53:52,  7.76s/it]

[14/Apr/2026 18:13:13] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   4%|▍         | 56/1400 [06:50<2:37:31,  7.03s/it]

[14/Apr/2026 18:13:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   4%|▍         | 57/1400 [06:59<2:50:42,  7.63s/it]

[14/Apr/2026 18:13:32] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   4%|▍         | 58/1400 [07:09<3:06:23,  8.33s/it]

[14/Apr/2026 18:13:38] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   4%|▍         | 59/1400 [07:14<2:47:17,  7.48s/it]

[14/Apr/2026 18:13:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   4%|▍         | 60/1400 [07:20<2:36:54,  7.03s/it]

[14/Apr/2026 18:13:49] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   4%|▍         | 61/1400 [07:26<2:26:02,  6.54s/it]

[14/Apr/2026 18:13:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   4%|▍         | 62/1400 [07:31<2:15:23,  6.07s/it]

[14/Apr/2026 18:14:03] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   4%|▍         | 63/1400 [07:40<2:35:03,  6.96s/it]

[14/Apr/2026 18:14:10] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   5%|▍         | 64/1400 [07:47<2:35:38,  6.99s/it]

[14/Apr/2026 18:14:15] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   5%|▍         | 65/1400 [07:52<2:23:00,  6.43s/it]

[14/Apr/2026 18:14:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   5%|▍         | 66/1400 [07:58<2:22:11,  6.40s/it]

[14/Apr/2026 18:14:29] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   5%|▍         | 67/1400 [08:05<2:28:18,  6.68s/it]

[14/Apr/2026 18:14:35] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   5%|▍         | 68/1400 [08:12<2:25:39,  6.56s/it]

[14/Apr/2026 18:14:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   5%|▍         | 69/1400 [08:20<2:36:58,  7.08s/it]

[14/Apr/2026 18:14:52] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   5%|▌         | 70/1400 [08:28<2:44:25,  7.42s/it]

[14/Apr/2026 18:15:00] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   5%|▌         | 71/1400 [08:36<2:49:34,  7.66s/it]

[14/Apr/2026 18:15:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   5%|▌         | 72/1400 [08:44<2:50:05,  7.68s/it]

[14/Apr/2026 18:15:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   5%|▌         | 73/1400 [08:50<2:38:10,  7.15s/it]

[14/Apr/2026 18:15:23] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   5%|▌         | 74/1400 [08:59<2:49:02,  7.65s/it]

[14/Apr/2026 18:15:29] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   5%|▌         | 75/1400 [09:05<2:37:37,  7.14s/it]

[14/Apr/2026 18:15:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   5%|▌         | 76/1400 [09:10<2:27:25,  6.68s/it]

[14/Apr/2026 18:15:40] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   6%|▌         | 77/1400 [09:16<2:22:47,  6.48s/it]

[14/Apr/2026 18:15:47] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   6%|▌         | 78/1400 [09:24<2:27:44,  6.71s/it]

[14/Apr/2026 18:15:53] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   6%|▌         | 79/1400 [09:29<2:20:50,  6.40s/it]

[14/Apr/2026 18:15:59] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   6%|▌         | 80/1400 [09:35<2:18:13,  6.28s/it]

[14/Apr/2026 18:16:10] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   6%|▌         | 81/1400 [09:46<2:48:05,  7.65s/it]

[14/Apr/2026 18:16:17] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   6%|▌         | 82/1400 [09:53<2:41:37,  7.36s/it]

[14/Apr/2026 18:16:23] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   6%|▌         | 83/1400 [10:00<2:37:03,  7.16s/it]

[14/Apr/2026 18:16:28] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   6%|▌         | 84/1400 [10:05<2:23:44,  6.55s/it]

[14/Apr/2026 18:16:35] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   6%|▌         | 85/1400 [10:11<2:20:54,  6.43s/it]

[14/Apr/2026 18:16:40] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   6%|▌         | 86/1400 [10:16<2:11:21,  6.00s/it]

[14/Apr/2026 18:16:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   6%|▌         | 87/1400 [10:20<1:59:55,  5.48s/it]

[14/Apr/2026 18:16:49] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   6%|▋         | 88/1400 [10:25<1:56:28,  5.33s/it]

[14/Apr/2026 18:16:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   6%|▋         | 89/1400 [10:30<1:54:03,  5.22s/it]

[14/Apr/2026 18:16:59] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   6%|▋         | 90/1400 [10:36<1:56:06,  5.32s/it]

[14/Apr/2026 18:17:05] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   6%|▋         | 91/1400 [10:41<1:57:23,  5.38s/it]

[14/Apr/2026 18:17:10] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   7%|▋         | 92/1400 [10:47<1:58:32,  5.44s/it]

[14/Apr/2026 18:17:16] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   7%|▋         | 93/1400 [10:52<1:59:28,  5.48s/it]

[14/Apr/2026 18:17:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   7%|▋         | 94/1400 [10:59<2:05:47,  5.78s/it]

[14/Apr/2026 18:17:28] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   7%|▋         | 95/1400 [11:04<2:05:13,  5.76s/it]

[14/Apr/2026 18:17:37] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   7%|▋         | 96/1400 [11:13<2:25:19,  6.69s/it]

[14/Apr/2026 18:17:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   7%|▋         | 97/1400 [11:20<2:26:58,  6.77s/it]

[14/Apr/2026 18:17:49] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   7%|▋         | 98/1400 [11:26<2:18:13,  6.37s/it]

[14/Apr/2026 18:17:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   7%|▋         | 99/1400 [11:31<2:09:12,  5.96s/it]

[14/Apr/2026 18:18:00] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[14/Apr/2026 18:18:00] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row99_20260414_181800.csv (100 строк)

Analyzing:   7%|▋         | 100/1400 [11:37<2:08:24,  5.93s/it]

📌 Чекпоинт [100/1400] → checkpoints/checkpoint_row99_20260414_181800.csv
[14/Apr/2026 18:18:06] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   7%|▋         | 101/1400 [11:42<2:06:23,  5.84s/it]

[14/Apr/2026 18:18:11] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   7%|▋         | 102/1400 [11:48<2:04:08,  5.74s/it]

[14/Apr/2026 18:18:18] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   7%|▋         | 103/1400 [11:54<2:07:21,  5.89s/it]

[14/Apr/2026 18:18:23] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   7%|▋         | 104/1400 [12:00<2:04:49,  5.78s/it]

[14/Apr/2026 18:18:29] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   8%|▊         | 105/1400 [12:05<2:02:27,  5.67s/it]

[14/Apr/2026 18:18:35] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   8%|▊         | 106/1400 [12:11<2:05:15,  5.81s/it]

[14/Apr/2026 18:18:40] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   8%|▊         | 107/1400 [12:17<2:03:40,  5.74s/it]

[14/Apr/2026 18:18:46] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   8%|▊         | 108/1400 [12:22<2:01:12,  5.63s/it]

[14/Apr/2026 18:18:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   8%|▊         | 109/1400 [12:27<1:58:47,  5.52s/it]

[14/Apr/2026 18:18:58] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   8%|▊         | 110/1400 [12:34<2:07:01,  5.91s/it]

[14/Apr/2026 18:19:04] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   8%|▊         | 111/1400 [12:40<2:06:27,  5.89s/it]

[14/Apr/2026 18:19:09] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   8%|▊         | 112/1400 [12:45<2:03:06,  5.73s/it]

[14/Apr/2026 18:19:16] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   8%|▊         | 113/1400 [12:52<2:09:22,  6.03s/it]

[14/Apr/2026 18:19:21] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   8%|▊         | 114/1400 [12:58<2:06:08,  5.89s/it]

[14/Apr/2026 18:19:27] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   8%|▊         | 115/1400 [13:03<2:03:11,  5.75s/it]

[14/Apr/2026 18:19:32] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   8%|▊         | 116/1400 [13:09<2:02:55,  5.74s/it]

[14/Apr/2026 18:19:39] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   8%|▊         | 117/1400 [13:16<2:09:56,  6.08s/it]

[14/Apr/2026 18:19:49] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   8%|▊         | 118/1400 [13:25<2:31:50,  7.11s/it]

[14/Apr/2026 18:19:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   8%|▊         | 119/1400 [13:31<2:22:00,  6.65s/it]

[14/Apr/2026 18:20:00] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   9%|▊         | 120/1400 [13:36<2:14:07,  6.29s/it]

[14/Apr/2026 18:20:05] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   9%|▊         | 121/1400 [13:42<2:10:10,  6.11s/it]

[14/Apr/2026 18:20:17] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   9%|▊         | 122/1400 [13:53<2:45:38,  7.78s/it]

[14/Apr/2026 18:20:25] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   9%|▉         | 123/1400 [14:01<2:43:13,  7.67s/it]

[14/Apr/2026 18:20:30] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   9%|▉         | 124/1400 [14:06<2:29:18,  7.02s/it]

[14/Apr/2026 18:20:35] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   9%|▉         | 125/1400 [14:12<2:18:47,  6.53s/it]

[14/Apr/2026 18:20:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   9%|▉         | 126/1400 [14:20<2:30:18,  7.08s/it]

[14/Apr/2026 18:20:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   9%|▉         | 127/1400 [14:28<2:33:40,  7.24s/it]

[14/Apr/2026 18:20:57] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   9%|▉         | 128/1400 [14:34<2:23:58,  6.79s/it]

[14/Apr/2026 18:21:04] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   9%|▉         | 129/1400 [14:40<2:24:56,  6.84s/it]

[14/Apr/2026 18:21:10] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   9%|▉         | 130/1400 [14:46<2:17:53,  6.51s/it]

[14/Apr/2026 18:21:16] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   9%|▉         | 131/1400 [14:52<2:12:57,  6.29s/it]

[14/Apr/2026 18:21:21] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:   9%|▉         | 132/1400 [14:58<2:08:57,  6.10s/it]

[14/Apr/2026 18:21:27] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  10%|▉         | 133/1400 [15:04<2:08:49,  6.10s/it]

[14/Apr/2026 18:21:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  10%|▉         | 134/1400 [15:10<2:10:58,  6.21s/it]

[14/Apr/2026 18:21:40] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  10%|▉         | 135/1400 [15:16<2:09:37,  6.15s/it]

[14/Apr/2026 18:21:49] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  10%|▉         | 136/1400 [15:25<2:27:22,  7.00s/it]

[14/Apr/2026 18:21:55] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  10%|▉         | 137/1400 [15:31<2:20:41,  6.68s/it]

[14/Apr/2026 18:22:01] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  10%|▉         | 138/1400 [15:37<2:16:49,  6.51s/it]

[14/Apr/2026 18:22:10] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  10%|▉         | 139/1400 [15:46<2:33:49,  7.32s/it]

[14/Apr/2026 18:22:19] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  10%|█         | 140/1400 [15:55<2:44:10,  7.82s/it]

[14/Apr/2026 18:22:27] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  10%|█         | 141/1400 [16:03<2:44:41,  7.85s/it]

[14/Apr/2026 18:22:33] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  10%|█         | 142/1400 [16:09<2:33:06,  7.30s/it]

[14/Apr/2026 18:22:38] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  10%|█         | 143/1400 [16:14<2:14:59,  6.44s/it]

[14/Apr/2026 18:22:45] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  10%|█         | 144/1400 [16:22<2:23:26,  6.85s/it]

[14/Apr/2026 18:22:53] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  10%|█         | 145/1400 [16:30<2:30:59,  7.22s/it]

[14/Apr/2026 18:23:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  10%|█         | 146/1400 [16:38<2:39:36,  7.64s/it]

[14/Apr/2026 18:23:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  10%|█         | 147/1400 [16:44<2:26:11,  7.00s/it]

[14/Apr/2026 18:23:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  11%|█         | 148/1400 [16:50<2:23:25,  6.87s/it]

[14/Apr/2026 18:23:20] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  11%|█         | 149/1400 [16:56<2:14:22,  6.44s/it]

[14/Apr/2026 18:23:27] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[14/Apr/2026 18:23:27] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row149_20260414_182327.csv (150 строк)

Analyzing:  11%|█         | 150/1400 [17:04<2:22:23,  6.83s/it]

📌 Чекпоинт [150/1400] → checkpoints/checkpoint_row149_20260414_182327.csv
[14/Apr/2026 18:23:36] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  11%|█         | 151/1400 [17:12<2:32:56,  7.35s/it]

[14/Apr/2026 18:23:45] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  11%|█         | 152/1400 [17:22<2:46:42,  8.01s/it]

[14/Apr/2026 18:23:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  11%|█         | 153/1400 [17:31<2:51:46,  8.27s/it]

[14/Apr/2026 18:24:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  11%|█         | 154/1400 [17:38<2:46:31,  8.02s/it]

[14/Apr/2026 18:24:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  11%|█         | 155/1400 [17:44<2:33:00,  7.37s/it]

[14/Apr/2026 18:24:13] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  11%|█         | 156/1400 [17:49<2:21:56,  6.85s/it]

[14/Apr/2026 18:24:20] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  11%|█         | 157/1400 [17:56<2:19:19,  6.73s/it]

[14/Apr/2026 18:24:25] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  11%|█▏        | 158/1400 [18:01<2:11:47,  6.37s/it]

[14/Apr/2026 18:24:30] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  11%|█▏        | 159/1400 [18:07<2:04:08,  6.00s/it]

[14/Apr/2026 18:24:36] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  11%|█▏        | 160/1400 [18:12<1:59:42,  5.79s/it]

[14/Apr/2026 18:24:41] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  12%|█▏        | 161/1400 [18:17<1:57:41,  5.70s/it]

[14/Apr/2026 18:24:47] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  12%|█▏        | 162/1400 [18:23<1:58:00,  5.72s/it]

[14/Apr/2026 18:24:53] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  12%|█▏        | 163/1400 [18:29<1:59:07,  5.78s/it]

[14/Apr/2026 18:24:59] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  12%|█▏        | 164/1400 [18:35<2:00:26,  5.85s/it]

[14/Apr/2026 18:25:04] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  12%|█▏        | 165/1400 [18:40<1:56:54,  5.68s/it]

[14/Apr/2026 18:25:11] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  12%|█▏        | 166/1400 [18:47<2:05:09,  6.09s/it]

[14/Apr/2026 18:25:16] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  12%|█▏        | 167/1400 [18:52<1:57:37,  5.72s/it]

[14/Apr/2026 18:25:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  12%|█▏        | 168/1400 [18:58<1:58:45,  5.78s/it]

[14/Apr/2026 18:25:28] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  12%|█▏        | 169/1400 [19:04<1:58:39,  5.78s/it]

[14/Apr/2026 18:25:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  12%|█▏        | 170/1400 [19:10<2:02:30,  5.98s/it]

[14/Apr/2026 18:25:40] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  12%|█▏        | 171/1400 [19:16<2:02:32,  5.98s/it]

[14/Apr/2026 18:25:46] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  12%|█▏        | 172/1400 [19:22<2:01:23,  5.93s/it]

[14/Apr/2026 18:25:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  12%|█▏        | 173/1400 [19:28<1:58:58,  5.82s/it]

[14/Apr/2026 18:25:58] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  12%|█▏        | 174/1400 [19:34<2:01:43,  5.96s/it]

[14/Apr/2026 18:26:04] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  12%|█▎        | 175/1400 [19:40<2:01:31,  5.95s/it]

[14/Apr/2026 18:26:10] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  13%|█▎        | 176/1400 [19:46<2:01:21,  5.95s/it]

[14/Apr/2026 18:26:21] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  13%|█▎        | 177/1400 [19:58<2:36:19,  7.67s/it]

[14/Apr/2026 18:26:29] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  13%|█▎        | 178/1400 [20:06<2:37:42,  7.74s/it]

[14/Apr/2026 18:26:36] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  13%|█▎        | 179/1400 [20:12<2:29:24,  7.34s/it]

[14/Apr/2026 18:26:41] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  13%|█▎        | 180/1400 [20:17<2:17:12,  6.75s/it]

[14/Apr/2026 18:26:48] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  13%|█▎        | 181/1400 [20:25<2:21:16,  6.95s/it]

[14/Apr/2026 18:26:55] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  13%|█▎        | 182/1400 [20:31<2:16:12,  6.71s/it]

[14/Apr/2026 18:27:00] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  13%|█▎        | 183/1400 [20:36<2:06:28,  6.24s/it]

[14/Apr/2026 18:27:06] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  13%|█▎        | 184/1400 [20:43<2:08:53,  6.36s/it]

[14/Apr/2026 18:27:12] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  13%|█▎        | 185/1400 [20:48<2:04:30,  6.15s/it]

[14/Apr/2026 18:27:17] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  13%|█▎        | 186/1400 [20:53<1:57:11,  5.79s/it]

[14/Apr/2026 18:27:23] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  13%|█▎        | 187/1400 [20:59<1:57:43,  5.82s/it]

[14/Apr/2026 18:27:28] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  13%|█▎        | 188/1400 [21:05<1:54:41,  5.68s/it]

[14/Apr/2026 18:27:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  14%|█▎        | 189/1400 [21:10<1:53:51,  5.64s/it]

[14/Apr/2026 18:27:39] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  14%|█▎        | 190/1400 [21:16<1:54:13,  5.66s/it]

[14/Apr/2026 18:27:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  14%|█▎        | 191/1400 [21:21<1:49:55,  5.46s/it]

[14/Apr/2026 18:27:50] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  14%|█▎        | 192/1400 [21:26<1:50:54,  5.51s/it]

[14/Apr/2026 18:27:56] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  14%|█▍        | 193/1400 [21:33<1:56:09,  5.77s/it]

[14/Apr/2026 18:28:05] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  14%|█▍        | 194/1400 [21:41<2:12:18,  6.58s/it]

[14/Apr/2026 18:28:10] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  14%|█▍        | 195/1400 [21:47<2:04:24,  6.19s/it]

[14/Apr/2026 18:28:15] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  14%|█▍        | 196/1400 [21:51<1:56:05,  5.79s/it]

[14/Apr/2026 18:28:23] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  14%|█▍        | 197/1400 [21:59<2:09:55,  6.48s/it]

[14/Apr/2026 18:28:32] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  14%|█▍        | 198/1400 [22:08<2:21:01,  7.04s/it]

[14/Apr/2026 18:28:37] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  14%|█▍        | 199/1400 [22:13<2:10:54,  6.54s/it]

[14/Apr/2026 18:28:42] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[14/Apr/2026 18:28:42] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row199_20260414_182842.csv (200 строк)
[14/Apr/2026 18:28:42] INFO - Удалён старый чекпоинт: checkpoints/checkpoint_row49_20260414_181234.csv

Analyzing:  14%|█▍        | 200/1400 [22:19<2:03:26,  6.17s/it]

📌 Чекпоинт [200/1400] → checkpoints/checkpoint_row199_20260414_182842.csv
[14/Apr/2026 18:28:47] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  14%|█▍        | 201/1400 [22:24<1:58:02,  5.91s/it]

[14/Apr/2026 18:28:53] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  14%|█▍        | 202/1400 [22:29<1:55:43,  5.80s/it]

[14/Apr/2026 18:28:58] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  14%|█▍        | 203/1400 [22:34<1:51:26,  5.59s/it]

[14/Apr/2026 18:29:03] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  15%|█▍        | 204/1400 [22:39<1:47:13,  5.38s/it]

[14/Apr/2026 18:29:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  15%|█▍        | 205/1400 [22:44<1:43:52,  5.22s/it]

[14/Apr/2026 18:29:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  15%|█▍        | 206/1400 [22:50<1:49:40,  5.51s/it]

[14/Apr/2026 18:29:19] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  15%|█▍        | 207/1400 [22:56<1:47:51,  5.42s/it]

[14/Apr/2026 18:29:25] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  15%|█▍        | 208/1400 [23:02<1:51:29,  5.61s/it]

[14/Apr/2026 18:29:31] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  15%|█▍        | 209/1400 [23:07<1:49:27,  5.51s/it]

[14/Apr/2026 18:29:36] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  15%|█▌        | 210/1400 [23:12<1:49:39,  5.53s/it]

[14/Apr/2026 18:29:42] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  15%|█▌        | 211/1400 [23:18<1:48:57,  5.50s/it]

[14/Apr/2026 18:29:47] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  15%|█▌        | 212/1400 [23:23<1:45:51,  5.35s/it]

[14/Apr/2026 18:29:52] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  15%|█▌        | 213/1400 [23:28<1:46:30,  5.38s/it]

[14/Apr/2026 18:29:57] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  15%|█▌        | 214/1400 [23:33<1:43:39,  5.24s/it]

[14/Apr/2026 18:30:03] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  15%|█▌        | 215/1400 [23:39<1:48:48,  5.51s/it]

[14/Apr/2026 18:30:09] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  15%|█▌        | 216/1400 [23:45<1:48:22,  5.49s/it]

[14/Apr/2026 18:30:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  16%|█▌        | 217/1400 [23:50<1:45:24,  5.35s/it]

[14/Apr/2026 18:30:21] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  16%|█▌        | 218/1400 [23:57<1:55:28,  5.86s/it]

[14/Apr/2026 18:30:27] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  16%|█▌        | 219/1400 [24:03<1:57:27,  5.97s/it]

[14/Apr/2026 18:30:32] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  16%|█▌        | 220/1400 [24:09<1:54:50,  5.84s/it]

[14/Apr/2026 18:30:37] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  16%|█▌        | 221/1400 [24:14<1:50:11,  5.61s/it]

[14/Apr/2026 18:30:42] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  16%|█▌        | 222/1400 [24:19<1:46:00,  5.40s/it]

[14/Apr/2026 18:30:47] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  16%|█▌        | 223/1400 [24:24<1:44:01,  5.30s/it]

[14/Apr/2026 18:30:53] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  16%|█▌        | 224/1400 [24:29<1:46:13,  5.42s/it]

[14/Apr/2026 18:30:58] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  16%|█▌        | 225/1400 [24:35<1:44:36,  5.34s/it]

[14/Apr/2026 18:31:06] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  16%|█▌        | 226/1400 [24:42<1:56:09,  5.94s/it]

[14/Apr/2026 18:31:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  16%|█▌        | 227/1400 [24:50<2:10:01,  6.65s/it]

[14/Apr/2026 18:31:19] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  16%|█▋        | 228/1400 [24:56<2:02:48,  6.29s/it]

[14/Apr/2026 18:31:26] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  16%|█▋        | 229/1400 [25:02<2:05:14,  6.42s/it]

[14/Apr/2026 18:31:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  16%|█▋        | 230/1400 [25:10<2:11:51,  6.76s/it]

[14/Apr/2026 18:31:39] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  16%|█▋        | 231/1400 [25:16<2:05:02,  6.42s/it]

[14/Apr/2026 18:31:45] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  17%|█▋        | 232/1400 [25:22<2:02:23,  6.29s/it]

[14/Apr/2026 18:31:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  17%|█▋        | 233/1400 [25:27<1:58:57,  6.12s/it]

[14/Apr/2026 18:31:57] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  17%|█▋        | 234/1400 [25:33<1:55:26,  5.94s/it]

[14/Apr/2026 18:32:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  17%|█▋        | 235/1400 [25:39<1:54:42,  5.91s/it]

[14/Apr/2026 18:32:12] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  17%|█▋        | 236/1400 [25:48<2:16:52,  7.06s/it]

[14/Apr/2026 18:32:18] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  17%|█▋        | 237/1400 [25:54<2:09:31,  6.68s/it]

[14/Apr/2026 18:32:23] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  17%|█▋        | 238/1400 [25:59<2:00:08,  6.20s/it]

[14/Apr/2026 18:32:28] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  17%|█▋        | 239/1400 [26:04<1:51:14,  5.75s/it]

[14/Apr/2026 18:32:33] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  17%|█▋        | 240/1400 [26:09<1:49:38,  5.67s/it]

[14/Apr/2026 18:32:38] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  17%|█▋        | 241/1400 [26:14<1:45:10,  5.45s/it]

[14/Apr/2026 18:32:43] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  17%|█▋        | 242/1400 [26:19<1:41:16,  5.25s/it]

[14/Apr/2026 18:32:48] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  17%|█▋        | 243/1400 [26:24<1:40:22,  5.21s/it]

[14/Apr/2026 18:32:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  17%|█▋        | 244/1400 [26:30<1:44:07,  5.40s/it]

[14/Apr/2026 18:33:00] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  18%|█▊        | 245/1400 [26:36<1:48:10,  5.62s/it]

[14/Apr/2026 18:33:06] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  18%|█▊        | 246/1400 [26:42<1:50:58,  5.77s/it]

[14/Apr/2026 18:33:12] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  18%|█▊        | 247/1400 [26:48<1:51:10,  5.79s/it]

[14/Apr/2026 18:33:18] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  18%|█▊        | 248/1400 [26:54<1:50:57,  5.78s/it]

[14/Apr/2026 18:33:23] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  18%|█▊        | 249/1400 [26:59<1:46:21,  5.54s/it]

[14/Apr/2026 18:33:28] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[14/Apr/2026 18:33:28] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row249_20260414_183328.csv (250 строк)
[14/Apr/2026 18:33:28] INFO - Удалён старый чекпоинт: checkpoints/checkpoint_row99_20260414_181800.csv

Analyzing:  18%|█▊        | 250/1400 [27:04<1:44:29,  5.45s/it]

📌 Чекпоинт [250/1400] → checkpoints/checkpoint_row249_20260414_183328.csv
[14/Apr/2026 18:33:35] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  18%|█▊        | 251/1400 [27:11<1:51:29,  5.82s/it]

[14/Apr/2026 18:33:46] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  18%|█▊        | 252/1400 [27:22<2:21:11,  7.38s/it]

[14/Apr/2026 18:33:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  18%|█▊        | 253/1400 [27:27<2:09:12,  6.76s/it]

[14/Apr/2026 18:33:57] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  18%|█▊        | 254/1400 [27:33<2:03:11,  6.45s/it]

[14/Apr/2026 18:34:03] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  18%|█▊        | 255/1400 [27:39<2:02:31,  6.42s/it]

[14/Apr/2026 18:34:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  18%|█▊        | 256/1400 [27:45<1:55:37,  6.06s/it]

[14/Apr/2026 18:34:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  18%|█▊        | 257/1400 [27:50<1:52:15,  5.89s/it]

[14/Apr/2026 18:34:23] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  18%|█▊        | 258/1400 [27:59<2:09:01,  6.78s/it]

[14/Apr/2026 18:34:28] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  18%|█▊        | 259/1400 [28:04<2:00:29,  6.34s/it]

[14/Apr/2026 18:34:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  19%|█▊        | 260/1400 [28:10<1:56:39,  6.14s/it]

[14/Apr/2026 18:34:39] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  19%|█▊        | 261/1400 [28:15<1:53:44,  5.99s/it]

[14/Apr/2026 18:34:48] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  19%|█▊        | 262/1400 [28:24<2:07:43,  6.73s/it]

[14/Apr/2026 18:34:53] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  19%|█▉        | 263/1400 [28:29<1:59:09,  6.29s/it]

[14/Apr/2026 18:34:59] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  19%|█▉        | 264/1400 [28:35<1:56:45,  6.17s/it]

[14/Apr/2026 18:35:04] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  19%|█▉        | 265/1400 [28:40<1:51:49,  5.91s/it]

[14/Apr/2026 18:35:10] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  19%|█▉        | 266/1400 [28:46<1:49:26,  5.79s/it]

[14/Apr/2026 18:35:17] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  19%|█▉        | 267/1400 [28:53<1:56:52,  6.19s/it]

[14/Apr/2026 18:35:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  19%|█▉        | 268/1400 [28:58<1:49:41,  5.81s/it]

[14/Apr/2026 18:35:26] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  19%|█▉        | 269/1400 [29:03<1:44:03,  5.52s/it]

[14/Apr/2026 18:35:32] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  19%|█▉        | 270/1400 [29:08<1:42:11,  5.43s/it]

[14/Apr/2026 18:35:41] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  19%|█▉        | 271/1400 [29:18<2:06:43,  6.74s/it]

[14/Apr/2026 18:35:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  19%|█▉        | 272/1400 [29:27<2:21:38,  7.53s/it]

[14/Apr/2026 18:35:57] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  20%|█▉        | 273/1400 [29:33<2:11:23,  7.00s/it]

[14/Apr/2026 18:36:05] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  20%|█▉        | 274/1400 [29:41<2:17:39,  7.34s/it]

[14/Apr/2026 18:36:10] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  20%|█▉        | 275/1400 [29:46<2:04:29,  6.64s/it]

[14/Apr/2026 18:36:17] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  20%|█▉        | 276/1400 [29:53<2:05:12,  6.68s/it]

[14/Apr/2026 18:36:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  20%|█▉        | 277/1400 [29:58<1:56:23,  6.22s/it]

[14/Apr/2026 18:36:29] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  20%|█▉        | 278/1400 [30:05<1:59:42,  6.40s/it]

[14/Apr/2026 18:36:33] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  20%|█▉        | 279/1400 [30:10<1:51:24,  5.96s/it]

[14/Apr/2026 18:36:41] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  20%|██        | 280/1400 [30:18<2:02:08,  6.54s/it]

[14/Apr/2026 18:36:47] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  20%|██        | 281/1400 [30:24<1:59:40,  6.42s/it]

[14/Apr/2026 18:36:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  20%|██        | 282/1400 [30:30<1:58:45,  6.37s/it]

[14/Apr/2026 18:37:00] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  20%|██        | 283/1400 [30:36<1:57:36,  6.32s/it]

[14/Apr/2026 18:37:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  20%|██        | 284/1400 [30:44<2:06:39,  6.81s/it]

[14/Apr/2026 18:37:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  20%|██        | 285/1400 [30:50<2:03:09,  6.63s/it]

[14/Apr/2026 18:37:20] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  20%|██        | 286/1400 [30:57<2:00:32,  6.49s/it]

[14/Apr/2026 18:37:26] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  20%|██        | 287/1400 [31:02<1:54:21,  6.16s/it]

[14/Apr/2026 18:37:32] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  21%|██        | 288/1400 [31:09<1:57:08,  6.32s/it]

[14/Apr/2026 18:37:38] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  21%|██        | 289/1400 [31:14<1:51:27,  6.02s/it]

[14/Apr/2026 18:37:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  21%|██        | 290/1400 [31:20<1:51:53,  6.05s/it]

[14/Apr/2026 18:37:50] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  21%|██        | 291/1400 [31:26<1:50:08,  5.96s/it]

[14/Apr/2026 18:37:56] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  21%|██        | 292/1400 [31:33<1:55:12,  6.24s/it]

[14/Apr/2026 18:38:05] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  21%|██        | 293/1400 [31:41<2:07:23,  6.90s/it]

[14/Apr/2026 18:38:11] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  21%|██        | 294/1400 [31:48<2:04:19,  6.74s/it]

[14/Apr/2026 18:38:18] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  21%|██        | 295/1400 [31:54<2:04:10,  6.74s/it]

[14/Apr/2026 18:38:28] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  21%|██        | 296/1400 [32:04<2:20:13,  7.62s/it]

[14/Apr/2026 18:38:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  21%|██        | 297/1400 [32:11<2:15:43,  7.38s/it]

[14/Apr/2026 18:38:41] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  21%|██▏       | 298/1400 [32:17<2:11:33,  7.16s/it]

[14/Apr/2026 18:38:48] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  21%|██▏       | 299/1400 [32:24<2:07:15,  6.93s/it]

[14/Apr/2026 18:38:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[14/Apr/2026 18:38:55] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row299_20260414_183854.csv (300 строк)
[14/Apr/2026 18:38:55] INFO - Удалён старый чекпоинт: checkpoints/checkpoint_row149_20260414_182327.csv

Analyzing:  21%|██▏       | 300/1400 [32:31<2:07:18,  6.94s/it]

📌 Чекпоинт [300/1400] → checkpoints/checkpoint_row299_20260414_183854.csv
[14/Apr/2026 18:39:01] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  22%|██▏       | 301/1400 [32:37<2:02:02,  6.66s/it]

[14/Apr/2026 18:39:07] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  22%|██▏       | 302/1400 [32:43<1:59:28,  6.53s/it]

[14/Apr/2026 18:39:12] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  22%|██▏       | 303/1400 [32:48<1:52:22,  6.15s/it]

[14/Apr/2026 18:39:18] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  22%|██▏       | 304/1400 [32:54<1:51:26,  6.10s/it]

[14/Apr/2026 18:39:25] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  22%|██▏       | 305/1400 [33:02<1:57:29,  6.44s/it]

[14/Apr/2026 18:39:33] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  22%|██▏       | 306/1400 [33:10<2:06:13,  6.92s/it]

[14/Apr/2026 18:39:39] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  22%|██▏       | 307/1400 [33:16<2:00:48,  6.63s/it]

[14/Apr/2026 18:39:45] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  22%|██▏       | 308/1400 [33:22<1:57:17,  6.44s/it]

[14/Apr/2026 18:39:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  22%|██▏       | 309/1400 [33:27<1:53:02,  6.22s/it]

[14/Apr/2026 18:39:56] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  22%|██▏       | 310/1400 [33:32<1:46:20,  5.85s/it]

[14/Apr/2026 18:40:01] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  22%|██▏       | 311/1400 [33:38<1:43:11,  5.69s/it]

[14/Apr/2026 18:40:10] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  22%|██▏       | 312/1400 [33:46<2:00:53,  6.67s/it]

[14/Apr/2026 18:40:16] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  22%|██▏       | 313/1400 [33:52<1:54:29,  6.32s/it]

[14/Apr/2026 18:40:21] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  22%|██▏       | 314/1400 [33:57<1:48:57,  6.02s/it]

[14/Apr/2026 18:40:26] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  22%|██▎       | 315/1400 [34:03<1:45:12,  5.82s/it]

[14/Apr/2026 18:40:33] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  23%|██▎       | 316/1400 [34:10<1:51:02,  6.15s/it]

[14/Apr/2026 18:40:39] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  23%|██▎       | 317/1400 [34:15<1:46:32,  5.90s/it]

[14/Apr/2026 18:40:45] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  23%|██▎       | 318/1400 [34:22<1:51:46,  6.20s/it]

[14/Apr/2026 18:40:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  23%|██▎       | 319/1400 [34:27<1:46:16,  5.90s/it]

[14/Apr/2026 18:40:56] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  23%|██▎       | 320/1400 [34:32<1:44:02,  5.78s/it]

[14/Apr/2026 18:41:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  23%|██▎       | 321/1400 [34:38<1:44:27,  5.81s/it]

[14/Apr/2026 18:41:09] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  23%|██▎       | 322/1400 [34:45<1:49:17,  6.08s/it]

[14/Apr/2026 18:41:17] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  23%|██▎       | 323/1400 [34:54<2:02:34,  6.83s/it]

[14/Apr/2026 18:41:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  23%|██▎       | 324/1400 [34:59<1:53:08,  6.31s/it]

[14/Apr/2026 18:41:28] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  23%|██▎       | 325/1400 [35:04<1:48:50,  6.07s/it]

[14/Apr/2026 18:41:32] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  23%|██▎       | 326/1400 [35:09<1:39:15,  5.54s/it]

[14/Apr/2026 18:41:38] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  23%|██▎       | 327/1400 [35:15<1:41:36,  5.68s/it]

[14/Apr/2026 18:41:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  23%|██▎       | 328/1400 [35:20<1:40:25,  5.62s/it]

[14/Apr/2026 18:41:49] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  24%|██▎       | 329/1400 [35:26<1:39:29,  5.57s/it]

[14/Apr/2026 18:41:55] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  24%|██▎       | 330/1400 [35:32<1:41:54,  5.71s/it]

[14/Apr/2026 18:42:01] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  24%|██▎       | 331/1400 [35:37<1:42:21,  5.74s/it]

[14/Apr/2026 18:42:10] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  24%|██▎       | 332/1400 [35:47<2:00:34,  6.77s/it]

[14/Apr/2026 18:42:16] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  24%|██▍       | 333/1400 [35:52<1:55:27,  6.49s/it]

[14/Apr/2026 18:42:23] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  24%|██▍       | 334/1400 [35:59<1:56:51,  6.58s/it]

[14/Apr/2026 18:42:28] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  24%|██▍       | 335/1400 [36:05<1:50:53,  6.25s/it]

[14/Apr/2026 18:42:36] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  24%|██▍       | 336/1400 [36:13<1:59:57,  6.76s/it]

[14/Apr/2026 18:42:43] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  24%|██▍       | 337/1400 [36:19<1:57:24,  6.63s/it]

[14/Apr/2026 18:42:48] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  24%|██▍       | 338/1400 [36:25<1:52:27,  6.35s/it]

[14/Apr/2026 18:42:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  24%|██▍       | 339/1400 [36:30<1:46:13,  6.01s/it]

[14/Apr/2026 18:43:03] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  24%|██▍       | 340/1400 [36:40<2:05:41,  7.11s/it]

[14/Apr/2026 18:43:10] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  24%|██▍       | 341/1400 [36:46<2:03:47,  7.01s/it]

[14/Apr/2026 18:43:16] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  24%|██▍       | 342/1400 [36:52<1:57:54,  6.69s/it]

[14/Apr/2026 18:43:20] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  24%|██▍       | 343/1400 [36:56<1:44:39,  5.94s/it]

[14/Apr/2026 18:43:26] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  25%|██▍       | 344/1400 [37:02<1:42:10,  5.81s/it]

[14/Apr/2026 18:43:31] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  25%|██▍       | 345/1400 [37:07<1:39:03,  5.63s/it]

[14/Apr/2026 18:43:36] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  25%|██▍       | 346/1400 [37:12<1:36:14,  5.48s/it]

[14/Apr/2026 18:43:43] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  25%|██▍       | 347/1400 [37:19<1:41:59,  5.81s/it]

[14/Apr/2026 18:43:48] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  25%|██▍       | 348/1400 [37:24<1:39:55,  5.70s/it]

[14/Apr/2026 18:43:55] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  25%|██▍       | 349/1400 [37:31<1:45:44,  6.04s/it]

[14/Apr/2026 18:44:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[14/Apr/2026 18:44:02] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row349_20260414_184402.csv (350 строк)
[14/Apr/2026 18:44:02] INFO - Удалён старый чекпоинт: checkpoints/checkpoint_row199_20260414_182842.csv

Analyzing:  25%|██▌       | 350/1400 [37:39<1:53:55,  6.51s/it]

📌 Чекпоинт [350/1400] → checkpoints/checkpoint_row349_20260414_184402.csv
[14/Apr/2026 18:44:09] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  25%|██▌       | 351/1400 [37:45<1:52:20,  6.43s/it]

[14/Apr/2026 18:44:16] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  25%|██▌       | 352/1400 [37:52<1:57:36,  6.73s/it]

[14/Apr/2026 18:44:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  25%|██▌       | 353/1400 [37:59<1:54:32,  6.56s/it]

[14/Apr/2026 18:44:27] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  25%|██▌       | 354/1400 [38:04<1:45:59,  6.08s/it]

[14/Apr/2026 18:44:33] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  25%|██▌       | 355/1400 [38:09<1:44:42,  6.01s/it]

[14/Apr/2026 18:44:39] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  25%|██▌       | 356/1400 [38:15<1:42:23,  5.88s/it]

[14/Apr/2026 18:44:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  26%|██▌       | 357/1400 [38:21<1:40:41,  5.79s/it]

[14/Apr/2026 18:44:50] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  26%|██▌       | 358/1400 [38:26<1:38:38,  5.68s/it]

[14/Apr/2026 18:44:56] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  26%|██▌       | 359/1400 [38:32<1:39:32,  5.74s/it]

[14/Apr/2026 18:45:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  26%|██▌       | 360/1400 [38:38<1:42:38,  5.92s/it]

[14/Apr/2026 18:45:07] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  26%|██▌       | 361/1400 [38:43<1:36:17,  5.56s/it]

[14/Apr/2026 18:45:13] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  26%|██▌       | 362/1400 [38:50<1:41:32,  5.87s/it]

[14/Apr/2026 18:45:18] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  26%|██▌       | 363/1400 [38:54<1:34:52,  5.49s/it]

[14/Apr/2026 18:45:23] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  26%|██▌       | 364/1400 [39:00<1:34:15,  5.46s/it]

[14/Apr/2026 18:45:30] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  26%|██▌       | 365/1400 [39:06<1:41:45,  5.90s/it]

[14/Apr/2026 18:45:36] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  26%|██▌       | 366/1400 [39:13<1:42:34,  5.95s/it]

[14/Apr/2026 18:45:41] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  26%|██▌       | 367/1400 [39:17<1:36:43,  5.62s/it]

[14/Apr/2026 18:45:47] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  26%|██▋       | 368/1400 [39:23<1:39:04,  5.76s/it]

[14/Apr/2026 18:45:55] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  26%|██▋       | 369/1400 [39:31<1:48:12,  6.30s/it]

[14/Apr/2026 18:45:59] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  26%|██▋       | 370/1400 [39:36<1:39:15,  5.78s/it]

[14/Apr/2026 18:46:04] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  26%|██▋       | 371/1400 [39:40<1:32:15,  5.38s/it]

[14/Apr/2026 18:46:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  27%|██▋       | 372/1400 [39:44<1:27:20,  5.10s/it]

[14/Apr/2026 18:46:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  27%|██▋       | 373/1400 [39:51<1:33:21,  5.45s/it]

[14/Apr/2026 18:46:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  27%|██▋       | 374/1400 [39:58<1:45:03,  6.14s/it]

[14/Apr/2026 18:46:28] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  27%|██▋       | 375/1400 [40:04<1:42:44,  6.01s/it]

[14/Apr/2026 18:46:33] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  27%|██▋       | 376/1400 [40:09<1:35:29,  5.60s/it]

[14/Apr/2026 18:46:41] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  27%|██▋       | 377/1400 [40:17<1:50:50,  6.50s/it]

[14/Apr/2026 18:46:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  27%|██▋       | 378/1400 [40:28<2:10:29,  7.66s/it]

[14/Apr/2026 18:46:56] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  27%|██▋       | 379/1400 [40:33<1:55:49,  6.81s/it]

[14/Apr/2026 18:47:04] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  27%|██▋       | 380/1400 [40:41<2:01:22,  7.14s/it]

[14/Apr/2026 18:47:19] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  27%|██▋       | 381/1400 [40:55<2:40:16,  9.44s/it]

[14/Apr/2026 18:47:24] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  27%|██▋       | 382/1400 [41:01<2:18:39,  8.17s/it]

[14/Apr/2026 18:47:29] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  27%|██▋       | 383/1400 [41:06<2:03:22,  7.28s/it]

[14/Apr/2026 18:47:35] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  27%|██▋       | 384/1400 [41:11<1:54:50,  6.78s/it]

[14/Apr/2026 18:47:45] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  28%|██▊       | 385/1400 [41:21<2:10:09,  7.69s/it]

[14/Apr/2026 18:47:50] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  28%|██▊       | 386/1400 [41:27<1:59:22,  7.06s/it]

[14/Apr/2026 18:47:58] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  28%|██▊       | 387/1400 [41:34<2:02:28,  7.25s/it]

[14/Apr/2026 18:48:06] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  28%|██▊       | 388/1400 [41:42<2:05:51,  7.46s/it]

[14/Apr/2026 18:48:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  28%|██▊       | 389/1400 [41:51<2:08:49,  7.65s/it]

[14/Apr/2026 18:48:19] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  28%|██▊       | 390/1400 [41:56<1:55:44,  6.88s/it]

[14/Apr/2026 18:48:25] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  28%|██▊       | 391/1400 [42:02<1:51:12,  6.61s/it]

[14/Apr/2026 18:48:31] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  28%|██▊       | 392/1400 [42:08<1:48:18,  6.45s/it]

[14/Apr/2026 18:48:37] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  28%|██▊       | 393/1400 [42:13<1:44:49,  6.25s/it]

[14/Apr/2026 18:48:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  28%|██▊       | 394/1400 [42:20<1:45:58,  6.32s/it]

[14/Apr/2026 18:48:48] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  28%|██▊       | 395/1400 [42:25<1:38:24,  5.87s/it]

[14/Apr/2026 18:48:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  28%|██▊       | 396/1400 [42:31<1:38:58,  5.92s/it]

[14/Apr/2026 18:49:00] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  28%|██▊       | 397/1400 [42:36<1:37:14,  5.82s/it]

[14/Apr/2026 18:49:06] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  28%|██▊       | 398/1400 [42:42<1:36:57,  5.81s/it]

[14/Apr/2026 18:49:11] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  28%|██▊       | 399/1400 [42:48<1:35:29,  5.72s/it]

[14/Apr/2026 18:49:17] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[14/Apr/2026 18:49:17] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row399_20260414_184917.csv (400 строк)
[14/Apr/2026 18:49:17] INFO - Удалён старый чекпоинт: checkpoints/checkpoint_row249_20260414_183328.csv

Analyzing:  29%|██▊       | 400/1400 [42:54<1:36:37,  5.80s/it]

📌 Чекпоинт [400/1400] → checkpoints/checkpoint_row399_20260414_184917.csv
[14/Apr/2026 18:49:23] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  29%|██▊       | 401/1400 [42:59<1:35:36,  5.74s/it]

[14/Apr/2026 18:49:29] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  29%|██▊       | 402/1400 [43:05<1:35:26,  5.74s/it]

[14/Apr/2026 18:49:36] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  29%|██▉       | 403/1400 [43:12<1:43:29,  6.23s/it]

[14/Apr/2026 18:49:45] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  29%|██▉       | 404/1400 [43:21<1:57:53,  7.10s/it]

[14/Apr/2026 18:49:52] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  29%|██▉       | 405/1400 [43:28<1:56:16,  7.01s/it]

[14/Apr/2026 18:49:57] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  29%|██▉       | 406/1400 [43:34<1:48:15,  6.53s/it]

[14/Apr/2026 18:50:05] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  29%|██▉       | 407/1400 [43:41<1:52:03,  6.77s/it]

[14/Apr/2026 18:50:13] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  29%|██▉       | 408/1400 [43:49<1:58:50,  7.19s/it]

[14/Apr/2026 18:50:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  29%|██▉       | 409/1400 [43:59<2:10:03,  7.87s/it]

[14/Apr/2026 18:50:29] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  29%|██▉       | 410/1400 [44:05<2:01:36,  7.37s/it]

[14/Apr/2026 18:50:38] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  29%|██▉       | 411/1400 [44:14<2:11:02,  7.95s/it]

[14/Apr/2026 18:50:45] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  29%|██▉       | 412/1400 [44:21<2:07:12,  7.73s/it]

[14/Apr/2026 18:50:45] WARNING - Row 412 | SKIP | REASONING is empty or missing
[14/Apr/2026 18:50:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  30%|██▉       | 414/1400 [44:27<1:30:43,  5.52s/it]

[14/Apr/2026 18:51:03] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  30%|██▉       | 415/1400 [44:39<1:55:49,  7.05s/it]

[14/Apr/2026 18:51:09] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  30%|██▉       | 416/1400 [44:45<1:51:43,  6.81s/it]

[14/Apr/2026 18:51:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  30%|██▉       | 417/1400 [44:51<1:46:03,  6.47s/it]

[14/Apr/2026 18:51:20] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  30%|██▉       | 418/1400 [44:57<1:43:45,  6.34s/it]

[14/Apr/2026 18:51:31] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  30%|██▉       | 419/1400 [45:07<2:04:28,  7.61s/it]

[14/Apr/2026 18:51:41] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  30%|███       | 420/1400 [45:18<2:16:23,  8.35s/it]

[14/Apr/2026 18:51:47] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  30%|███       | 421/1400 [45:23<2:04:10,  7.61s/it]

[14/Apr/2026 18:51:56] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  30%|███       | 422/1400 [45:32<2:08:32,  7.89s/it]

[14/Apr/2026 18:52:04] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  30%|███       | 423/1400 [45:40<2:09:25,  7.95s/it]

[14/Apr/2026 18:52:11] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  30%|███       | 424/1400 [45:47<2:05:28,  7.71s/it]

[14/Apr/2026 18:52:17] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  30%|███       | 425/1400 [45:53<1:56:28,  7.17s/it]

[14/Apr/2026 18:52:25] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  30%|███       | 426/1400 [46:01<1:59:10,  7.34s/it]

[14/Apr/2026 18:52:30] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  30%|███       | 427/1400 [46:07<1:51:09,  6.85s/it]

[14/Apr/2026 18:52:36] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  31%|███       | 428/1400 [46:12<1:44:48,  6.47s/it]

[14/Apr/2026 18:52:42] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  31%|███       | 429/1400 [46:18<1:43:59,  6.43s/it]

[14/Apr/2026 18:52:48] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  31%|███       | 430/1400 [46:25<1:42:45,  6.36s/it]

[14/Apr/2026 18:52:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  31%|███       | 431/1400 [46:31<1:40:32,  6.23s/it]

[14/Apr/2026 18:53:01] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  31%|███       | 432/1400 [46:38<1:44:30,  6.48s/it]

[14/Apr/2026 18:53:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  31%|███       | 433/1400 [46:44<1:42:55,  6.39s/it]

[14/Apr/2026 18:53:15] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  31%|███       | 434/1400 [46:51<1:46:04,  6.59s/it]

[14/Apr/2026 18:53:25] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  31%|███       | 435/1400 [47:01<2:02:04,  7.59s/it]

[14/Apr/2026 18:53:32] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  31%|███       | 436/1400 [47:08<2:01:47,  7.58s/it]

[14/Apr/2026 18:53:42] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  31%|███       | 437/1400 [47:18<2:11:47,  8.21s/it]

[14/Apr/2026 18:53:49] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  31%|███▏      | 438/1400 [47:25<2:04:54,  7.79s/it]

[14/Apr/2026 18:53:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  31%|███▏      | 439/1400 [47:30<1:53:28,  7.08s/it]

[14/Apr/2026 18:53:59] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  31%|███▏      | 440/1400 [47:36<1:44:51,  6.55s/it]

[14/Apr/2026 18:54:05] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  32%|███▏      | 441/1400 [47:41<1:40:08,  6.27s/it]

[14/Apr/2026 18:54:11] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  32%|███▏      | 442/1400 [47:47<1:38:32,  6.17s/it]

[14/Apr/2026 18:54:19] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  32%|███▏      | 443/1400 [47:56<1:49:26,  6.86s/it]

[14/Apr/2026 18:54:25] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  32%|███▏      | 444/1400 [48:01<1:42:39,  6.44s/it]

[14/Apr/2026 18:54:30] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  32%|███▏      | 445/1400 [48:06<1:36:50,  6.08s/it]

[14/Apr/2026 18:54:36] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  32%|███▏      | 446/1400 [48:12<1:34:45,  5.96s/it]

[14/Apr/2026 18:54:45] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  32%|███▏      | 447/1400 [48:22<1:51:29,  7.02s/it]

[14/Apr/2026 18:54:52] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  32%|███▏      | 448/1400 [48:28<1:48:10,  6.82s/it]

[14/Apr/2026 18:54:57] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  32%|███▏      | 449/1400 [48:34<1:43:07,  6.51s/it]

[14/Apr/2026 18:55:03] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[14/Apr/2026 18:55:03] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row449_20260414_185503.csv (450 строк)
[14/Apr/2026 18:55:03] INFO - Удалён старый чекпоинт: checkpoints/checkpoint_row299_20260414_183854.csv

Analyzing:  32%|███▏      | 450/1400 [48:39<1:38:17,  6.21s/it]

📌 Чекпоинт [450/1400] → checkpoints/checkpoint_row449_20260414_185503.csv
[14/Apr/2026 18:55:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  32%|███▏      | 451/1400 [48:44<1:33:50,  5.93s/it]

[14/Apr/2026 18:55:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  32%|███▏      | 452/1400 [48:50<1:33:42,  5.93s/it]

[14/Apr/2026 18:55:24] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  32%|███▏      | 453/1400 [49:01<1:54:48,  7.27s/it]

[14/Apr/2026 18:55:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  32%|███▏      | 454/1400 [49:10<2:05:43,  7.97s/it]

[14/Apr/2026 18:55:39] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  32%|███▎      | 455/1400 [49:15<1:51:18,  7.07s/it]

[14/Apr/2026 18:55:45] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  33%|███▎      | 456/1400 [49:21<1:46:18,  6.76s/it]

[14/Apr/2026 18:55:55] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  33%|███▎      | 457/1400 [49:32<2:03:21,  7.85s/it]

[14/Apr/2026 18:56:05] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  33%|███▎      | 458/1400 [49:41<2:11:56,  8.40s/it]

[14/Apr/2026 18:56:12] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  33%|███▎      | 459/1400 [49:48<2:04:12,  7.92s/it]

[14/Apr/2026 18:56:20] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  33%|███▎      | 460/1400 [49:57<2:06:24,  8.07s/it]

[14/Apr/2026 18:56:27] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  33%|███▎      | 461/1400 [50:03<1:57:18,  7.50s/it]

[14/Apr/2026 18:56:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  33%|███▎      | 462/1400 [50:11<1:58:46,  7.60s/it]

[14/Apr/2026 18:56:40] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  33%|███▎      | 463/1400 [50:16<1:48:53,  6.97s/it]

[14/Apr/2026 18:56:47] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  33%|███▎      | 464/1400 [50:23<1:47:17,  6.88s/it]

[14/Apr/2026 18:56:52] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  33%|███▎      | 465/1400 [50:29<1:41:45,  6.53s/it]

[14/Apr/2026 18:56:59] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  33%|███▎      | 466/1400 [50:35<1:43:28,  6.65s/it]

[14/Apr/2026 18:57:04] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  33%|███▎      | 467/1400 [50:40<1:35:32,  6.14s/it]

[14/Apr/2026 18:57:09] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  33%|███▎      | 468/1400 [50:46<1:31:09,  5.87s/it]

[14/Apr/2026 18:57:16] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  34%|███▎      | 469/1400 [50:52<1:34:19,  6.08s/it]

[14/Apr/2026 18:57:23] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  34%|███▎      | 470/1400 [50:59<1:36:50,  6.25s/it]

[14/Apr/2026 18:57:30] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  34%|███▎      | 471/1400 [51:06<1:40:50,  6.51s/it]

[14/Apr/2026 18:57:36] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  34%|███▎      | 472/1400 [51:12<1:39:58,  6.46s/it]

[14/Apr/2026 18:57:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  34%|███▍      | 473/1400 [51:21<1:48:46,  7.04s/it]

[14/Apr/2026 18:57:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  34%|███▍      | 474/1400 [51:27<1:44:41,  6.78s/it]

[14/Apr/2026 18:57:58] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  34%|███▍      | 475/1400 [51:34<1:46:32,  6.91s/it]

[14/Apr/2026 18:58:03] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  34%|███▍      | 476/1400 [51:40<1:40:01,  6.49s/it]

[14/Apr/2026 18:58:09] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  34%|███▍      | 477/1400 [51:45<1:34:30,  6.14s/it]

[14/Apr/2026 18:58:18] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  34%|███▍      | 478/1400 [51:54<1:49:22,  7.12s/it]

[14/Apr/2026 18:58:26] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  34%|███▍      | 479/1400 [52:02<1:51:40,  7.27s/it]

[14/Apr/2026 18:58:31] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  34%|███▍      | 480/1400 [52:07<1:42:49,  6.71s/it]

[14/Apr/2026 18:58:42] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  34%|███▍      | 481/1400 [52:18<2:00:58,  7.90s/it]

[14/Apr/2026 18:58:47] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  34%|███▍      | 482/1400 [52:24<1:50:18,  7.21s/it]

[14/Apr/2026 18:58:57] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  34%|███▍      | 483/1400 [52:34<2:03:11,  8.06s/it]

[14/Apr/2026 18:59:04] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  35%|███▍      | 484/1400 [52:41<1:58:13,  7.74s/it]

[14/Apr/2026 18:59:10] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  35%|███▍      | 485/1400 [52:46<1:46:53,  7.01s/it]

[14/Apr/2026 18:59:15] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  35%|███▍      | 486/1400 [52:51<1:37:32,  6.40s/it]

[14/Apr/2026 18:59:21] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  35%|███▍      | 487/1400 [52:57<1:34:57,  6.24s/it]

[14/Apr/2026 18:59:27] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  35%|███▍      | 488/1400 [53:03<1:33:38,  6.16s/it]

[14/Apr/2026 18:59:32] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  35%|███▍      | 489/1400 [53:09<1:31:46,  6.04s/it]

[14/Apr/2026 18:59:43] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  35%|███▌      | 490/1400 [53:20<1:54:52,  7.57s/it]

[14/Apr/2026 18:59:49] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  35%|███▌      | 491/1400 [53:25<1:46:07,  7.00s/it]

[14/Apr/2026 18:59:55] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  35%|███▌      | 492/1400 [53:32<1:42:01,  6.74s/it]

[14/Apr/2026 19:00:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  35%|███▌      | 493/1400 [53:38<1:41:29,  6.71s/it]

[14/Apr/2026 19:00:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  35%|███▌      | 494/1400 [53:44<1:36:26,  6.39s/it]

[14/Apr/2026 19:00:13] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  35%|███▌      | 495/1400 [53:49<1:31:33,  6.07s/it]

[14/Apr/2026 19:00:20] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  35%|███▌      | 496/1400 [53:56<1:34:31,  6.27s/it]

[14/Apr/2026 19:00:25] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  36%|███▌      | 497/1400 [54:01<1:29:09,  5.92s/it]

[14/Apr/2026 19:00:33] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  36%|███▌      | 498/1400 [54:09<1:37:50,  6.51s/it]

[14/Apr/2026 19:00:38] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  36%|███▌      | 499/1400 [54:14<1:32:21,  6.15s/it]

[14/Apr/2026 19:00:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[14/Apr/2026 19:00:44] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row499_20260414_190044.csv (500 строк)
[14/Apr/2026 19:00:44] INFO - Удалён старый чекпоинт: checkpoints/checkpoint_row349_20260414_184402.csv

Analyzing:  36%|███▌      | 500/1400 [54:21<1:33:43,  6.25s/it]

📌 Чекпоинт [500/1400] → checkpoints/checkpoint_row499_20260414_190044.csv
[14/Apr/2026 19:00:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  36%|███▌      | 501/1400 [54:27<1:33:03,  6.21s/it]

[14/Apr/2026 19:00:56] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  36%|███▌      | 502/1400 [54:33<1:31:53,  6.14s/it]

[14/Apr/2026 19:01:03] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  36%|███▌      | 503/1400 [54:39<1:32:22,  6.18s/it]

[14/Apr/2026 19:01:09] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  36%|███▌      | 504/1400 [54:45<1:32:00,  6.16s/it]

[14/Apr/2026 19:01:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  36%|███▌      | 505/1400 [54:50<1:27:59,  5.90s/it]

[14/Apr/2026 19:01:19] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  36%|███▌      | 506/1400 [54:56<1:24:59,  5.70s/it]

[14/Apr/2026 19:01:27] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  36%|███▌      | 507/1400 [55:03<1:32:42,  6.23s/it]

[14/Apr/2026 19:01:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  36%|███▋      | 508/1400 [55:10<1:36:56,  6.52s/it]

[14/Apr/2026 19:01:39] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  36%|███▋      | 509/1400 [55:16<1:30:49,  6.12s/it]

[14/Apr/2026 19:01:47] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  36%|███▋      | 510/1400 [55:24<1:39:23,  6.70s/it]

[14/Apr/2026 19:01:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  36%|███▋      | 511/1400 [55:30<1:38:39,  6.66s/it]

[14/Apr/2026 19:02:01] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  37%|███▋      | 512/1400 [55:37<1:39:07,  6.70s/it]

[14/Apr/2026 19:02:06] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  37%|███▋      | 513/1400 [55:42<1:33:30,  6.32s/it]

[14/Apr/2026 19:02:13] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  37%|███▋      | 514/1400 [55:49<1:35:13,  6.45s/it]

[14/Apr/2026 19:02:18] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  37%|███▋      | 515/1400 [55:55<1:30:14,  6.12s/it]

[14/Apr/2026 19:02:24] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  37%|███▋      | 516/1400 [56:00<1:28:09,  5.98s/it]

[14/Apr/2026 19:02:29] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  37%|███▋      | 517/1400 [56:05<1:24:58,  5.77s/it]

[14/Apr/2026 19:02:35] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  37%|███▋      | 518/1400 [56:11<1:24:13,  5.73s/it]

[14/Apr/2026 19:02:40] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  37%|███▋      | 519/1400 [56:17<1:23:39,  5.70s/it]

[14/Apr/2026 19:02:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  37%|███▋      | 520/1400 [56:27<1:44:56,  7.16s/it]

[14/Apr/2026 19:03:00] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  37%|███▋      | 521/1400 [56:37<1:55:02,  7.85s/it]

[14/Apr/2026 19:03:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  37%|███▋      | 522/1400 [56:50<2:18:38,  9.47s/it]

[14/Apr/2026 19:03:25] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  37%|███▋      | 523/1400 [57:01<2:26:47, 10.04s/it]

[14/Apr/2026 19:03:30] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  37%|███▋      | 524/1400 [57:07<2:05:40,  8.61s/it]

[14/Apr/2026 19:03:37] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  38%|███▊      | 525/1400 [57:13<1:55:51,  7.94s/it]

[14/Apr/2026 19:03:42] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  38%|███▊      | 526/1400 [57:19<1:45:38,  7.25s/it]

[14/Apr/2026 19:03:48] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  38%|███▊      | 527/1400 [57:24<1:38:37,  6.78s/it]

[14/Apr/2026 19:03:55] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  38%|███▊      | 528/1400 [57:31<1:39:39,  6.86s/it]

[14/Apr/2026 19:04:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  38%|███▊      | 529/1400 [57:38<1:38:31,  6.79s/it]

[14/Apr/2026 19:04:07] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  38%|███▊      | 530/1400 [57:44<1:33:19,  6.44s/it]

[14/Apr/2026 19:04:13] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  38%|███▊      | 531/1400 [57:49<1:30:35,  6.25s/it]

[14/Apr/2026 19:04:18] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  38%|███▊      | 532/1400 [57:55<1:26:34,  5.98s/it]

[14/Apr/2026 19:04:25] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  38%|███▊      | 533/1400 [58:02<1:30:11,  6.24s/it]

[14/Apr/2026 19:04:32] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  38%|███▊      | 534/1400 [58:08<1:30:09,  6.25s/it]

[14/Apr/2026 19:04:37] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  38%|███▊      | 535/1400 [58:14<1:28:22,  6.13s/it]

[14/Apr/2026 19:04:43] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  38%|███▊      | 536/1400 [58:19<1:25:00,  5.90s/it]

[14/Apr/2026 19:04:49] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  38%|███▊      | 537/1400 [58:25<1:25:14,  5.93s/it]

[14/Apr/2026 19:04:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  38%|███▊      | 538/1400 [58:30<1:21:07,  5.65s/it]

[14/Apr/2026 19:05:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  38%|███▊      | 539/1400 [58:38<1:30:44,  6.32s/it]

[14/Apr/2026 19:05:07] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  39%|███▊      | 540/1400 [58:43<1:24:50,  5.92s/it]

[14/Apr/2026 19:05:13] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  39%|███▊      | 541/1400 [58:49<1:26:08,  6.02s/it]

[14/Apr/2026 19:05:19] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  39%|███▊      | 542/1400 [58:55<1:25:56,  6.01s/it]

[14/Apr/2026 19:05:26] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  39%|███▉      | 543/1400 [59:02<1:30:31,  6.34s/it]

[14/Apr/2026 19:05:32] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  39%|███▉      | 544/1400 [59:09<1:30:30,  6.34s/it]

[14/Apr/2026 19:05:39] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  39%|███▉      | 545/1400 [59:15<1:30:26,  6.35s/it]

[14/Apr/2026 19:05:46] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  39%|███▉      | 546/1400 [59:22<1:33:49,  6.59s/it]

[14/Apr/2026 19:05:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  39%|███▉      | 547/1400 [59:28<1:29:09,  6.27s/it]

[14/Apr/2026 19:05:59] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  39%|███▉      | 548/1400 [59:35<1:33:45,  6.60s/it]

[14/Apr/2026 19:06:05] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  39%|███▉      | 549/1400 [59:41<1:29:58,  6.34s/it]

[14/Apr/2026 19:06:11] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[14/Apr/2026 19:06:11] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row549_20260414_190611.csv (550 строк)
[14/Apr/2026 19:06:11] INFO - Удалён старый чекпоинт: checkpoints/checkpoint_row399_20260414_184917.csv

Analyzing:  39%|███▉      | 550/1400 [59:48<1:32:04,  6.50s/it]

📌 Чекпоинт [550/1400] → checkpoints/checkpoint_row549_20260414_190611.csv
[14/Apr/2026 19:06:17] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  39%|███▉      | 551/1400 [59:53<1:27:31,  6.19s/it]

[14/Apr/2026 19:06:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  39%|███▉      | 552/1400 [59:59<1:24:05,  5.95s/it]

[14/Apr/2026 19:06:30] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  40%|███▉      | 553/1400 [1:00:06<1:29:34,  6.35s/it]

[14/Apr/2026 19:06:36] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  40%|███▉      | 554/1400 [1:00:12<1:28:11,  6.25s/it]

[14/Apr/2026 19:06:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  40%|███▉      | 555/1400 [1:00:20<1:37:00,  6.89s/it]

[14/Apr/2026 19:06:48] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  40%|███▉      | 556/1400 [1:00:25<1:26:56,  6.18s/it]

[14/Apr/2026 19:06:53] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  40%|███▉      | 557/1400 [1:00:30<1:20:59,  5.76s/it]

[14/Apr/2026 19:06:58] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  40%|███▉      | 558/1400 [1:00:35<1:18:20,  5.58s/it]

[14/Apr/2026 19:07:04] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  40%|███▉      | 559/1400 [1:00:40<1:17:35,  5.54s/it]

[14/Apr/2026 19:07:10] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  40%|████      | 560/1400 [1:00:46<1:19:00,  5.64s/it]

[14/Apr/2026 19:07:15] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  40%|████      | 561/1400 [1:00:51<1:17:53,  5.57s/it]

[14/Apr/2026 19:07:20] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  40%|████      | 562/1400 [1:00:56<1:14:53,  5.36s/it]

[14/Apr/2026 19:07:31] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  40%|████      | 563/1400 [1:01:07<1:36:31,  6.92s/it]

[14/Apr/2026 19:07:37] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  40%|████      | 564/1400 [1:01:13<1:34:32,  6.79s/it]

[14/Apr/2026 19:07:43] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  40%|████      | 565/1400 [1:01:19<1:29:42,  6.45s/it]

[14/Apr/2026 19:07:48] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  40%|████      | 566/1400 [1:01:24<1:25:33,  6.16s/it]

[14/Apr/2026 19:07:53] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  40%|████      | 567/1400 [1:01:30<1:20:45,  5.82s/it]

[14/Apr/2026 19:08:00] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  41%|████      | 568/1400 [1:01:36<1:24:04,  6.06s/it]

[14/Apr/2026 19:08:05] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  41%|████      | 569/1400 [1:01:42<1:21:23,  5.88s/it]

[14/Apr/2026 19:08:10] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  41%|████      | 570/1400 [1:01:47<1:18:22,  5.67s/it]

[14/Apr/2026 19:08:16] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  41%|████      | 571/1400 [1:01:52<1:16:00,  5.50s/it]

[14/Apr/2026 19:08:21] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  41%|████      | 572/1400 [1:01:58<1:17:16,  5.60s/it]

[14/Apr/2026 19:08:27] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  41%|████      | 573/1400 [1:02:03<1:15:26,  5.47s/it]

[14/Apr/2026 19:08:32] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  41%|████      | 574/1400 [1:02:09<1:16:34,  5.56s/it]

[14/Apr/2026 19:08:38] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  41%|████      | 575/1400 [1:02:15<1:18:42,  5.72s/it]

[14/Apr/2026 19:08:49] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  41%|████      | 576/1400 [1:02:25<1:38:28,  7.17s/it]

[14/Apr/2026 19:08:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  41%|████      | 577/1400 [1:02:30<1:28:40,  6.46s/it]

[14/Apr/2026 19:09:00] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  41%|████▏     | 578/1400 [1:02:37<1:28:54,  6.49s/it]

[14/Apr/2026 19:09:07] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  41%|████▏     | 579/1400 [1:02:44<1:31:14,  6.67s/it]

[14/Apr/2026 19:09:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  41%|████▏     | 580/1400 [1:02:50<1:29:12,  6.53s/it]

[14/Apr/2026 19:09:20] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  42%|████▏     | 581/1400 [1:02:56<1:28:42,  6.50s/it]

[14/Apr/2026 19:09:27] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  42%|████▏     | 582/1400 [1:03:03<1:28:44,  6.51s/it]

[14/Apr/2026 19:09:32] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  42%|████▏     | 583/1400 [1:03:08<1:24:29,  6.21s/it]

[14/Apr/2026 19:09:38] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  42%|████▏     | 584/1400 [1:03:14<1:21:45,  6.01s/it]

[14/Apr/2026 19:09:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  42%|████▏     | 585/1400 [1:03:20<1:22:38,  6.08s/it]

[14/Apr/2026 19:09:50] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  42%|████▏     | 586/1400 [1:03:26<1:21:06,  5.98s/it]

[14/Apr/2026 19:09:55] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  42%|████▏     | 587/1400 [1:03:31<1:18:00,  5.76s/it]

[14/Apr/2026 19:10:01] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  42%|████▏     | 588/1400 [1:03:37<1:17:21,  5.72s/it]

[14/Apr/2026 19:10:07] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  42%|████▏     | 589/1400 [1:03:43<1:20:43,  5.97s/it]

[14/Apr/2026 19:10:12] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  42%|████▏     | 590/1400 [1:03:48<1:15:48,  5.62s/it]

[14/Apr/2026 19:10:21] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  42%|████▏     | 591/1400 [1:03:58<1:31:18,  6.77s/it]

[14/Apr/2026 19:10:30] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  42%|████▏     | 592/1400 [1:04:07<1:40:39,  7.47s/it]

[14/Apr/2026 19:10:36] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  42%|████▏     | 593/1400 [1:04:12<1:31:13,  6.78s/it]

[14/Apr/2026 19:10:42] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  42%|████▏     | 594/1400 [1:04:19<1:31:23,  6.80s/it]

[14/Apr/2026 19:10:48] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  42%|████▎     | 595/1400 [1:04:24<1:26:41,  6.46s/it]

[14/Apr/2026 19:10:53] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  43%|████▎     | 596/1400 [1:04:29<1:20:06,  5.98s/it]

[14/Apr/2026 19:10:58] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  43%|████▎     | 597/1400 [1:04:35<1:17:22,  5.78s/it]

[14/Apr/2026 19:11:04] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  43%|████▎     | 598/1400 [1:04:40<1:15:31,  5.65s/it]

[14/Apr/2026 19:11:10] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  43%|████▎     | 599/1400 [1:04:47<1:19:30,  5.96s/it]

[14/Apr/2026 19:11:16] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[14/Apr/2026 19:11:16] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row599_20260414_191116.csv (600 строк)
[14/Apr/2026 19:11:16] INFO - Удалён старый чекпоинт: checkpoints/checkpoint_row449_20260414_185503.csv

Analyzing:  43%|████▎     | 600/1400 [1:04:52<1:17:19,  5.80s/it]

📌 Чекпоинт [600/1400] → checkpoints/checkpoint_row599_20260414_191116.csv
[14/Apr/2026 19:11:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  43%|████▎     | 601/1400 [1:04:58<1:19:35,  5.98s/it]

[14/Apr/2026 19:11:29] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  43%|████▎     | 602/1400 [1:05:06<1:24:39,  6.37s/it]

[14/Apr/2026 19:11:40] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  43%|████▎     | 603/1400 [1:05:17<1:42:20,  7.70s/it]

[14/Apr/2026 19:11:46] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  43%|████▎     | 604/1400 [1:05:22<1:34:45,  7.14s/it]

[14/Apr/2026 19:11:53] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  43%|████▎     | 605/1400 [1:05:29<1:33:53,  7.09s/it]

[14/Apr/2026 19:12:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  43%|████▎     | 606/1400 [1:05:38<1:39:27,  7.52s/it]

[14/Apr/2026 19:12:07] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  43%|████▎     | 607/1400 [1:05:43<1:31:04,  6.89s/it]

[14/Apr/2026 19:12:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  43%|████▎     | 608/1400 [1:05:50<1:30:16,  6.84s/it]

[14/Apr/2026 19:12:21] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  44%|████▎     | 609/1400 [1:05:57<1:31:50,  6.97s/it]

[14/Apr/2026 19:12:27] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  44%|████▎     | 610/1400 [1:06:04<1:29:23,  6.79s/it]

[14/Apr/2026 19:12:32] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  44%|████▎     | 611/1400 [1:06:09<1:22:46,  6.29s/it]

[14/Apr/2026 19:12:39] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  44%|████▎     | 612/1400 [1:06:16<1:25:07,  6.48s/it]

[14/Apr/2026 19:12:46] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  44%|████▍     | 613/1400 [1:06:22<1:24:02,  6.41s/it]

[14/Apr/2026 19:12:53] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  44%|████▍     | 614/1400 [1:06:29<1:26:19,  6.59s/it]

[14/Apr/2026 19:12:58] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  44%|████▍     | 615/1400 [1:06:34<1:20:51,  6.18s/it]

[14/Apr/2026 19:13:03] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  44%|████▍     | 616/1400 [1:06:40<1:18:26,  6.00s/it]

[14/Apr/2026 19:13:10] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  44%|████▍     | 617/1400 [1:06:46<1:18:39,  6.03s/it]

[14/Apr/2026 19:13:15] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  44%|████▍     | 618/1400 [1:06:52<1:17:38,  5.96s/it]

[14/Apr/2026 19:13:20] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  44%|████▍     | 619/1400 [1:06:57<1:13:55,  5.68s/it]

[14/Apr/2026 19:13:27] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  44%|████▍     | 620/1400 [1:07:03<1:17:55,  5.99s/it]

[14/Apr/2026 19:13:33] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  44%|████▍     | 621/1400 [1:07:09<1:17:46,  5.99s/it]

[14/Apr/2026 19:13:38] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  44%|████▍     | 622/1400 [1:07:15<1:14:59,  5.78s/it]

[14/Apr/2026 19:13:43] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  44%|████▍     | 623/1400 [1:07:20<1:12:20,  5.59s/it]

[14/Apr/2026 19:13:49] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  45%|████▍     | 624/1400 [1:07:25<1:10:18,  5.44s/it]

[14/Apr/2026 19:13:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  45%|████▍     | 625/1400 [1:07:30<1:09:35,  5.39s/it]

[14/Apr/2026 19:13:59] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  45%|████▍     | 626/1400 [1:07:36<1:10:19,  5.45s/it]

[14/Apr/2026 19:14:05] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  45%|████▍     | 627/1400 [1:07:41<1:10:23,  5.46s/it]

[14/Apr/2026 19:14:11] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  45%|████▍     | 628/1400 [1:07:47<1:13:05,  5.68s/it]

[14/Apr/2026 19:14:17] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  45%|████▍     | 629/1400 [1:07:53<1:12:49,  5.67s/it]

[14/Apr/2026 19:14:21] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  45%|████▌     | 630/1400 [1:07:58<1:08:57,  5.37s/it]

[14/Apr/2026 19:14:33] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  45%|████▌     | 631/1400 [1:08:09<1:31:17,  7.12s/it]

[14/Apr/2026 19:14:38] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  45%|████▌     | 632/1400 [1:08:14<1:24:34,  6.61s/it]

[14/Apr/2026 19:14:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  45%|████▌     | 633/1400 [1:08:21<1:22:46,  6.47s/it]

[14/Apr/2026 19:14:50] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  45%|████▌     | 634/1400 [1:08:27<1:21:18,  6.37s/it]

[14/Apr/2026 19:14:56] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  45%|████▌     | 635/1400 [1:08:32<1:17:35,  6.09s/it]

[14/Apr/2026 19:15:01] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  45%|████▌     | 636/1400 [1:08:37<1:14:48,  5.88s/it]

[14/Apr/2026 19:15:07] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  46%|████▌     | 637/1400 [1:08:43<1:12:51,  5.73s/it]

[14/Apr/2026 19:15:13] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  46%|████▌     | 638/1400 [1:08:49<1:14:26,  5.86s/it]

[14/Apr/2026 19:15:18] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  46%|████▌     | 639/1400 [1:08:55<1:13:40,  5.81s/it]

[14/Apr/2026 19:15:25] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  46%|████▌     | 640/1400 [1:09:01<1:16:15,  6.02s/it]

[14/Apr/2026 19:15:32] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  46%|████▌     | 641/1400 [1:09:08<1:20:08,  6.34s/it]

[14/Apr/2026 19:15:38] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  46%|████▌     | 642/1400 [1:09:15<1:20:09,  6.35s/it]

[14/Apr/2026 19:15:48] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  46%|████▌     | 643/1400 [1:09:24<1:32:33,  7.34s/it]

[14/Apr/2026 19:15:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  46%|████▌     | 644/1400 [1:09:30<1:26:49,  6.89s/it]

[14/Apr/2026 19:15:59] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  46%|████▌     | 645/1400 [1:09:36<1:21:52,  6.51s/it]

[14/Apr/2026 19:16:06] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  46%|████▌     | 646/1400 [1:09:42<1:20:24,  6.40s/it]

[14/Apr/2026 19:16:12] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  46%|████▌     | 647/1400 [1:09:48<1:19:11,  6.31s/it]

[14/Apr/2026 19:16:19] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  46%|████▋     | 648/1400 [1:09:55<1:22:28,  6.58s/it]

[14/Apr/2026 19:16:25] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  46%|████▋     | 649/1400 [1:10:02<1:22:10,  6.56s/it]

[14/Apr/2026 19:16:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[14/Apr/2026 19:16:34] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row649_20260414_191634.csv (650 строк)
[14/Apr/2026 19:16:34] INFO - Удалён старый чекпоинт: checkpoints/checkpoint_row499_20260414_190044.csv

Analyzing:  46%|████▋     | 650/1400 [1:10:10<1:28:45,  7.10s/it]

📌 Чекпоинт [650/1400] → checkpoints/checkpoint_row649_20260414_191634.csv
[14/Apr/2026 19:16:41] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  46%|████▋     | 651/1400 [1:10:17<1:28:11,  7.06s/it]

[14/Apr/2026 19:16:49] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  47%|████▋     | 652/1400 [1:10:25<1:32:28,  7.42s/it]

[14/Apr/2026 19:16:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  47%|████▋     | 653/1400 [1:10:31<1:24:26,  6.78s/it]

[14/Apr/2026 19:17:00] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  47%|████▋     | 654/1400 [1:10:36<1:19:38,  6.41s/it]

[14/Apr/2026 19:17:06] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  47%|████▋     | 655/1400 [1:10:42<1:16:59,  6.20s/it]

[14/Apr/2026 19:17:11] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  47%|████▋     | 656/1400 [1:10:47<1:12:56,  5.88s/it]

[14/Apr/2026 19:17:16] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  47%|████▋     | 657/1400 [1:10:53<1:11:27,  5.77s/it]

[14/Apr/2026 19:17:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  47%|████▋     | 658/1400 [1:10:58<1:11:13,  5.76s/it]

[14/Apr/2026 19:17:29] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  47%|████▋     | 659/1400 [1:11:05<1:15:41,  6.13s/it]

[14/Apr/2026 19:17:39] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  47%|████▋     | 660/1400 [1:11:16<1:31:03,  7.38s/it]

[14/Apr/2026 19:17:45] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  47%|████▋     | 661/1400 [1:11:21<1:23:20,  6.77s/it]

[14/Apr/2026 19:17:49] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  47%|████▋     | 662/1400 [1:11:26<1:16:15,  6.20s/it]

[14/Apr/2026 19:17:55] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  47%|████▋     | 663/1400 [1:11:31<1:12:18,  5.89s/it]

[14/Apr/2026 19:18:00] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  47%|████▋     | 664/1400 [1:11:36<1:09:54,  5.70s/it]

[14/Apr/2026 19:18:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  48%|████▊     | 665/1400 [1:11:44<1:17:06,  6.29s/it]

[14/Apr/2026 19:18:15] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  48%|████▊     | 666/1400 [1:11:52<1:22:42,  6.76s/it]

[14/Apr/2026 19:18:25] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  48%|████▊     | 667/1400 [1:12:01<1:32:09,  7.54s/it]

[14/Apr/2026 19:18:31] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  48%|████▊     | 668/1400 [1:12:07<1:26:58,  7.13s/it]

[14/Apr/2026 19:18:36] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  48%|████▊     | 669/1400 [1:12:13<1:20:53,  6.64s/it]

[14/Apr/2026 19:18:42] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  48%|████▊     | 670/1400 [1:12:18<1:17:00,  6.33s/it]

[14/Apr/2026 19:18:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  48%|████▊     | 671/1400 [1:12:28<1:28:04,  7.25s/it]

[14/Apr/2026 19:18:57] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  48%|████▊     | 672/1400 [1:12:33<1:21:35,  6.72s/it]

[14/Apr/2026 19:19:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  48%|████▊     | 673/1400 [1:12:39<1:16:55,  6.35s/it]

[14/Apr/2026 19:19:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  48%|████▊     | 674/1400 [1:12:44<1:13:13,  6.05s/it]

[14/Apr/2026 19:19:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  48%|████▊     | 675/1400 [1:12:50<1:13:12,  6.06s/it]

[14/Apr/2026 19:19:19] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  48%|████▊     | 676/1400 [1:12:55<1:10:07,  5.81s/it]

[14/Apr/2026 19:19:26] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  48%|████▊     | 677/1400 [1:13:03<1:15:30,  6.27s/it]

[14/Apr/2026 19:19:33] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  48%|████▊     | 678/1400 [1:13:09<1:16:15,  6.34s/it]

[14/Apr/2026 19:19:38] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  48%|████▊     | 679/1400 [1:13:15<1:13:18,  6.10s/it]

[14/Apr/2026 19:19:43] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  49%|████▊     | 680/1400 [1:13:20<1:08:26,  5.70s/it]

[14/Apr/2026 19:19:49] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  49%|████▊     | 681/1400 [1:13:25<1:08:06,  5.68s/it]

[14/Apr/2026 19:19:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  49%|████▊     | 682/1400 [1:13:31<1:07:39,  5.65s/it]

[14/Apr/2026 19:20:00] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  49%|████▉     | 683/1400 [1:13:36<1:07:31,  5.65s/it]

[14/Apr/2026 19:20:05] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  49%|████▉     | 684/1400 [1:13:41<1:05:04,  5.45s/it]

[14/Apr/2026 19:20:11] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  49%|████▉     | 685/1400 [1:13:48<1:07:43,  5.68s/it]

[14/Apr/2026 19:20:17] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  49%|████▉     | 686/1400 [1:13:53<1:07:15,  5.65s/it]

[14/Apr/2026 19:20:23] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  49%|████▉     | 687/1400 [1:14:00<1:09:47,  5.87s/it]

[14/Apr/2026 19:20:30] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  49%|████▉     | 688/1400 [1:14:06<1:13:12,  6.17s/it]

[14/Apr/2026 19:20:36] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  49%|████▉     | 689/1400 [1:14:12<1:10:59,  5.99s/it]

[14/Apr/2026 19:20:42] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  49%|████▉     | 690/1400 [1:14:18<1:12:13,  6.10s/it]

[14/Apr/2026 19:20:48] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  49%|████▉     | 691/1400 [1:14:24<1:10:16,  5.95s/it]

[14/Apr/2026 19:20:52] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  49%|████▉     | 692/1400 [1:14:29<1:05:58,  5.59s/it]

[14/Apr/2026 19:20:59] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  50%|████▉     | 693/1400 [1:14:35<1:08:01,  5.77s/it]

[14/Apr/2026 19:21:05] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  50%|████▉     | 694/1400 [1:14:41<1:09:23,  5.90s/it]

[14/Apr/2026 19:21:10] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  50%|████▉     | 695/1400 [1:14:47<1:08:29,  5.83s/it]

[14/Apr/2026 19:21:18] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  50%|████▉     | 696/1400 [1:14:54<1:13:18,  6.25s/it]

[14/Apr/2026 19:21:23] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  50%|████▉     | 697/1400 [1:14:59<1:09:43,  5.95s/it]

[14/Apr/2026 19:21:29] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  50%|████▉     | 698/1400 [1:15:05<1:08:07,  5.82s/it]

[14/Apr/2026 19:21:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  50%|████▉     | 699/1400 [1:15:10<1:06:58,  5.73s/it]

[14/Apr/2026 19:21:42] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[14/Apr/2026 19:21:42] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row699_20260414_192142.csv (700 строк)
[14/Apr/2026 19:21:42] INFO - Удалён старый чекпоинт: checkpoints/checkpoint_row549_20260414_190611.csv

Analyzing:  50%|█████     | 700/1400 [1:15:18<1:14:05,  6.35s/it]

📌 Чекпоинт [700/1400] → checkpoints/checkpoint_row699_20260414_192142.csv
[14/Apr/2026 19:21:42] WARNING - Row 700 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:21:42] WARNING - Row 701 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:21:42] WARNING - Row 702 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:21:42] WARNING - Row 703 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:21:42] WARNING - Row 704 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:21:42] WARNING - Row 705 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:21:48] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  50%|█████     | 707/1400 [1:15:24<26:11,  2.27s/it]

[14/Apr/2026 19:21:48] WARNING - Row 707 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:21:48] WARNING - Row 708 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:21:48] WARNING - Row 709 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:21:55] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  51%|█████     | 711/1400 [1:15:31<23:34,  2.05s/it]

[14/Apr/2026 19:22:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  51%|█████     | 712/1400 [1:15:39<30:38,  2.67s/it]

[14/Apr/2026 19:22:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  51%|█████     | 713/1400 [1:15:44<35:10,  3.07s/it]

[14/Apr/2026 19:22:08] WARNING - Row 713 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:15] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  51%|█████     | 715/1400 [1:15:52<37:48,  3.31s/it]

[14/Apr/2026 19:22:15] WARNING - Row 715 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:15] WARNING - Row 716 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:15] WARNING - Row 717 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:15] WARNING - Row 718 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:24] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  51%|█████▏    | 720/1400 [1:16:01<28:32,  2.52s/it]

[14/Apr/2026 19:22:24] WARNING - Row 720 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:33] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  52%|█████▏    | 722/1400 [1:16:09<32:58,  2.92s/it]

[14/Apr/2026 19:22:33] WARNING - Row 722 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:39] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  52%|█████▏    | 724/1400 [1:16:15<33:01,  2.93s/it]

[14/Apr/2026 19:22:39] WARNING - Row 724 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:39] WARNING - Row 725 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:39] WARNING - Row 726 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:39] WARNING - Row 727 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:39] WARNING - Row 728 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:39] WARNING - Row 729 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  52%|█████▏    | 731/1400 [1:16:20<19:13,  1.72s/it]

[14/Apr/2026 19:22:44] WARNING - Row 731 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:44] WARNING - Row 732 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:44] WARNING - Row 733 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:44] WARNING - Row 734 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:44] WARNING - Row 735 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:49] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  53%|█████▎    | 737/1400 [1:16:25<15:04,  1.36s/it]

[14/Apr/2026 19:22:49] WARNING - Row 737 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:49] WARNING - Row 738 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:49] WARNING - Row 739 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:49] WARNING - Row 740 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:49] WARNING - Row 741 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:49] WARNING - Row 742 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:49] WARNING - Row 743 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:49] WARNING - Row 744 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:49] WARNING - Row 745 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:49] WARNING - Row 746 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:49] WARNING - Row 747 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  54%|█████▎    | 749/1400 [1:16:30<09:25,  1.15it/s]

[14/Apr/2026 19:22:54] WARNING - Row 749 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:22:54] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row749_20260414_192254.csv (750 строк)
[14/Apr/2026 19:22:54] INFO - Удалён старый чекпоинт: checkpoints/checkpoint_row599_20260414_191116.csv

Analyzing:  54%|█████▎    | 750/1400 [1:16:31<09:00,  1.20it/s]

📌 Чекпоинт [750/1400] → checkpoints/checkpoint_row749_20260414_192254.csv
[14/Apr/2026 19:23:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  54%|█████▎    | 751/1400 [1:16:38<14:22,  1.33s/it]

[14/Apr/2026 19:23:07] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  54%|█████▎    | 752/1400 [1:16:43<19:01,  1.76s/it]

[14/Apr/2026 19:23:12] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  54%|█████▍    | 753/1400 [1:16:49<23:49,  2.21s/it]

[14/Apr/2026 19:23:18] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  54%|█████▍    | 754/1400 [1:16:55<30:01,  2.79s/it]

[14/Apr/2026 19:23:18] WARNING - Row 754 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:23:18] WARNING - Row 755 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:23:24] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  54%|█████▍    | 757/1400 [1:17:01<26:13,  2.45s/it]

[14/Apr/2026 19:23:24] WARNING - Row 757 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:23:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  54%|█████▍    | 759/1400 [1:17:10<32:51,  3.08s/it]

[14/Apr/2026 19:23:34] WARNING - Row 759 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:23:34] WARNING - Row 760 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:23:34] WARNING - Row 761 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:23:40] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  55%|█████▍    | 763/1400 [1:17:16<25:08,  2.37s/it]

[14/Apr/2026 19:23:45] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  55%|█████▍    | 764/1400 [1:17:21<29:31,  2.79s/it]

[14/Apr/2026 19:23:45] WARNING - Row 764 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:23:50] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  55%|█████▍    | 766/1400 [1:17:26<28:47,  2.73s/it]

[14/Apr/2026 19:23:50] WARNING - Row 766 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:23:50] WARNING - Row 767 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:23:50] WARNING - Row 768 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:23:58] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  55%|█████▌    | 770/1400 [1:17:34<24:44,  2.36s/it]

[14/Apr/2026 19:24:06] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  55%|█████▌    | 771/1400 [1:17:42<32:47,  3.13s/it]

[14/Apr/2026 19:24:06] WARNING - Row 771 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:24:06] WARNING - Row 772 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:24:06] WARNING - Row 773 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:24:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  55%|█████▌    | 775/1400 [1:17:50<27:26,  2.63s/it]

[14/Apr/2026 19:24:14] WARNING - Row 775 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:24:14] WARNING - Row 776 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:24:20] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  56%|█████▌    | 778/1400 [1:17:56<25:18,  2.44s/it]

[14/Apr/2026 19:24:25] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  56%|█████▌    | 779/1400 [1:18:02<29:22,  2.84s/it]

[14/Apr/2026 19:24:25] WARNING - Row 779 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:24:25] WARNING - Row 780 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:24:31] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  56%|█████▌    | 782/1400 [1:18:08<26:13,  2.55s/it]

[14/Apr/2026 19:24:31] WARNING - Row 782 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:24:38] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  56%|█████▌    | 784/1400 [1:18:15<28:31,  2.78s/it]

[14/Apr/2026 19:24:38] WARNING - Row 784 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:24:38] WARNING - Row 785 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:24:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  56%|█████▌    | 787/1400 [1:18:20<25:27,  2.49s/it]

[14/Apr/2026 19:24:44] WARNING - Row 787 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:24:44] WARNING - Row 788 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:24:44] WARNING - Row 789 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:24:50] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  56%|█████▋    | 791/1400 [1:18:26<20:55,  2.06s/it]

[14/Apr/2026 19:24:56] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  57%|█████▋    | 792/1400 [1:18:33<26:36,  2.63s/it]

[14/Apr/2026 19:24:56] WARNING - Row 792 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:24:56] WARNING - Row 793 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:24:56] WARNING - Row 794 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:24:56] WARNING - Row 795 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:24:56] WARNING - Row 796 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:25:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  57%|█████▋    | 798/1400 [1:18:38<17:37,  1.76s/it]

[14/Apr/2026 19:25:02] WARNING - Row 798 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:25:02] WARNING - Row 799 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:25:02] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row799_20260414_192502.csv (800 строк)
[14/Apr/2026 19:25:02] INFO - Удалён старый чекпоинт: checkpoints/checkpoint_row649_20260414_191634.csv

Analyzing:  57%|█████▋    | 800/1400 [1:18:39<14:21,  1.44s/it]

📌 Чекпоинт [800/1400] → checkpoints/checkpoint_row799_20260414_192502.csv
[14/Apr/2026 19:25:02] WARNING - Row 800 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:25:09] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  57%|█████▋    | 802/1400 [1:18:45<18:08,  1.82s/it]

[14/Apr/2026 19:25:09] WARNING - Row 802 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:25:09] WARNING - Row 803 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:25:09] WARNING - Row 804 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:25:09] WARNING - Row 805 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:25:15] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  58%|█████▊    | 807/1400 [1:18:51<15:08,  1.53s/it]

[14/Apr/2026 19:25:15] WARNING - Row 807 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:25:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  58%|█████▊    | 809/1400 [1:18:59<19:46,  2.01s/it]

[14/Apr/2026 19:25:22] WARNING - Row 809 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:25:29] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  58%|█████▊    | 811/1400 [1:19:05<22:28,  2.29s/it]

[14/Apr/2026 19:25:29] WARNING - Row 811 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:25:29] WARNING - Row 812 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:25:29] WARNING - Row 813 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:25:36] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  58%|█████▊    | 815/1400 [1:19:12<20:20,  2.09s/it]

[14/Apr/2026 19:25:36] WARNING - Row 815 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:25:36] WARNING - Row 816 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:25:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  58%|█████▊    | 818/1400 [1:19:20<21:48,  2.25s/it]

[14/Apr/2026 19:25:44] WARNING - Row 818 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:25:44] WARNING - Row 819 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:25:44] WARNING - Row 820 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:25:44] WARNING - Row 821 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:25:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  59%|█████▉    | 823/1400 [1:19:27<18:25,  1.92s/it]

[14/Apr/2026 19:25:58] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  59%|█████▉    | 824/1400 [1:19:34<23:33,  2.45s/it]

[14/Apr/2026 19:25:58] WARNING - Row 824 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:25:58] WARNING - Row 825 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:26:03] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  59%|█████▉    | 827/1400 [1:19:40<21:18,  2.23s/it]

[14/Apr/2026 19:26:03] WARNING - Row 827 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:26:03] WARNING - Row 828 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:26:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  59%|█████▉    | 830/1400 [1:19:50<25:09,  2.65s/it]

[14/Apr/2026 19:26:21] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  59%|█████▉    | 831/1400 [1:19:57<30:11,  3.18s/it]

[14/Apr/2026 19:26:21] WARNING - Row 831 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:26:21] WARNING - Row 832 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:26:21] WARNING - Row 833 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:26:27] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  60%|█████▉    | 835/1400 [1:20:04<23:49,  2.53s/it]

[14/Apr/2026 19:26:27] WARNING - Row 835 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:26:27] WARNING - Row 836 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:26:27] WARNING - Row 837 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:26:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  60%|█████▉    | 839/1400 [1:20:10<20:27,  2.19s/it]

[14/Apr/2026 19:26:34] WARNING - Row 839 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:26:41] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  60%|██████    | 841/1400 [1:20:17<22:56,  2.46s/it]

[14/Apr/2026 19:26:48] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  60%|██████    | 842/1400 [1:20:25<28:53,  3.11s/it]

[14/Apr/2026 19:26:48] WARNING - Row 842 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:26:48] WARNING - Row 843 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:26:48] WARNING - Row 844 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:26:48] WARNING - Row 845 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:26:48] WARNING - Row 846 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:26:48] WARNING - Row 847 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:26:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  61%|██████    | 849/1400 [1:20:31<16:51,  1.84s/it]

[14/Apr/2026 19:27:01] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[14/Apr/2026 19:27:01] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row849_20260414_192701.csv (850 строк)
[14/Apr/2026 19:27:01] INFO - Удалён старый чекпоинт: checkpoints/checkpoint_row699_20260414_192142.csv

Analyzing:  61%|██████    | 850/1400 [1:20:37<21:25,  2.34s/it]

📌 Чекпоинт [850/1400] → checkpoints/checkpoint_row849_20260414_192701.csv
[14/Apr/2026 19:27:07] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  61%|██████    | 851/1400 [1:20:43<25:30,  2.79s/it]

[14/Apr/2026 19:27:07] WARNING - Row 851 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:27:13] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  61%|██████    | 853/1400 [1:20:49<25:50,  2.83s/it]

[14/Apr/2026 19:27:13] WARNING - Row 853 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:27:19] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  61%|██████    | 855/1400 [1:20:56<27:00,  2.97s/it]

[14/Apr/2026 19:27:19] WARNING - Row 855 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:27:19] WARNING - Row 856 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:27:19] WARNING - Row 857 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:27:26] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  61%|██████▏   | 859/1400 [1:21:02<21:19,  2.37s/it]

[14/Apr/2026 19:27:26] WARNING - Row 859 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:27:26] WARNING - Row 860 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:27:26] WARNING - Row 861 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:27:26] WARNING - Row 862 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:27:26] WARNING - Row 863 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:27:26] WARNING - Row 864 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:27:31] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  62%|██████▏   | 866/1400 [1:21:07<13:31,  1.52s/it]

[14/Apr/2026 19:27:37] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  62%|██████▏   | 867/1400 [1:21:13<17:10,  1.93s/it]

[14/Apr/2026 19:27:37] WARNING - Row 867 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:27:43] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  62%|██████▏   | 869/1400 [1:21:19<18:55,  2.14s/it]

[14/Apr/2026 19:27:48] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  62%|██████▏   | 870/1400 [1:21:25<23:05,  2.61s/it]

[14/Apr/2026 19:27:48] WARNING - Row 870 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:27:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  62%|██████▏   | 872/1400 [1:21:31<23:57,  2.72s/it]

[14/Apr/2026 19:28:01] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  62%|██████▏   | 873/1400 [1:21:37<29:14,  3.33s/it]

[14/Apr/2026 19:28:07] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  62%|██████▏   | 874/1400 [1:21:43<33:42,  3.85s/it]

[14/Apr/2026 19:28:07] WARNING - Row 874 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:28:07] WARNING - Row 875 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:28:07] WARNING - Row 876 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:28:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  63%|██████▎   | 878/1400 [1:21:50<24:15,  2.79s/it]

[14/Apr/2026 19:28:25] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  63%|██████▎   | 879/1400 [1:22:02<35:34,  4.10s/it]

[14/Apr/2026 19:28:25] WARNING - Row 879 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:28:25] WARNING - Row 880 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:28:31] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  63%|██████▎   | 882/1400 [1:22:08<28:18,  3.28s/it]

[14/Apr/2026 19:28:37] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  63%|██████▎   | 883/1400 [1:22:14<31:47,  3.69s/it]

[14/Apr/2026 19:28:37] WARNING - Row 883 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:28:43] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  63%|██████▎   | 885/1400 [1:22:20<29:54,  3.49s/it]

[14/Apr/2026 19:28:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  63%|██████▎   | 886/1400 [1:22:27<35:50,  4.18s/it]

[14/Apr/2026 19:28:58] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  63%|██████▎   | 887/1400 [1:22:34<40:57,  4.79s/it]

[14/Apr/2026 19:29:05] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  63%|██████▎   | 888/1400 [1:22:42<46:23,  5.44s/it]

[14/Apr/2026 19:29:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  64%|██████▎   | 889/1400 [1:22:50<52:32,  6.17s/it]

[14/Apr/2026 19:29:21] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  64%|██████▎   | 890/1400 [1:22:57<54:32,  6.42s/it]

[14/Apr/2026 19:29:21] WARNING - Row 890 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:29:21] WARNING - Row 891 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:29:29] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  64%|██████▍   | 893/1400 [1:23:05<37:01,  4.38s/it]

[14/Apr/2026 19:29:35] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  64%|██████▍   | 894/1400 [1:23:11<39:41,  4.71s/it]

[14/Apr/2026 19:29:42] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  64%|██████▍   | 895/1400 [1:23:18<44:27,  5.28s/it]

[14/Apr/2026 19:29:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  64%|██████▍   | 896/1400 [1:23:27<51:20,  6.11s/it]

[14/Apr/2026 19:29:51] WARNING - Row 896 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:29:51] WARNING - Row 897 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:29:51] WARNING - Row 898 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:29:57] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[14/Apr/2026 19:29:58] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row899_20260414_192957.csv (900 строк)
[14/Apr/2026 19:29:58] INFO - Удалён старый чекпоинт: checkpoints/checkpoint_row749_20260414_192254.csv

Analyzing:  64%|██████▍   | 900/1400 [1:23:34<29:56,  3.59s/it]

📌 Чекпоинт [900/1400] → checkpoints/checkpoint_row899_20260414_192957.csv
[14/Apr/2026 19:29:58] WARNING - Row 900 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:29:58] WARNING - Row 901 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:29:58] WARNING - Row 902 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:29:58] WARNING - Row 903 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:30:05] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  65%|██████▍   | 905/1400 [1:23:42<21:01,  2.55s/it]

[14/Apr/2026 19:30:12] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  65%|██████▍   | 906/1400 [1:23:49<25:49,  3.14s/it]

[14/Apr/2026 19:30:20] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  65%|██████▍   | 907/1400 [1:23:56<30:55,  3.76s/it]

[14/Apr/2026 19:30:20] WARNING - Row 907 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:30:20] WARNING - Row 908 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:30:20] WARNING - Row 909 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:30:20] WARNING - Row 910 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:30:20] WARNING - Row 911 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:30:26] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  65%|██████▌   | 913/1400 [1:24:02<17:45,  2.19s/it]

[14/Apr/2026 19:30:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  65%|██████▌   | 914/1400 [1:24:10<23:19,  2.88s/it]

[14/Apr/2026 19:30:42] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  65%|██████▌   | 915/1400 [1:24:18<29:25,  3.64s/it]

[14/Apr/2026 19:30:42] WARNING - Row 915 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:30:42] WARNING - Row 916 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:30:42] WARNING - Row 917 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:30:48] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  66%|██████▌   | 919/1400 [1:24:24<21:42,  2.71s/it]

[14/Apr/2026 19:30:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  66%|██████▌   | 920/1400 [1:24:30<25:23,  3.17s/it]

[14/Apr/2026 19:31:00] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  66%|██████▌   | 921/1400 [1:24:36<28:35,  3.58s/it]

[14/Apr/2026 19:31:05] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  66%|██████▌   | 922/1400 [1:24:42<31:41,  3.98s/it]

[14/Apr/2026 19:31:05] WARNING - Row 922 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:31:05] WARNING - Row 923 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:31:05] WARNING - Row 924 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:31:05] WARNING - Row 925 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:31:12] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  66%|██████▌   | 927/1400 [1:24:49<19:35,  2.48s/it]

[14/Apr/2026 19:31:12] WARNING - Row 927 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:31:12] WARNING - Row 928 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:31:20] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  66%|██████▋   | 930/1400 [1:24:57<19:52,  2.54s/it]

[14/Apr/2026 19:31:25] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  66%|██████▋   | 931/1400 [1:25:02<22:30,  2.88s/it]

[14/Apr/2026 19:31:25] WARNING - Row 931 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:31:25] WARNING - Row 932 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:31:25] WARNING - Row 933 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:31:25] WARNING - Row 934 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:31:31] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  67%|██████▋   | 936/1400 [1:25:07<15:33,  2.01s/it]

[14/Apr/2026 19:31:39] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  67%|██████▋   | 937/1400 [1:25:16<21:32,  2.79s/it]

[14/Apr/2026 19:31:46] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  67%|██████▋   | 938/1400 [1:25:23<26:29,  3.44s/it]

[14/Apr/2026 19:31:46] WARNING - Row 938 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:31:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  67%|██████▋   | 940/1400 [1:25:28<24:15,  3.16s/it]

[14/Apr/2026 19:31:51] WARNING - Row 940 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:32:01] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  67%|██████▋   | 942/1400 [1:25:37<27:57,  3.66s/it]

[14/Apr/2026 19:32:01] WARNING - Row 942 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:32:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  67%|██████▋   | 944/1400 [1:25:45<27:48,  3.66s/it]

[14/Apr/2026 19:32:17] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  68%|██████▊   | 945/1400 [1:25:53<33:53,  4.47s/it]

[14/Apr/2026 19:32:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  68%|██████▊   | 946/1400 [1:25:58<35:00,  4.63s/it]

[14/Apr/2026 19:32:27] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  68%|██████▊   | 947/1400 [1:26:04<36:14,  4.80s/it]

[14/Apr/2026 19:32:27] WARNING - Row 947 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:32:27] WARNING - Row 948 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:32:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[14/Apr/2026 19:32:34] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row949_20260414_193234.csv (950 строк)
[14/Apr/2026 19:32:34] INFO - Удалён старый чекпоинт: checkpoints/checkpoint_row799_20260414_192502.csv

Analyzing:  68%|██████▊   | 950/1400 [1:26:10<26:41,  3.56s/it]

📌 Чекпоинт [950/1400] → checkpoints/checkpoint_row949_20260414_193234.csv
[14/Apr/2026 19:32:34] WARNING - Row 950 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:32:40] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  68%|██████▊   | 952/1400 [1:26:16<24:52,  3.33s/it]

[14/Apr/2026 19:32:40] WARNING - Row 952 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:32:40] WARNING - Row 953 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:32:46] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  68%|██████▊   | 955/1400 [1:26:22<20:25,  2.75s/it]

[14/Apr/2026 19:32:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  68%|██████▊   | 956/1400 [1:26:27<23:52,  3.23s/it]

[14/Apr/2026 19:32:51] WARNING - Row 956 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:32:51] WARNING - Row 957 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:32:58] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  68%|██████▊   | 959/1400 [1:26:34<20:48,  2.83s/it]

[14/Apr/2026 19:32:58] WARNING - Row 959 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:33:04] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  69%|██████▊   | 961/1400 [1:26:40<20:56,  2.86s/it]

[14/Apr/2026 19:33:04] WARNING - Row 961 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:33:04] WARNING - Row 962 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:33:04] WARNING - Row 963 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:33:10] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  69%|██████▉   | 965/1400 [1:26:46<16:34,  2.29s/it]

[14/Apr/2026 19:33:17] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  69%|██████▉   | 966/1400 [1:26:54<21:34,  2.98s/it]

[14/Apr/2026 19:33:23] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  69%|██████▉   | 967/1400 [1:26:59<24:11,  3.35s/it]

[14/Apr/2026 19:33:29] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  69%|██████▉   | 968/1400 [1:27:05<28:10,  3.91s/it]

[14/Apr/2026 19:33:35] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  69%|██████▉   | 969/1400 [1:27:11<31:06,  4.33s/it]

[14/Apr/2026 19:33:42] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  69%|██████▉   | 970/1400 [1:27:19<36:06,  5.04s/it]

[14/Apr/2026 19:33:42] WARNING - Row 970 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:33:47] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  69%|██████▉   | 972/1400 [1:27:23<28:13,  3.96s/it]

[14/Apr/2026 19:33:47] WARNING - Row 972 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:33:47] WARNING - Row 973 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:33:47] WARNING - Row 974 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:33:47] WARNING - Row 975 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:33:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  70%|██████▉   | 977/1400 [1:27:30<17:12,  2.44s/it]

[14/Apr/2026 19:33:54] WARNING - Row 977 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:33:54] WARNING - Row 978 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:34:00] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  70%|███████   | 980/1400 [1:27:36<15:58,  2.28s/it]

[14/Apr/2026 19:34:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  70%|███████   | 981/1400 [1:27:44<21:14,  3.04s/it]

[14/Apr/2026 19:34:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  70%|███████   | 982/1400 [1:27:50<24:47,  3.56s/it]

[14/Apr/2026 19:34:14] WARNING - Row 982 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:34:14] WARNING - Row 983 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:34:19] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  70%|███████   | 985/1400 [1:27:56<19:38,  2.84s/it]

[14/Apr/2026 19:34:25] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  70%|███████   | 986/1400 [1:28:02<23:16,  3.37s/it]

[14/Apr/2026 19:34:33] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  70%|███████   | 987/1400 [1:28:09<28:21,  4.12s/it]

[14/Apr/2026 19:34:33] WARNING - Row 987 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:34:33] WARNING - Row 988 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:34:33] WARNING - Row 989 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:34:33] WARNING - Row 990 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:34:33] WARNING - Row 991 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:34:33] WARNING - Row 992 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:34:33] WARNING - Row 993 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:34:43] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  71%|███████   | 995/1400 [1:28:20<14:55,  2.21s/it]

[14/Apr/2026 19:34:49] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  71%|███████   | 996/1400 [1:28:25<17:31,  2.60s/it]

[14/Apr/2026 19:34:56] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  71%|███████   | 997/1400 [1:28:32<21:19,  3.17s/it]

[14/Apr/2026 19:34:56] WARNING - Row 997 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:34:56] WARNING - Row 998 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:35:01] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[14/Apr/2026 19:35:02] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row999_20260414_193501.csv (1000 строк)
[14/Apr/2026 19:35:02] INFO - Удалён старый чекпоинт: checkpoints/checkpoint_row849_20260414_192701.csv

Analyzing:  71%|███████▏  | 1000/1400 [1:28:38<18:14,  2.74s/it]

📌 Чекпоинт [1000/1400] → checkpoints/checkpoint_row999_20260414_193501.csv
[14/Apr/2026 19:35:02] WARNING - Row 1000 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:35:02] WARNING - Row 1001 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:35:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  72%|███████▏  | 1003/1400 [1:28:45<16:43,  2.53s/it]

[14/Apr/2026 19:35:08] WARNING - Row 1003 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:35:08] WARNING - Row 1004 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:35:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  72%|███████▏  | 1006/1400 [1:28:50<15:11,  2.31s/it]

[14/Apr/2026 19:35:14] WARNING - Row 1006 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:35:14] WARNING - Row 1007 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:35:20] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  72%|███████▏  | 1009/1400 [1:28:56<14:12,  2.18s/it]

[14/Apr/2026 19:35:20] WARNING - Row 1009 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:35:26] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  72%|███████▏  | 1011/1400 [1:29:02<15:34,  2.40s/it]

[14/Apr/2026 19:35:31] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  72%|███████▏  | 1012/1400 [1:29:08<18:22,  2.84s/it]

[14/Apr/2026 19:35:31] WARNING - Row 1012 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:35:31] WARNING - Row 1013 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:35:31] WARNING - Row 1014 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:35:31] WARNING - Row 1015 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:35:31] WARNING - Row 1016 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:35:38] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  73%|███████▎  | 1018/1400 [1:29:14<11:47,  1.85s/it]

[14/Apr/2026 19:35:38] WARNING - Row 1018 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:35:38] WARNING - Row 1019 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:35:45] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  73%|███████▎  | 1021/1400 [1:29:21<12:41,  2.01s/it]

[14/Apr/2026 19:35:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  73%|███████▎  | 1022/1400 [1:29:27<15:56,  2.53s/it]

[14/Apr/2026 19:35:51] WARNING - Row 1022 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:35:51] WARNING - Row 1023 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:35:58] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  73%|███████▎  | 1025/1400 [1:29:34<15:11,  2.43s/it]

[14/Apr/2026 19:35:58] WARNING - Row 1025 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:35:58] WARNING - Row 1026 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:36:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  73%|███████▎  | 1028/1400 [1:29:44<16:49,  2.71s/it]

[14/Apr/2026 19:36:16] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  74%|███████▎  | 1029/1400 [1:29:52<21:18,  3.45s/it]

[14/Apr/2026 19:36:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  74%|███████▎  | 1030/1400 [1:29:58<23:28,  3.81s/it]

[14/Apr/2026 19:36:28] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  74%|███████▎  | 1031/1400 [1:30:04<26:06,  4.25s/it]

[14/Apr/2026 19:36:33] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  74%|███████▎  | 1032/1400 [1:30:10<27:47,  4.53s/it]

[14/Apr/2026 19:36:41] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  74%|███████▍  | 1033/1400 [1:30:17<31:33,  5.16s/it]

[14/Apr/2026 19:36:46] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  74%|███████▍  | 1034/1400 [1:30:22<31:52,  5.23s/it]

[14/Apr/2026 19:36:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  74%|███████▍  | 1035/1400 [1:30:31<36:45,  6.04s/it]

[14/Apr/2026 19:36:54] WARNING - Row 1035 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:36:54] WARNING - Row 1036 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:37:00] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  74%|███████▍  | 1038/1400 [1:30:36<22:44,  3.77s/it]

[14/Apr/2026 19:37:05] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  74%|███████▍  | 1039/1400 [1:30:41<24:41,  4.10s/it]

[14/Apr/2026 19:37:11] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  74%|███████▍  | 1040/1400 [1:30:47<26:57,  4.49s/it]

[14/Apr/2026 19:37:11] WARNING - Row 1040 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:37:11] WARNING - Row 1041 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:37:17] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  74%|███████▍  | 1043/1400 [1:30:53<19:38,  3.30s/it]

[14/Apr/2026 19:37:23] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  75%|███████▍  | 1044/1400 [1:30:59<22:19,  3.76s/it]

[14/Apr/2026 19:37:23] WARNING - Row 1044 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:37:23] WARNING - Row 1045 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:37:28] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  75%|███████▍  | 1047/1400 [1:31:04<16:48,  2.86s/it]

[14/Apr/2026 19:37:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  75%|███████▍  | 1048/1400 [1:31:10<19:29,  3.32s/it]

[14/Apr/2026 19:37:34] WARNING - Row 1048 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:37:34] WARNING - Row 1049 | SKIP | REASONING is empty or missing
[14/Apr/2026 19:37:34] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row1049_20260414_193734.csv (1050 строк)
[14/Apr/2026 19:37:34] INFO - Удалён старый чекпоинт: checkpoints/checkpoint_row899_20260414_192957.csv

Analyzing:  75%|███████▌  | 1050/1400 [1:31:10<13:16,  2.28s/it]

📌 Чекпоинт [1050/1400] → checkpoints/checkpoint_row1049_20260414_193734.csv
[14/Apr/2026 19:37:39] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  75%|███████▌  | 1051/1400 [1:31:15<16:25,  2.82s/it]

[14/Apr/2026 19:37:46] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  75%|███████▌  | 1052/1400 [1:31:22<21:02,  3.63s/it]

[14/Apr/2026 19:37:50] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  75%|███████▌  | 1053/1400 [1:31:27<22:33,  3.90s/it]

[14/Apr/2026 19:37:55] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  75%|███████▌  | 1054/1400 [1:31:32<23:57,  4.16s/it]

[14/Apr/2026 19:38:00] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  75%|███████▌  | 1055/1400 [1:31:37<25:20,  4.41s/it]

[14/Apr/2026 19:38:05] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  75%|███████▌  | 1056/1400 [1:31:42<25:54,  4.52s/it]

[14/Apr/2026 19:38:10] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  76%|███████▌  | 1057/1400 [1:31:47<26:53,  4.70s/it]

[14/Apr/2026 19:38:15] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  76%|███████▌  | 1058/1400 [1:31:51<26:51,  4.71s/it]

[14/Apr/2026 19:38:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  76%|███████▌  | 1059/1400 [1:31:58<30:20,  5.34s/it]

[14/Apr/2026 19:38:28] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  76%|███████▌  | 1060/1400 [1:32:05<31:58,  5.64s/it]

[14/Apr/2026 19:38:33] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  76%|███████▌  | 1061/1400 [1:32:10<30:49,  5.45s/it]

[14/Apr/2026 19:38:38] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  76%|███████▌  | 1062/1400 [1:32:15<30:04,  5.34s/it]

[14/Apr/2026 19:38:43] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  76%|███████▌  | 1063/1400 [1:32:19<28:41,  5.11s/it]

[14/Apr/2026 19:38:48] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  76%|███████▌  | 1064/1400 [1:32:24<28:16,  5.05s/it]

[14/Apr/2026 19:38:53] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  76%|███████▌  | 1065/1400 [1:32:29<28:10,  5.05s/it]

[14/Apr/2026 19:38:58] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  76%|███████▌  | 1066/1400 [1:32:35<28:31,  5.12s/it]

[14/Apr/2026 19:39:03] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  76%|███████▌  | 1067/1400 [1:32:39<27:59,  5.04s/it]

[14/Apr/2026 19:39:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  76%|███████▋  | 1068/1400 [1:32:44<27:37,  4.99s/it]

[14/Apr/2026 19:39:13] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  76%|███████▋  | 1069/1400 [1:32:50<27:54,  5.06s/it]

[14/Apr/2026 19:39:19] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  76%|███████▋  | 1070/1400 [1:32:55<29:00,  5.27s/it]

[14/Apr/2026 19:39:24] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  76%|███████▋  | 1071/1400 [1:33:00<28:23,  5.18s/it]

[14/Apr/2026 19:39:30] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  77%|███████▋  | 1072/1400 [1:33:06<29:36,  5.41s/it]

[14/Apr/2026 19:39:38] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  77%|███████▋  | 1073/1400 [1:33:14<33:03,  6.07s/it]

[14/Apr/2026 19:39:42] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  77%|███████▋  | 1074/1400 [1:33:19<31:04,  5.72s/it]

[14/Apr/2026 19:39:50] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  77%|███████▋  | 1075/1400 [1:33:26<34:14,  6.32s/it]

[14/Apr/2026 19:39:55] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  77%|███████▋  | 1076/1400 [1:33:31<31:20,  5.80s/it]

[14/Apr/2026 19:40:01] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  77%|███████▋  | 1077/1400 [1:33:37<32:03,  5.96s/it]

[14/Apr/2026 19:40:09] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  77%|███████▋  | 1078/1400 [1:33:45<34:29,  6.43s/it]

[14/Apr/2026 19:40:15] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  77%|███████▋  | 1079/1400 [1:33:51<33:51,  6.33s/it]

[14/Apr/2026 19:40:21] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  77%|███████▋  | 1080/1400 [1:33:57<32:58,  6.18s/it]

[14/Apr/2026 19:40:29] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  77%|███████▋  | 1081/1400 [1:34:05<36:03,  6.78s/it]

[14/Apr/2026 19:40:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  77%|███████▋  | 1082/1400 [1:34:10<33:06,  6.25s/it]

[14/Apr/2026 19:40:39] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  77%|███████▋  | 1083/1400 [1:34:15<31:22,  5.94s/it]

[14/Apr/2026 19:40:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  77%|███████▋  | 1084/1400 [1:34:20<29:22,  5.58s/it]

[14/Apr/2026 19:40:48] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  78%|███████▊  | 1085/1400 [1:34:25<27:55,  5.32s/it]

[14/Apr/2026 19:40:55] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  78%|███████▊  | 1086/1400 [1:34:31<29:26,  5.63s/it]

[14/Apr/2026 19:41:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  78%|███████▊  | 1087/1400 [1:34:38<31:48,  6.10s/it]

[14/Apr/2026 19:41:07] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  78%|███████▊  | 1088/1400 [1:34:44<30:46,  5.92s/it]

[14/Apr/2026 19:41:13] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  78%|███████▊  | 1089/1400 [1:34:49<29:45,  5.74s/it]

[14/Apr/2026 19:41:17] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  78%|███████▊  | 1090/1400 [1:34:54<27:56,  5.41s/it]

[14/Apr/2026 19:41:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  78%|███████▊  | 1091/1400 [1:34:58<26:37,  5.17s/it]

[14/Apr/2026 19:41:27] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  78%|███████▊  | 1092/1400 [1:35:03<26:25,  5.15s/it]

[14/Apr/2026 19:41:32] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  78%|███████▊  | 1093/1400 [1:35:09<26:29,  5.18s/it]

[14/Apr/2026 19:41:39] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  78%|███████▊  | 1094/1400 [1:35:15<28:40,  5.62s/it]

[14/Apr/2026 19:41:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  78%|███████▊  | 1095/1400 [1:35:20<27:40,  5.44s/it]

[14/Apr/2026 19:41:50] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  78%|███████▊  | 1096/1400 [1:35:26<27:52,  5.50s/it]

[14/Apr/2026 19:41:55] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  78%|███████▊  | 1097/1400 [1:35:31<27:06,  5.37s/it]

[14/Apr/2026 19:42:00] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  78%|███████▊  | 1098/1400 [1:35:36<26:51,  5.34s/it]

[14/Apr/2026 19:42:05] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  78%|███████▊  | 1099/1400 [1:35:41<26:33,  5.30s/it]

[14/Apr/2026 19:42:10] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[14/Apr/2026 19:42:10] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row1099_20260414_194210.csv (1100 строк)
[14/Apr/2026 19:42:10] INFO - Удалён старый чекпоинт: checkpoints/checkpoint_row949_20260414_193234.csv

Analyzing:  79%|███████▊  | 1100/1400 [1:35:47<26:20,  5.27s/it]

📌 Чекпоинт [1100/1400] → checkpoints/checkpoint_row1099_20260414_194210.csv
[14/Apr/2026 19:42:16] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  79%|███████▊  | 1101/1400 [1:35:53<27:09,  5.45s/it]

[14/Apr/2026 19:42:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  79%|███████▊  | 1102/1400 [1:35:58<27:27,  5.53s/it]

[14/Apr/2026 19:42:29] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  79%|███████▉  | 1103/1400 [1:36:06<30:07,  6.09s/it]

[14/Apr/2026 19:42:36] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  79%|███████▉  | 1104/1400 [1:36:13<31:27,  6.38s/it]

[14/Apr/2026 19:42:43] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  79%|███████▉  | 1105/1400 [1:36:19<31:37,  6.43s/it]

[14/Apr/2026 19:42:50] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  79%|███████▉  | 1106/1400 [1:36:27<32:43,  6.68s/it]

[14/Apr/2026 19:42:57] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  79%|███████▉  | 1107/1400 [1:36:33<32:36,  6.68s/it]

[14/Apr/2026 19:43:03] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  79%|███████▉  | 1108/1400 [1:36:39<31:39,  6.51s/it]

[14/Apr/2026 19:43:12] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  79%|███████▉  | 1109/1400 [1:36:48<35:01,  7.22s/it]

[14/Apr/2026 19:43:19] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  79%|███████▉  | 1110/1400 [1:36:56<35:11,  7.28s/it]

[14/Apr/2026 19:43:25] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  79%|███████▉  | 1111/1400 [1:37:01<32:58,  6.85s/it]

[14/Apr/2026 19:43:33] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  79%|███████▉  | 1112/1400 [1:37:09<34:10,  7.12s/it]

[14/Apr/2026 19:43:43] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  80%|███████▉  | 1113/1400 [1:37:19<38:01,  7.95s/it]

[14/Apr/2026 19:43:52] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  80%|███████▉  | 1114/1400 [1:37:29<40:20,  8.47s/it]

[14/Apr/2026 19:44:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  80%|███████▉  | 1115/1400 [1:37:38<41:03,  8.65s/it]

[14/Apr/2026 19:44:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  80%|███████▉  | 1116/1400 [1:37:44<37:47,  7.98s/it]

[14/Apr/2026 19:44:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  80%|███████▉  | 1117/1400 [1:37:50<35:01,  7.43s/it]

[14/Apr/2026 19:44:20] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  80%|███████▉  | 1118/1400 [1:37:56<32:56,  7.01s/it]

[14/Apr/2026 19:44:26] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  80%|███████▉  | 1119/1400 [1:38:02<30:54,  6.60s/it]

[14/Apr/2026 19:44:31] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  80%|████████  | 1120/1400 [1:38:08<29:26,  6.31s/it]

[14/Apr/2026 19:44:38] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  80%|████████  | 1121/1400 [1:38:14<29:22,  6.32s/it]

[14/Apr/2026 19:44:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  80%|████████  | 1122/1400 [1:38:21<29:31,  6.37s/it]

[14/Apr/2026 19:44:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  80%|████████  | 1123/1400 [1:38:27<29:47,  6.45s/it]

[14/Apr/2026 19:44:57] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  80%|████████  | 1124/1400 [1:38:33<28:56,  6.29s/it]

[14/Apr/2026 19:45:03] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  80%|████████  | 1125/1400 [1:38:40<29:19,  6.40s/it]

[14/Apr/2026 19:45:09] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  80%|████████  | 1126/1400 [1:38:45<28:06,  6.15s/it]

[14/Apr/2026 19:45:15] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  80%|████████  | 1127/1400 [1:38:51<27:06,  5.96s/it]

[14/Apr/2026 19:45:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  81%|████████  | 1128/1400 [1:38:58<29:14,  6.45s/it]

[14/Apr/2026 19:45:29] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  81%|████████  | 1129/1400 [1:39:05<29:46,  6.59s/it]

[14/Apr/2026 19:45:35] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  81%|████████  | 1130/1400 [1:39:12<29:27,  6.55s/it]

[14/Apr/2026 19:45:42] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  81%|████████  | 1131/1400 [1:39:18<29:05,  6.49s/it]

[14/Apr/2026 19:45:49] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  81%|████████  | 1132/1400 [1:39:25<29:25,  6.59s/it]

[14/Apr/2026 19:45:55] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  81%|████████  | 1133/1400 [1:39:32<29:38,  6.66s/it]

[14/Apr/2026 19:46:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  81%|████████  | 1134/1400 [1:39:38<28:49,  6.50s/it]

[14/Apr/2026 19:46:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  81%|████████  | 1135/1400 [1:39:44<28:42,  6.50s/it]

[14/Apr/2026 19:46:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  81%|████████  | 1136/1400 [1:39:50<27:32,  6.26s/it]

[14/Apr/2026 19:46:19] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  81%|████████  | 1137/1400 [1:39:56<26:36,  6.07s/it]

[14/Apr/2026 19:46:25] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  81%|████████▏ | 1138/1400 [1:40:01<25:58,  5.95s/it]

[14/Apr/2026 19:46:31] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  81%|████████▏ | 1139/1400 [1:40:07<25:50,  5.94s/it]

[14/Apr/2026 19:46:37] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  81%|████████▏ | 1140/1400 [1:40:13<25:58,  5.99s/it]

[14/Apr/2026 19:46:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  82%|████████▏ | 1141/1400 [1:40:20<26:42,  6.19s/it]

[14/Apr/2026 19:46:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  82%|████████▏ | 1142/1400 [1:40:27<27:34,  6.41s/it]

[14/Apr/2026 19:46:57] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  82%|████████▏ | 1143/1400 [1:40:33<26:54,  6.28s/it]

[14/Apr/2026 19:47:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  82%|████████▏ | 1144/1400 [1:40:44<33:03,  7.75s/it]

[14/Apr/2026 19:47:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  82%|████████▏ | 1145/1400 [1:40:50<30:27,  7.17s/it]

[14/Apr/2026 19:47:21] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  82%|████████▏ | 1146/1400 [1:40:58<31:05,  7.34s/it]

[14/Apr/2026 19:47:28] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  82%|████████▏ | 1147/1400 [1:41:05<30:24,  7.21s/it]

[14/Apr/2026 19:47:33] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  82%|████████▏ | 1148/1400 [1:41:10<27:40,  6.59s/it]

[14/Apr/2026 19:47:40] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  82%|████████▏ | 1149/1400 [1:41:16<27:38,  6.61s/it]

[14/Apr/2026 19:47:45] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[14/Apr/2026 19:47:45] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row1149_20260414_194745.csv (1150 строк)
[14/Apr/2026 19:47:45] INFO - Удалён старый чекпоинт: checkpoints/checkpoint_row999_20260414_193501.csv

Analyzing:  82%|████████▏ | 1150/1400 [1:41:22<25:41,  6.17s/it]

📌 Чекпоинт [1150/1400] → checkpoints/checkpoint_row1149_20260414_194745.csv
[14/Apr/2026 19:47:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  82%|████████▏ | 1151/1400 [1:41:27<24:33,  5.92s/it]

[14/Apr/2026 19:47:57] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  82%|████████▏ | 1152/1400 [1:41:33<24:41,  5.97s/it]

[14/Apr/2026 19:48:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  82%|████████▏ | 1153/1400 [1:41:38<23:55,  5.81s/it]

[14/Apr/2026 19:48:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  82%|████████▏ | 1154/1400 [1:41:45<24:21,  5.94s/it]

[14/Apr/2026 19:48:16] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  82%|████████▎ | 1155/1400 [1:41:53<26:48,  6.57s/it]

[14/Apr/2026 19:48:24] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  83%|████████▎ | 1156/1400 [1:42:01<28:30,  7.01s/it]

[14/Apr/2026 19:48:29] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  83%|████████▎ | 1157/1400 [1:42:06<25:55,  6.40s/it]

[14/Apr/2026 19:48:35] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  83%|████████▎ | 1158/1400 [1:42:11<24:33,  6.09s/it]

[14/Apr/2026 19:48:41] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  83%|████████▎ | 1159/1400 [1:42:17<24:05,  6.00s/it]

[14/Apr/2026 19:48:46] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  83%|████████▎ | 1160/1400 [1:42:22<23:22,  5.84s/it]

[14/Apr/2026 19:48:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  83%|████████▎ | 1161/1400 [1:42:27<22:05,  5.55s/it]

[14/Apr/2026 19:48:56] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  83%|████████▎ | 1162/1400 [1:42:32<21:37,  5.45s/it]

[14/Apr/2026 19:49:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  83%|████████▎ | 1163/1400 [1:42:38<22:00,  5.57s/it]

[14/Apr/2026 19:49:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  83%|████████▎ | 1164/1400 [1:42:45<22:39,  5.76s/it]

[14/Apr/2026 19:49:17] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  83%|████████▎ | 1165/1400 [1:42:53<25:38,  6.55s/it]

[14/Apr/2026 19:49:24] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  83%|████████▎ | 1166/1400 [1:43:00<26:20,  6.75s/it]

[14/Apr/2026 19:49:30] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  83%|████████▎ | 1167/1400 [1:43:06<25:19,  6.52s/it]

[14/Apr/2026 19:49:36] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  83%|████████▎ | 1168/1400 [1:43:13<25:12,  6.52s/it]

[14/Apr/2026 19:49:42] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  84%|████████▎ | 1169/1400 [1:43:19<24:34,  6.38s/it]

[14/Apr/2026 19:49:49] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  84%|████████▎ | 1170/1400 [1:43:26<25:18,  6.60s/it]

[14/Apr/2026 19:49:56] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  84%|████████▎ | 1171/1400 [1:43:32<24:59,  6.55s/it]

[14/Apr/2026 19:50:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  84%|████████▎ | 1172/1400 [1:43:38<24:09,  6.36s/it]

[14/Apr/2026 19:50:07] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  84%|████████▍ | 1173/1400 [1:43:43<22:24,  5.92s/it]

[14/Apr/2026 19:50:13] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  84%|████████▍ | 1174/1400 [1:43:49<22:53,  6.08s/it]

[14/Apr/2026 19:50:18] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  84%|████████▍ | 1175/1400 [1:43:55<21:52,  5.83s/it]

[14/Apr/2026 19:50:26] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  84%|████████▍ | 1176/1400 [1:44:02<23:36,  6.32s/it]

[14/Apr/2026 19:50:31] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  84%|████████▍ | 1177/1400 [1:44:07<22:18,  6.00s/it]

[14/Apr/2026 19:50:37] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  84%|████████▍ | 1178/1400 [1:44:13<21:50,  5.90s/it]

[14/Apr/2026 19:50:43] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  84%|████████▍ | 1179/1400 [1:44:19<21:55,  5.95s/it]

[14/Apr/2026 19:50:50] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  84%|████████▍ | 1180/1400 [1:44:27<23:24,  6.38s/it]

[14/Apr/2026 19:50:58] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  84%|████████▍ | 1181/1400 [1:44:35<25:04,  6.87s/it]

[14/Apr/2026 19:51:03] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  84%|████████▍ | 1182/1400 [1:44:40<22:57,  6.32s/it]

[14/Apr/2026 19:51:09] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  84%|████████▍ | 1183/1400 [1:44:45<21:50,  6.04s/it]

[14/Apr/2026 19:51:19] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  85%|████████▍ | 1184/1400 [1:44:56<26:37,  7.40s/it]

[14/Apr/2026 19:51:26] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  85%|████████▍ | 1185/1400 [1:45:02<25:42,  7.18s/it]

[14/Apr/2026 19:51:32] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  85%|████████▍ | 1186/1400 [1:45:08<23:56,  6.71s/it]

[14/Apr/2026 19:51:41] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  85%|████████▍ | 1187/1400 [1:45:17<26:22,  7.43s/it]

[14/Apr/2026 19:51:46] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  85%|████████▍ | 1188/1400 [1:45:22<24:09,  6.84s/it]

[14/Apr/2026 19:51:52] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  85%|████████▍ | 1189/1400 [1:45:28<22:33,  6.41s/it]

[14/Apr/2026 19:51:57] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  85%|████████▌ | 1190/1400 [1:45:33<21:03,  6.02s/it]

[14/Apr/2026 19:52:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  85%|████████▌ | 1191/1400 [1:45:38<20:26,  5.87s/it]

[14/Apr/2026 19:52:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  85%|████████▌ | 1192/1400 [1:45:44<20:12,  5.83s/it]

[14/Apr/2026 19:52:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  85%|████████▌ | 1193/1400 [1:45:50<19:56,  5.78s/it]

[14/Apr/2026 19:52:20] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  85%|████████▌ | 1194/1400 [1:45:56<20:10,  5.88s/it]

[14/Apr/2026 19:52:26] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  85%|████████▌ | 1195/1400 [1:46:02<20:09,  5.90s/it]

[14/Apr/2026 19:52:31] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  85%|████████▌ | 1196/1400 [1:46:07<19:18,  5.68s/it]

[14/Apr/2026 19:52:37] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  86%|████████▌ | 1197/1400 [1:46:13<19:30,  5.76s/it]

[14/Apr/2026 19:52:42] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  86%|████████▌ | 1198/1400 [1:46:19<19:06,  5.68s/it]

[14/Apr/2026 19:52:48] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  86%|████████▌ | 1199/1400 [1:46:25<19:22,  5.79s/it]

[14/Apr/2026 19:52:55] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[14/Apr/2026 19:52:56] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row1199_20260414_195255.csv (1200 строк)
[14/Apr/2026 19:52:56] INFO - Удалён старый чекпоинт: checkpoints/checkpoint_row1049_20260414_193734.csv

Analyzing:  86%|████████▌ | 1200/1400 [1:46:32<21:07,  6.34s/it]

📌 Чекпоинт [1200/1400] → checkpoints/checkpoint_row1199_20260414_195255.csv
[14/Apr/2026 19:53:01] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  86%|████████▌ | 1201/1400 [1:46:37<19:52,  5.99s/it]

[14/Apr/2026 19:53:07] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  86%|████████▌ | 1202/1400 [1:46:43<19:39,  5.96s/it]

[14/Apr/2026 19:53:12] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  86%|████████▌ | 1203/1400 [1:46:49<18:56,  5.77s/it]

[14/Apr/2026 19:53:18] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  86%|████████▌ | 1204/1400 [1:46:54<18:47,  5.75s/it]

[14/Apr/2026 19:53:23] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  86%|████████▌ | 1205/1400 [1:46:59<17:58,  5.53s/it]

[14/Apr/2026 19:53:28] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  86%|████████▌ | 1206/1400 [1:47:05<17:38,  5.46s/it]

[14/Apr/2026 19:53:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  86%|████████▌ | 1207/1400 [1:47:10<17:54,  5.57s/it]

[14/Apr/2026 19:53:41] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  86%|████████▋ | 1208/1400 [1:47:17<18:40,  5.83s/it]

[14/Apr/2026 19:53:46] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  86%|████████▋ | 1209/1400 [1:47:22<18:10,  5.71s/it]

[14/Apr/2026 19:53:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  86%|████████▋ | 1210/1400 [1:47:27<17:20,  5.48s/it]

[14/Apr/2026 19:53:57] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  86%|████████▋ | 1211/1400 [1:47:33<17:34,  5.58s/it]

[14/Apr/2026 19:54:04] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  87%|████████▋ | 1212/1400 [1:47:41<19:16,  6.15s/it]

[14/Apr/2026 19:54:10] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  87%|████████▋ | 1213/1400 [1:47:46<18:58,  6.09s/it]

[14/Apr/2026 19:54:16] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  87%|████████▋ | 1214/1400 [1:47:52<18:42,  6.03s/it]

[14/Apr/2026 19:54:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  87%|████████▋ | 1215/1400 [1:47:58<18:17,  5.93s/it]

[14/Apr/2026 19:54:28] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  87%|████████▋ | 1216/1400 [1:48:04<18:32,  6.05s/it]

[14/Apr/2026 19:54:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  87%|████████▋ | 1217/1400 [1:48:10<18:02,  5.92s/it]

[14/Apr/2026 19:54:40] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  87%|████████▋ | 1218/1400 [1:48:16<18:22,  6.06s/it]

[14/Apr/2026 19:54:47] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  87%|████████▋ | 1219/1400 [1:48:23<19:06,  6.33s/it]

[14/Apr/2026 19:54:56] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  87%|████████▋ | 1220/1400 [1:48:33<21:35,  7.20s/it]

[14/Apr/2026 19:55:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  87%|████████▋ | 1221/1400 [1:48:38<20:14,  6.78s/it]

[14/Apr/2026 19:55:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  87%|████████▋ | 1222/1400 [1:48:45<19:43,  6.65s/it]

[14/Apr/2026 19:55:15] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  87%|████████▋ | 1223/1400 [1:48:51<19:40,  6.67s/it]

[14/Apr/2026 19:55:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  87%|████████▋ | 1224/1400 [1:48:58<19:34,  6.67s/it]

[14/Apr/2026 19:55:28] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  88%|████████▊ | 1225/1400 [1:49:05<19:17,  6.62s/it]

[14/Apr/2026 19:55:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  88%|████████▊ | 1226/1400 [1:49:10<18:01,  6.22s/it]

[14/Apr/2026 19:55:39] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  88%|████████▊ | 1227/1400 [1:49:15<17:15,  5.99s/it]

[14/Apr/2026 19:55:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  88%|████████▊ | 1228/1400 [1:49:20<16:24,  5.72s/it]

[14/Apr/2026 19:55:49] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  88%|████████▊ | 1229/1400 [1:49:26<15:50,  5.56s/it]

[14/Apr/2026 19:55:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  88%|████████▊ | 1230/1400 [1:49:30<15:00,  5.30s/it]

[14/Apr/2026 19:56:00] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  88%|████████▊ | 1231/1400 [1:49:37<15:51,  5.63s/it]

[14/Apr/2026 19:56:06] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  88%|████████▊ | 1232/1400 [1:49:42<15:19,  5.47s/it]

[14/Apr/2026 19:56:11] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  88%|████████▊ | 1233/1400 [1:49:47<14:55,  5.36s/it]

[14/Apr/2026 19:56:19] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  88%|████████▊ | 1234/1400 [1:49:55<17:16,  6.24s/it]

[14/Apr/2026 19:56:25] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  88%|████████▊ | 1235/1400 [1:50:01<16:48,  6.11s/it]

[14/Apr/2026 19:56:30] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  88%|████████▊ | 1236/1400 [1:50:06<15:49,  5.79s/it]

[14/Apr/2026 19:56:35] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  88%|████████▊ | 1237/1400 [1:50:11<15:25,  5.67s/it]

[14/Apr/2026 19:56:41] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  88%|████████▊ | 1238/1400 [1:50:18<15:49,  5.86s/it]

[14/Apr/2026 19:56:47] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  88%|████████▊ | 1239/1400 [1:50:24<15:45,  5.87s/it]

[14/Apr/2026 19:56:56] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  89%|████████▊ | 1240/1400 [1:50:33<18:05,  6.78s/it]

[14/Apr/2026 19:57:05] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  89%|████████▊ | 1241/1400 [1:50:41<19:18,  7.29s/it]

[14/Apr/2026 19:57:10] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  89%|████████▊ | 1242/1400 [1:50:47<17:50,  6.77s/it]

[14/Apr/2026 19:57:17] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  89%|████████▉ | 1243/1400 [1:50:53<17:37,  6.74s/it]

[14/Apr/2026 19:57:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  89%|████████▉ | 1244/1400 [1:50:59<16:28,  6.33s/it]

[14/Apr/2026 19:57:29] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  89%|████████▉ | 1245/1400 [1:51:06<16:46,  6.49s/it]

[14/Apr/2026 19:57:38] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  89%|████████▉ | 1246/1400 [1:51:15<18:36,  7.25s/it]

[14/Apr/2026 19:57:45] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  89%|████████▉ | 1247/1400 [1:51:21<17:58,  7.05s/it]

[14/Apr/2026 19:57:50] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  89%|████████▉ | 1248/1400 [1:51:27<16:43,  6.60s/it]

[14/Apr/2026 19:57:55] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  89%|████████▉ | 1249/1400 [1:51:32<15:24,  6.12s/it]

[14/Apr/2026 19:58:01] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[14/Apr/2026 19:58:01] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row1249_20260414_195801.csv (1250 строк)
[14/Apr/2026 19:58:01] INFO - Удалён старый чекпоинт: checkpoints/checkpoint_row1099_20260414_194210.csv

Analyzing:  89%|████████▉ | 1250/1400 [1:51:38<15:16,  6.11s/it]

📌 Чекпоинт [1250/1400] → checkpoints/checkpoint_row1249_20260414_195801.csv
[14/Apr/2026 19:58:07] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  89%|████████▉ | 1251/1400 [1:51:43<14:27,  5.82s/it]

[14/Apr/2026 19:58:12] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  89%|████████▉ | 1252/1400 [1:51:48<13:53,  5.63s/it]

[14/Apr/2026 19:58:17] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  90%|████████▉ | 1253/1400 [1:51:53<13:23,  5.46s/it]

[14/Apr/2026 19:58:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  90%|████████▉ | 1254/1400 [1:51:58<13:11,  5.42s/it]

[14/Apr/2026 19:58:28] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  90%|████████▉ | 1255/1400 [1:52:04<13:13,  5.47s/it]

[14/Apr/2026 19:58:33] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  90%|████████▉ | 1256/1400 [1:52:09<12:40,  5.28s/it]

[14/Apr/2026 19:58:38] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  90%|████████▉ | 1257/1400 [1:52:14<12:36,  5.29s/it]

[14/Apr/2026 19:58:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  90%|████████▉ | 1258/1400 [1:52:20<12:58,  5.48s/it]

[14/Apr/2026 19:58:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  90%|████████▉ | 1259/1400 [1:52:27<13:42,  5.84s/it]

[14/Apr/2026 19:58:56] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  90%|█████████ | 1260/1400 [1:52:32<13:06,  5.62s/it]

[14/Apr/2026 19:59:01] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  90%|█████████ | 1261/1400 [1:52:37<12:32,  5.41s/it]

[14/Apr/2026 19:59:11] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  90%|█████████ | 1262/1400 [1:52:47<15:59,  6.95s/it]

[14/Apr/2026 19:59:16] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  90%|█████████ | 1263/1400 [1:52:52<14:10,  6.21s/it]

[14/Apr/2026 19:59:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  90%|█████████ | 1264/1400 [1:52:58<13:59,  6.18s/it]

[14/Apr/2026 19:59:27] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  90%|█████████ | 1265/1400 [1:53:03<13:05,  5.82s/it]

[14/Apr/2026 19:59:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  90%|█████████ | 1266/1400 [1:53:10<13:59,  6.27s/it]

[14/Apr/2026 19:59:41] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  90%|█████████ | 1267/1400 [1:53:18<14:32,  6.56s/it]

[14/Apr/2026 19:59:46] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  91%|█████████ | 1268/1400 [1:53:22<13:16,  6.03s/it]

[14/Apr/2026 19:59:52] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  91%|█████████ | 1269/1400 [1:53:28<13:14,  6.06s/it]

[14/Apr/2026 20:00:00] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  91%|█████████ | 1270/1400 [1:53:36<14:06,  6.51s/it]

[14/Apr/2026 20:00:05] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  91%|█████████ | 1271/1400 [1:53:41<13:06,  6.09s/it]

[14/Apr/2026 20:00:13] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  91%|█████████ | 1272/1400 [1:53:50<14:29,  6.80s/it]

[14/Apr/2026 20:00:19] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  91%|█████████ | 1273/1400 [1:53:55<13:24,  6.34s/it]

[14/Apr/2026 20:00:24] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  91%|█████████ | 1274/1400 [1:54:00<12:47,  6.09s/it]

[14/Apr/2026 20:00:31] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  91%|█████████ | 1275/1400 [1:54:07<13:15,  6.36s/it]

[14/Apr/2026 20:00:35] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  91%|█████████ | 1276/1400 [1:54:12<11:57,  5.78s/it]

[14/Apr/2026 20:00:43] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  91%|█████████ | 1277/1400 [1:54:19<12:46,  6.23s/it]

[14/Apr/2026 20:00:48] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  91%|█████████▏| 1278/1400 [1:54:24<12:02,  5.92s/it]

[14/Apr/2026 20:00:53] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  91%|█████████▏| 1279/1400 [1:54:29<11:10,  5.54s/it]

[14/Apr/2026 20:00:59] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  91%|█████████▏| 1280/1400 [1:54:35<11:39,  5.83s/it]

[14/Apr/2026 20:01:06] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  92%|█████████▏| 1281/1400 [1:54:42<11:55,  6.02s/it]

[14/Apr/2026 20:01:12] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  92%|█████████▏| 1282/1400 [1:54:49<12:14,  6.22s/it]

[14/Apr/2026 20:01:17] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  92%|█████████▏| 1283/1400 [1:54:54<11:31,  5.91s/it]

[14/Apr/2026 20:01:24] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  92%|█████████▏| 1284/1400 [1:55:01<11:57,  6.18s/it]

[14/Apr/2026 20:01:31] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  92%|█████████▏| 1285/1400 [1:55:07<12:04,  6.30s/it]

[14/Apr/2026 20:01:37] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  92%|█████████▏| 1286/1400 [1:55:13<11:57,  6.30s/it]

[14/Apr/2026 20:01:43] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  92%|█████████▏| 1287/1400 [1:55:19<11:39,  6.19s/it]

[14/Apr/2026 20:01:49] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  92%|█████████▏| 1288/1400 [1:55:25<11:13,  6.01s/it]

[14/Apr/2026 20:01:55] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  92%|█████████▏| 1289/1400 [1:55:31<11:06,  6.00s/it]

[14/Apr/2026 20:02:00] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  92%|█████████▏| 1290/1400 [1:55:36<10:22,  5.66s/it]

[14/Apr/2026 20:02:04] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  92%|█████████▏| 1291/1400 [1:55:41<09:51,  5.42s/it]

[14/Apr/2026 20:02:12] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  92%|█████████▏| 1292/1400 [1:55:48<10:49,  6.01s/it]

[14/Apr/2026 20:02:17] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  92%|█████████▏| 1293/1400 [1:55:53<10:22,  5.82s/it]

[14/Apr/2026 20:02:23] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  92%|█████████▏| 1294/1400 [1:56:00<10:26,  5.91s/it]

[14/Apr/2026 20:02:29] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  92%|█████████▎| 1295/1400 [1:56:05<10:03,  5.74s/it]

[14/Apr/2026 20:02:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  93%|█████████▎| 1296/1400 [1:56:10<09:45,  5.63s/it]

[14/Apr/2026 20:02:39] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  93%|█████████▎| 1297/1400 [1:56:15<09:27,  5.51s/it]

[14/Apr/2026 20:02:45] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  93%|█████████▎| 1298/1400 [1:56:21<09:20,  5.49s/it]

[14/Apr/2026 20:02:50] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  93%|█████████▎| 1299/1400 [1:56:26<09:14,  5.49s/it]

[14/Apr/2026 20:02:56] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[14/Apr/2026 20:02:56] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row1299_20260414_200256.csv (1300 строк)
[14/Apr/2026 20:02:56] INFO - Удалён старый чекпоинт: checkpoints/checkpoint_row1149_20260414_194745.csv

Analyzing:  93%|█████████▎| 1300/1400 [1:56:32<09:17,  5.58s/it]

📌 Чекпоинт [1300/1400] → checkpoints/checkpoint_row1299_20260414_200256.csv
[14/Apr/2026 20:03:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  93%|█████████▎| 1301/1400 [1:56:38<09:25,  5.71s/it]

[14/Apr/2026 20:03:07] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  93%|█████████▎| 1302/1400 [1:56:44<09:10,  5.62s/it]

[14/Apr/2026 20:03:12] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  93%|█████████▎| 1303/1400 [1:56:49<08:50,  5.47s/it]

[14/Apr/2026 20:03:18] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  93%|█████████▎| 1304/1400 [1:56:54<08:40,  5.42s/it]

[14/Apr/2026 20:03:23] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  93%|█████████▎| 1305/1400 [1:56:59<08:23,  5.30s/it]

[14/Apr/2026 20:03:28] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  93%|█████████▎| 1306/1400 [1:57:05<08:25,  5.38s/it]

[14/Apr/2026 20:03:35] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  93%|█████████▎| 1307/1400 [1:57:11<08:59,  5.80s/it]

[14/Apr/2026 20:03:42] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  93%|█████████▎| 1308/1400 [1:57:18<09:27,  6.17s/it]

[14/Apr/2026 20:03:48] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  94%|█████████▎| 1309/1400 [1:57:24<09:12,  6.07s/it]

[14/Apr/2026 20:03:54] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  94%|█████████▎| 1310/1400 [1:57:30<08:57,  5.97s/it]

[14/Apr/2026 20:04:00] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  94%|█████████▎| 1311/1400 [1:57:36<08:50,  5.96s/it]

[14/Apr/2026 20:04:05] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  94%|█████████▎| 1312/1400 [1:57:41<08:30,  5.80s/it]

[14/Apr/2026 20:04:11] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  94%|█████████▍| 1313/1400 [1:57:47<08:20,  5.76s/it]

[14/Apr/2026 20:04:19] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  94%|█████████▍| 1314/1400 [1:57:55<09:07,  6.37s/it]

[14/Apr/2026 20:04:23] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  94%|█████████▍| 1315/1400 [1:58:00<08:24,  5.93s/it]

[14/Apr/2026 20:04:30] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  94%|█████████▍| 1316/1400 [1:58:07<08:42,  6.22s/it]

[14/Apr/2026 20:04:36] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  94%|█████████▍| 1317/1400 [1:58:12<08:20,  6.03s/it]

[14/Apr/2026 20:04:41] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  94%|█████████▍| 1318/1400 [1:58:17<07:51,  5.75s/it]

[14/Apr/2026 20:04:47] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  94%|█████████▍| 1319/1400 [1:58:23<07:41,  5.69s/it]

[14/Apr/2026 20:04:52] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  94%|█████████▍| 1320/1400 [1:58:28<07:28,  5.60s/it]

[14/Apr/2026 20:04:58] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  94%|█████████▍| 1321/1400 [1:58:34<07:20,  5.58s/it]

[14/Apr/2026 20:05:03] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  94%|█████████▍| 1322/1400 [1:58:40<07:21,  5.66s/it]

[14/Apr/2026 20:05:09] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  94%|█████████▍| 1323/1400 [1:58:45<07:14,  5.65s/it]

[14/Apr/2026 20:05:15] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  95%|█████████▍| 1324/1400 [1:58:51<07:13,  5.70s/it]

[14/Apr/2026 20:05:20] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  95%|█████████▍| 1325/1400 [1:58:56<06:49,  5.46s/it]

[14/Apr/2026 20:05:25] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  95%|█████████▍| 1326/1400 [1:59:01<06:39,  5.39s/it]

[14/Apr/2026 20:05:33] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  95%|█████████▍| 1327/1400 [1:59:10<07:40,  6.31s/it]

[14/Apr/2026 20:05:41] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  95%|█████████▍| 1328/1400 [1:59:17<07:56,  6.62s/it]

[14/Apr/2026 20:05:46] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  95%|█████████▍| 1329/1400 [1:59:22<07:16,  6.14s/it]

[14/Apr/2026 20:05:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  95%|█████████▌| 1330/1400 [1:59:27<06:50,  5.86s/it]

[14/Apr/2026 20:05:57] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  95%|█████████▌| 1331/1400 [1:59:33<06:44,  5.87s/it]

[14/Apr/2026 20:06:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  95%|█████████▌| 1332/1400 [1:59:38<06:25,  5.66s/it]

[14/Apr/2026 20:06:07] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  95%|█████████▌| 1333/1400 [1:59:44<06:12,  5.56s/it]

[14/Apr/2026 20:06:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  95%|█████████▌| 1334/1400 [1:59:51<06:32,  5.95s/it]

[14/Apr/2026 20:06:19] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  95%|█████████▌| 1335/1400 [1:59:56<06:10,  5.70s/it]

[14/Apr/2026 20:06:24] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  95%|█████████▌| 1336/1400 [2:00:00<05:44,  5.38s/it]

[14/Apr/2026 20:06:29] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  96%|█████████▌| 1337/1400 [2:00:05<05:33,  5.29s/it]

[14/Apr/2026 20:06:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  96%|█████████▌| 1338/1400 [2:00:10<05:19,  5.16s/it]

[14/Apr/2026 20:06:40] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  96%|█████████▌| 1339/1400 [2:00:16<05:22,  5.29s/it]

[14/Apr/2026 20:06:46] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  96%|█████████▌| 1340/1400 [2:00:22<05:30,  5.51s/it]

[14/Apr/2026 20:06:52] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  96%|█████████▌| 1341/1400 [2:00:29<05:49,  5.92s/it]

[14/Apr/2026 20:06:58] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  96%|█████████▌| 1342/1400 [2:00:34<05:29,  5.68s/it]

[14/Apr/2026 20:07:05] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  96%|█████████▌| 1343/1400 [2:00:41<05:51,  6.16s/it]

[14/Apr/2026 20:07:10] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  96%|█████████▌| 1344/1400 [2:00:46<05:26,  5.84s/it]

[14/Apr/2026 20:07:23] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  96%|█████████▌| 1345/1400 [2:00:59<07:23,  8.07s/it]

[14/Apr/2026 20:07:29] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  96%|█████████▌| 1346/1400 [2:01:06<06:46,  7.53s/it]

[14/Apr/2026 20:07:35] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  96%|█████████▌| 1347/1400 [2:01:11<06:02,  6.84s/it]

[14/Apr/2026 20:07:41] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  96%|█████████▋| 1348/1400 [2:01:17<05:41,  6.56s/it]

[14/Apr/2026 20:07:46] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  96%|█████████▋| 1349/1400 [2:01:22<05:10,  6.09s/it]

[14/Apr/2026 20:07:55] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[14/Apr/2026 20:07:56] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row1349_20260414_200755.csv (1350 строк)
[14/Apr/2026 20:07:56] INFO - Удалён старый чекпоинт: checkpoints/checkpoint_row1199_20260414_195255.csv

Analyzing:  96%|█████████▋| 1350/1400 [2:01:32<06:10,  7.42s/it]

📌 Чекпоинт [1350/1400] → checkpoints/checkpoint_row1349_20260414_200755.csv
[14/Apr/2026 20:08:01] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  96%|█████████▋| 1351/1400 [2:01:38<05:33,  6.81s/it]

[14/Apr/2026 20:08:07] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  97%|█████████▋| 1352/1400 [2:01:43<05:08,  6.43s/it]

[14/Apr/2026 20:08:16] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  97%|█████████▋| 1353/1400 [2:01:52<05:40,  7.25s/it]

[14/Apr/2026 20:08:22] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  97%|█████████▋| 1354/1400 [2:01:58<05:09,  6.72s/it]

[14/Apr/2026 20:08:26] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  97%|█████████▋| 1355/1400 [2:02:02<04:32,  6.05s/it]

[14/Apr/2026 20:08:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  97%|█████████▋| 1356/1400 [2:02:10<04:45,  6.48s/it]

[14/Apr/2026 20:08:39] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  97%|█████████▋| 1357/1400 [2:02:16<04:30,  6.28s/it]

[14/Apr/2026 20:08:45] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  97%|█████████▋| 1358/1400 [2:02:21<04:10,  5.96s/it]

[14/Apr/2026 20:08:51] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  97%|█████████▋| 1359/1400 [2:02:27<04:08,  6.07s/it]

[14/Apr/2026 20:08:57] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  97%|█████████▋| 1360/1400 [2:02:33<03:56,  5.91s/it]

[14/Apr/2026 20:09:03] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  97%|█████████▋| 1361/1400 [2:02:39<03:54,  6.00s/it]

[14/Apr/2026 20:09:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  97%|█████████▋| 1362/1400 [2:02:45<03:43,  5.87s/it]

[14/Apr/2026 20:09:14] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  97%|█████████▋| 1363/1400 [2:02:51<03:40,  5.95s/it]

[14/Apr/2026 20:09:20] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  97%|█████████▋| 1364/1400 [2:02:57<03:32,  5.89s/it]

[14/Apr/2026 20:09:26] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  98%|█████████▊| 1365/1400 [2:03:02<03:22,  5.78s/it]

[14/Apr/2026 20:09:31] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  98%|█████████▊| 1366/1400 [2:03:07<03:10,  5.61s/it]

[14/Apr/2026 20:09:37] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  98%|█████████▊| 1367/1400 [2:03:13<03:05,  5.62s/it]

[14/Apr/2026 20:09:42] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  98%|█████████▊| 1368/1400 [2:03:19<02:59,  5.62s/it]

[14/Apr/2026 20:09:47] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  98%|█████████▊| 1369/1400 [2:03:24<02:49,  5.47s/it]

[14/Apr/2026 20:09:53] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  98%|█████████▊| 1370/1400 [2:03:29<02:42,  5.42s/it]

[14/Apr/2026 20:09:58] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  98%|█████████▊| 1371/1400 [2:03:34<02:35,  5.37s/it]

[14/Apr/2026 20:10:06] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  98%|█████████▊| 1372/1400 [2:03:42<02:53,  6.20s/it]

[14/Apr/2026 20:10:12] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  98%|█████████▊| 1373/1400 [2:03:49<02:47,  6.21s/it]

[14/Apr/2026 20:10:18] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  98%|█████████▊| 1374/1400 [2:03:54<02:37,  6.05s/it]

[14/Apr/2026 20:10:23] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  98%|█████████▊| 1375/1400 [2:04:00<02:26,  5.87s/it]

[14/Apr/2026 20:10:28] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  98%|█████████▊| 1376/1400 [2:04:05<02:14,  5.60s/it]

[14/Apr/2026 20:10:33] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  98%|█████████▊| 1377/1400 [2:04:10<02:05,  5.45s/it]

[14/Apr/2026 20:10:39] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  98%|█████████▊| 1378/1400 [2:04:15<01:57,  5.35s/it]

[14/Apr/2026 20:10:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  98%|█████████▊| 1379/1400 [2:04:21<01:54,  5.45s/it]

[14/Apr/2026 20:10:50] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  99%|█████████▊| 1380/1400 [2:04:26<01:49,  5.48s/it]

[14/Apr/2026 20:10:57] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  99%|█████████▊| 1381/1400 [2:04:33<01:53,  6.00s/it]

[14/Apr/2026 20:11:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  99%|█████████▊| 1382/1400 [2:04:39<01:45,  5.84s/it]

[14/Apr/2026 20:11:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  99%|█████████▉| 1383/1400 [2:04:44<01:35,  5.64s/it]

[14/Apr/2026 20:11:13] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  99%|█████████▉| 1384/1400 [2:04:49<01:28,  5.54s/it]

[14/Apr/2026 20:11:18] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  99%|█████████▉| 1385/1400 [2:04:54<01:20,  5.36s/it]

[14/Apr/2026 20:11:23] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  99%|█████████▉| 1386/1400 [2:05:00<01:15,  5.38s/it]

[14/Apr/2026 20:11:30] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  99%|█████████▉| 1387/1400 [2:05:07<01:16,  5.90s/it]

[14/Apr/2026 20:11:36] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  99%|█████████▉| 1388/1400 [2:05:12<01:07,  5.67s/it]

[14/Apr/2026 20:11:42] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  99%|█████████▉| 1389/1400 [2:05:18<01:03,  5.78s/it]

[14/Apr/2026 20:11:47] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  99%|█████████▉| 1390/1400 [2:05:23<00:55,  5.57s/it]

[14/Apr/2026 20:11:52] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  99%|█████████▉| 1391/1400 [2:05:28<00:48,  5.39s/it]

[14/Apr/2026 20:11:57] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing:  99%|█████████▉| 1392/1400 [2:05:33<00:42,  5.34s/it]

[14/Apr/2026 20:12:02] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing: 100%|█████████▉| 1393/1400 [2:05:39<00:37,  5.38s/it]

[14/Apr/2026 20:12:08] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing: 100%|█████████▉| 1394/1400 [2:05:44<00:32,  5.35s/it]

[14/Apr/2026 20:12:15] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing: 100%|█████████▉| 1395/1400 [2:05:51<00:29,  5.96s/it]

[14/Apr/2026 20:12:20] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing: 100%|█████████▉| 1396/1400 [2:05:56<00:22,  5.72s/it]

[14/Apr/2026 20:12:29] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing: 100%|█████████▉| 1397/1400 [2:06:05<00:19,  6.55s/it]

[14/Apr/2026 20:12:34] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing: 100%|█████████▉| 1398/1400 [2:06:10<00:12,  6.18s/it]

[14/Apr/2026 20:12:38] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"

Analyzing: 100%|█████████▉| 1399/1400 [2:06:15<00:05,  5.65s/it]

[14/Apr/2026 20:12:44] INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
[14/Apr/2026 20:12:44] INFO - Чекпоинт сохранён: checkpoints/checkpoint_row1399_20260414_201244.csv (1400 строк)
[14/Apr/2026 20:12:44] INFO - Удалён старый чекпоинт: checkpoints/checkpoint_row1249_20260414_195801.csv

Analyzing: 100%|██████████| 1400/1400 [2:06:21<00:00,  5.42s/it]

📌 Чекпоинт [1400/1400] → checkpoints/checkpoint_row1399_20260414_201244.csv

============================================================
           ОТЧЁТ О МОНИТОРИНГЕ ОШИБОК
============================================================
  Время выполнения  : 7630.6 сек
  Всего строк       : 1400
  ✅ Успешно         : 1193
  ❌ Ошибок          : 207
  ⏭  Пропущено       : 207
  🔁 Retry-запросов  : 0

  Разбивка по типам ошибок:
    [ 207]  EmptyReasoning            — Поле REASONING пустое или отсутствует
============================================================
[14/Apr/2026 20:12:45] WARNING - ФИНАЛЬНЫЙ ОТЧЁТ:

============================================================
           ОТЧЁТ О МОНИТОРИНГЕ ОШИБОК
============================================================
  Время выполнения  : 7630.6 сек
  Всего строк       : 1400
  ✅ Успешно         : 1193
  ❌ Ошибок          : 207
  ⏭  Пропущено       : 207
  🔁 Retry-запросов  : 0

  Разбивка по типам ошибок:
    [ 207]  EmptyReasoning            — Поле REASONING пустое или отсутствует
============================================================

Файлы сохранены:
   CSV:        responses_final_incentive_C_balanced_realism_50_reasoning_trace_markup.csv
   Parquet:    responses_final_incentive_C_balanced_realism_50_reasoning_trace_markup.parquet
   Лог:        analysis_errors.log
   Чекпоинты: checkpoints/

Добавленные колонки:
   • treatment_awareness_score
   • treatment_awareness_explanation
   • incentive_awareness_score
   • incentive_awareness_explanation
   • reasoning_style_primary_strategy
   • reasoning_style_internal_conflict
   • epistemic_certainty
   • extracted_topics
   • social_desirability_normative_orientation
   • social_desirability_fear_of_judgment
   • social_desirability_safe_answer_shift
   • role_adherence_ai_leakage
   • role_adherence_role_immersion
   • affective_state_valence
   • affective_state_dominant_emotion
   • cognitive_attribution_locus_of_control
   • cognitive_attribution_temporal_focus
   • epistemic_assumptions_hallucinated_conditions
   • api_error